<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Greg Ridgeway">
<meta name="author" content="Ruth Moyer">
<meta name="author" content="Li Sian Goh">
<meta name="dcterms.date" content="2025-08-14">

<title>Introduction to SQL</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="06_Introduction_to_SQL1_files/libs/clipboard/clipboard.min.js"></script>
<script src="06_Introduction_to_SQL1_files/libs/quarto-html/quarto.js"></script>
<script src="06_Introduction_to_SQL1_files/libs/quarto-html/popper.min.js"></script>
<script src="06_Introduction_to_SQL1_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="06_Introduction_to_SQL1_files/libs/quarto-html/anchor.min.js"></script>
<link href="06_Introduction_to_SQL1_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="06_Introduction_to_SQL1_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="06_Introduction_to_SQL1_files/libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="06_Introduction_to_SQL1_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="06_Introduction_to_SQL1_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="06_Introduction_to_SQL1_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="06_Introduction_to_SQL1_files/libs/bootstrap/bootstrap-dark.min.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#getting-the-data-into-proper-form" id="toc-getting-the-data-into-proper-form" class="nav-link" data-scroll-target="#getting-the-data-into-proper-form"><span class="header-section-number">2</span> Getting the data into proper form</a></li>
  <li><a href="#setting-up-the-database" id="toc-setting-up-the-database" class="nav-link" data-scroll-target="#setting-up-the-database"><span class="header-section-number">3</span> Setting up the database</a></li>
  <li><a href="#sql-queries-select-where-from" id="toc-sql-queries-select-where-from" class="nav-link" data-scroll-target="#sql-queries-select-where-from"><span class="header-section-number">4</span> SQL queries (<code>SELECT</code>, <code>WHERE</code>, <code>FROM</code>)</a>
  <ul class="collapse">
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">4.1</span> Exercises</a></li>
  </ul></li>
  <li><a href="#group_by-and-aggregation-functions" id="toc-group_by-and-aggregation-functions" class="nav-link" data-scroll-target="#group_by-and-aggregation-functions"><span class="header-section-number">5</span> <code>GROUP_BY</code> and aggregation functions</a>
  <ul class="collapse">
  <li><a href="#exercises-1" id="toc-exercises-1" class="nav-link" data-scroll-target="#exercises-1"><span class="header-section-number">5.1</span> Exercises</a></li>
  </ul></li>
  <li><a href="#order_by-and-update" id="toc-order_by-and-update" class="nav-link" data-scroll-target="#order_by-and-update"><span class="header-section-number">6</span> <code>ORDER_BY</code> and <code>UPDATE</code></a>
  <ul class="collapse">
  <li><a href="#exercises-2" id="toc-exercises-2" class="nav-link" data-scroll-target="#exercises-2"><span class="header-section-number">6.1</span> Exercises</a></li>
  </ul></li>
  <li><a href="#solutions-to-the-exercises" id="toc-solutions-to-the-exercises" class="nav-link" data-scroll-target="#solutions-to-the-exercises"><span class="header-section-number">7</span> Solutions to the exercises</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="06_Introduction_to_SQL1.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Introduction to SQL</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Greg Ridgeway <a href="mailto:gridge@upenn.edu" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Pennsylvania
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Ruth Moyer <a href="mailto:moyruth@upenn.edu" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Pennsylvania
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Li Sian Goh <a href="mailto:gohl@upenn.edu" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Pennsylvania
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 14, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<!-- In terminal -->
<!-- quarto render 06_Introduction_to_SQL1.qmd -->
<!-- git commit 06-* -m "commit message" -->
<!-- git status -->
<!-- git push -->
<!-- cache the results -->
<!-- A function for automating the numbering and wording of the exercise questions -->
<!-- Use \x60 inside exercise questions for backticks -->
<!-- To run this, first download the latest Chicago crime data from -->
<!-- https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-Present/ijzp-q8t2 -->
<!-- and put the file in the current folder -->
<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>Some datasets are far too large for R to handle by itself. Structured Query Language (“SQL”) is a widely used international standard language for managing data stored in a relational databases management system. A relational database management system itself is an approach to managing data using a structure that can be contrasted against the ‘flat file’ approach we have been using thus far with R. Why use SQL? R doesn’t work very well with really huge datasets. A relational database management system offers a way of storing large amounts of information more efficiently and reducing the size of the dataset that we are working with. There are numerous relational database management systems such as Oracle, Microsoft Access, and MySQL. We are going to use <a href="https://www.sqlite.org/index.html">SQLite</a>, which is probably the most widely deployed database system. SQLite is in your phone, car, airplanes, thermostats, and numerous appliances. We are going to hook up SQLite to R so that R can handle large datasets.</p>
<p>These are some basic clauses in a SQL query that we will explore:</p>
<p>SELECT fields or functions of fields INTO results table FROM tables queried WHERE conditions for selecting a record GROUP BY list of fields to group ORDER BY list of fields to sort by</p>
<p>However, before being able to use SQL as a tool in R, it will first be necessary to install the <code>sqldf</code> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sqldf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="getting-the-data-into-proper-form" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Getting the data into proper form</h1>
<p>We will be working with Chicago crime data, which is accessible comma separated value (csv) format. Before we can even being learning SQL, we are going to have to do a fair bit of work to acquire the dataset, format it so that it is ready for SQLite, and then load it into the SQLite database.</p>
<p>Navigate to the Chicago open data website to get the <a href="https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2">data</a>. Click the “Export” button and select the “CSV” option, or directly download from <a href="https://data.cityofchicago.org/api/views/ijzp-q8t2/rows.csv?accessType=DOWNLOAD">here</a></p>
<p>The Chicago crime data is huge, more than 2.0 Gb. It contains over 8.3 million records on all crimes reported to the Chicago police department since 2001. R does not handle really large datasets well. By using SQL, you will learn how to more efficiently work with large datasets and learn a data language that is used absolutely everywhere.</p>
<p>Let’s use <code>scan()</code> to just peek at the first three rows of the file.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">scan</span>(<span class="at">what=</span><span class="st">""</span>,<span class="at">file=</span><span class="st">"Crimes_-_2001_to_present.csv"</span>,<span class="at">nlines=</span><span class="dv">5</span>,<span class="at">sep=</span><span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location"                                   
[2] "13311263,JG503434,07/29/2022 03:39:00 AM,023XX S TROY ST,1582,OFFENSE INVOLVING CHILDREN,CHILD PORNOGRAPHY,RESIDENCE,true,false,1033,010,25,30,17,,,2022,04/18/2024 03:40:59 PM,,,"                                                              
[3] "13053066,JG103252,01/03/2023 04:44:00 PM,039XX W WASHINGTON BLVD,2017,NARCOTICS,MANUFACTURE / DELIVER - CRACK,SIDEWALK,true,false,1122,011,28,26,18,,,2023,01/20/2024 03:41:12 PM,,,"                                                            
[4] "12131221,JD327000,08/10/2020 09:45:00 AM,015XX N DAMEN AVE,0326,ROBBERY,AGGRAVATED VEHICULAR HIJACKING,STREET,true,false,1424,014,1,24,03,1162795,1909900,2020,05/17/2025 03:40:52 PM,41.908417822,-87.67740693,\"(41.908417822, -87.67740693)\""
[5] "11227634,JB147599,08/26/2017 10:00:00 AM,001XX W RANDOLPH ST,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,HOTEL/MOTEL,false,false,0122,001,42,32,02,,,2017,02/11/2018 03:57:41 PM,,,"                                                                 </code></pre>
</div>
</div>
<p><code>scan()</code> is a very basic R function that reads in plain text files. We’ve told it to read in text (<code>what==""</code>), the name of the file, to only read in 5 lines (<code>nlines=5</code>), and to start a new row whenever it reaches a line feed character (<code>sep="\n"</code>). Using <code>scan()</code> without <code>nlines=5</code> would cause R to try to read in the whole dataset and that could take a lot of time and you might run out of memory.</p>
<p>You can see that the first row contains the column names. The second row contains the first reported crime in the file. You can see date and time, address, crime descriptions, longitude and latitude of the crime, and other information.</p>
<p>Let’s try to load this file into a SQLite database. There are two steps. First, using <code>dbConnect()</code> we need to tell R to make a connection to a new SQLite database that we will call <code>chicagocrime.db</code>. This will be a file in your working folder that SQLite will use to store the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a connection to the database</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>con <span class="ot">&lt;-</span> <span class="fu">dbConnect</span>(<span class="fu">SQLite</span>(), <span class="at">dbname=</span><span class="st">"chicagocrime.db"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then using <code>dbWriteTable()</code> we tell R to read in the csv file and store its contents in a new table in the database. We will call that new table <code>crime</code>. Make sure that your path is set to the correct folder where you want the database to be stored.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># write a table called "crime" into the SQLite database</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dbWriteTable</span>(con, </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>             <span class="st">"crime"</span>, <span class="co"># the new table in the database</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>             <span class="st">"Crimes_-_2001_to_present.csv"</span>,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">row.names=</span><span class="cn">FALSE</span>,</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">header=</span><span class="cn">TRUE</span>)     <span class="co"># first row has column names</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in connection_import_file(conn@ptr, name, value, sep, eol, skip): RS_sqlite_import: Crimes_-_2001_to_present.csv line 4 expected 22 columns of data but found 23</code></pre>
</div>
</div>
<p>Looks like there is a problem with the dataset. SQLite was expecting 22 columns, but row 4 had 23. Notice from when we ran <code>scan()</code> earlier, the fourth row has a <code>"(41.908417822, -87.67740693)"</code>. SQLite thinks that these two numbers belong in two different columns instead of a single <code>Location</code> column.</p>
<p>SQLite is very particular about the formatting of a file. It can easily read in a csv file, but this dataset has some commas in places that confuse SQLite. For example, there is a row in this file that looks like this:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "10000153,HY189345,03/18/2015 12:20:00 PM,091XX S UNIVERSITY AVE,0483,BATTERY,AGG PRO.EMP: OTHER DANG WEAPON,\"SCHOOL, PUBLIC, BUILDING\",true,false,0413,004,8,47,04B,1185475,1844606,2015,02/10/2018 03:50:01 PM,41.728740563,-87.596150779,\"(41.728740563, -87.596150779)\""</code></pre>
</div>
</div>
<p>You see that the location description for this crime is <code>"SCHOOL, PUBLIC, BUILDING"</code>. Those commas inside the quotes are going to cause SQLite problems. SQLite is going to think that <code>SCHOOL</code>, <code>PUBLIC</code>, and <code>BUILDING</code> are all separate columns rather than one columns describing the location.</p>
<p>To resolve this, we are going to change all the commas that separate the columns into something else besides commas, leaving the commas in elements like <code>"SCHOOL, PUBLIC, BUILDING"</code> alone. It does not matter what we use to separate the fields, but it should be an unusual character that would not appear anywhere else in the dataset. Popular choices in the vertical bar (<code>|</code>) and the semicolon (<code>;</code>). So let’s take a slight detour to find out how to convert a comma-separated file into a semicolon separated file.</p>
<p>You will know if you need to convert your file if, when you try to set up your SQL database, you receive an error message about an “extra column.”</p>
<p>We are going to use a <code>while</code> loop to read in 1,000,000 rows of the our data file at a time. R can handle 1,000,000 rows. With the 1,000,000 rows read in, we will use a regular expression to replace all the commas used for separating columns with semicolons. Then we will write out the resulting cleaned up rows into a new file. It is a big file so this code can take a few minutes to run to completion.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>infile  <span class="ot">&lt;-</span> <span class="fu">file</span>(<span class="st">"Crimes_-_2001_to_present.csv"</span>, <span class="st">'r'</span>)       <span class="co"># 'r' for 'read'</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>outfile <span class="ot">&lt;-</span> <span class="fu">file</span>(<span class="st">"Crimes_-_2001_to_present-clean.csv"</span>, <span class="st">'w'</span>) <span class="co"># 'w' for 'write'</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># fix the Row #1 with the columns names</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="fu">readLines</span>(infile, <span class="at">n=</span><span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>   <span class="fu">gsub</span>(<span class="st">","</span>, <span class="st">";"</span>, <span class="at">x=</span>_) <span class="sc">|&gt;</span> <span class="co"># separate with ;</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>   <span class="fu">gsub</span>(<span class="st">" "</span>, <span class="st">""</span>, <span class="at">x=</span>_)  <span class="sc">|&gt;</span> <span class="co"># SQL doesn't like field names with .,-,space</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>   <span class="fu">writeLines</span>(<span class="at">con=</span>outfile)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>cLines <span class="ot">&lt;-</span> <span class="dv">0</span> <span class="co"># just a counter for the number of lines read</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="co"># read in 1000000 lines. keep going if more than 0 lines read</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a><span class="cf">while</span> ((<span class="fu">length</span>(a <span class="ot">&lt;-</span> <span class="fu">readLines</span>(infile, <span class="at">n=</span><span class="dv">1000000</span>)) <span class="sc">&gt;</span> <span class="dv">0</span>))</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>   cLines <span class="ot">&lt;-</span> cLines <span class="sc">+</span> <span class="fu">length</span>(a) <span class="co"># increase the line counter</span></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>   cLines <span class="sc">|&gt;</span> <span class="fu">format</span>(<span class="at">big.mark=</span><span class="st">","</span>, <span class="at">scientific=</span><span class="cn">FALSE</span>) <span class="sc">|&gt;</span> <span class="fu">message</span>()</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>   <span class="co"># remove any semicolons if they are there</span></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>   a <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">";"</span>, <span class="st">""</span>, a)</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>   <span class="co"># use ?= to "lookahead" for paired quotes</span></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>   a <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">",(?=([^</span><span class="sc">\"</span><span class="st">]|</span><span class="sc">\"</span><span class="st">[^</span><span class="sc">\"</span><span class="st">]*</span><span class="sc">\"</span><span class="st">)*$)"</span>, <span class="st">";"</span>, a, <span class="at">perl=</span><span class="cn">TRUE</span>)</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>   <span class="co"># write the cleaned up data to storage</span></span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>   <span class="fu">writeLines</span>(a, <span class="at">con=</span>outfile)</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>1,000,000</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>2,000,000</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>3,000,000</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>4,000,000</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>5,000,000</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>6,000,000</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>7,000,000</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>8,000,000</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>8,377,991</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">close</span>(infile)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">close</span>(outfile)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, let’s take a look at the first five lines of the new file we just created.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">scan</span>(<span class="at">what=</span><span class="st">""</span>,<span class="at">file=</span><span class="st">"Crimes_-_2001_to_present-clean.csv"</span>,<span class="at">nlines=</span><span class="dv">5</span>,<span class="at">sep=</span><span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "ID;CaseNumber;Date;Block;IUCR;PrimaryType;Description;LocationDescription;Arrest;Domestic;Beat;District;Ward;CommunityArea;FBICode;XCoordinate;YCoordinate;Year;UpdatedOn;Latitude;Longitude;Location"                                           
[2] "13311263;JG503434;07/29/2022 03:39:00 AM;023XX S TROY ST;1582;OFFENSE INVOLVING CHILDREN;CHILD PORNOGRAPHY;RESIDENCE;true;false;1033;010;25;30;17;;;2022;04/18/2024 03:40:59 PM;;;"                                                              
[3] "13053066;JG103252;01/03/2023 04:44:00 PM;039XX W WASHINGTON BLVD;2017;NARCOTICS;MANUFACTURE / DELIVER - CRACK;SIDEWALK;true;false;1122;011;28;26;18;;;2023;01/20/2024 03:41:12 PM;;;"                                                            
[4] "12131221;JD327000;08/10/2020 09:45:00 AM;015XX N DAMEN AVE;0326;ROBBERY;AGGRAVATED VEHICULAR HIJACKING;STREET;true;false;1424;014;1;24;03;1162795;1909900;2020;05/17/2025 03:40:52 PM;41.908417822;-87.67740693;\"(41.908417822, -87.67740693)\""
[5] "11227634;JB147599;08/26/2017 10:00:00 AM;001XX W RANDOLPH ST;0281;CRIM SEXUAL ASSAULT;NON-AGGRAVATED;HOTEL/MOTEL;false;false;0122;001;42;32;02;;;2017;02/11/2018 03:57:41 PM;;;"                                                                 </code></pre>
</div>
</div>
<p>You now see that semicolons separate the columns rather than commas. That previous record that had the location description “SCHOOL, PUBLIC, BUILDING” now looks like this:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "10000153;HY189345;03/18/2015 12:20:00 PM;091XX S UNIVERSITY AVE;0483;BATTERY;AGG PRO.EMP: OTHER DANG WEAPON;\"SCHOOL, PUBLIC, BUILDING\";true;false;0413;004;8;47;04B;1185475;1844606;2015;02/10/2018 03:50:01 PM;41.728740563;-87.596150779;\"(41.728740563, -87.596150779)\""</code></pre>
</div>
</div>
<p>Note that the commas are still there inside the quotes. Now we will be able to tell SQLite to look for semicolons to separate the columns.</p>
</section>
<section id="setting-up-the-database" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Setting up the database</h1>
<p>Now that the csv file containing the data is ready, we can load it into SQLite.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># peek at the first few rows of the dataset</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"Crimes_-_2001_to_present-clean.csv"</span>,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">sep=</span><span class="st">";"</span>,<span class="at">nrows=</span><span class="dv">5</span>,<span class="at">header=</span><span class="cn">TRUE</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co"># ask SQLite what data type it plans to use to store each column (eg number, text)</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>variabletypes <span class="ot">&lt;-</span> <span class="fu">dbDataType</span>(con, a)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="co"># make sure these features are stored as TEXT</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>variabletypes[<span class="fu">c</span>(<span class="st">"IUCR"</span>,<span class="st">"FBICode"</span>,<span class="st">"Ward"</span>,<span class="st">"District"</span>,<span class="st">"CommunityArea"</span>)] <span class="ot">&lt;-</span> <span class="st">"TEXT"</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a><span class="co"># just in case you've already created a "crime" table, delete it</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="fu">dbExistsTable</span>(con, <span class="st">"crime"</span>)) <span class="fu">dbRemoveTable</span>(con, <span class="st">"crime"</span>)</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="co"># import the data file into the database</span></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a><span class="fu">dbWriteTable</span>(con, <span class="st">"crime"</span>,                         <span class="co"># create crime table   </span></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>             <span class="st">"Crimes_-_2001_to_present-clean.csv"</span>, <span class="co"># from our cleaned up file</span></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>             <span class="at">row.names=</span><span class="cn">FALSE</span>,</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>             <span class="at">header=</span><span class="cn">TRUE</span>,                          <span class="co"># first row has column names</span></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>             <span class="at">field.types=</span>variabletypes,            </span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>             <span class="at">sep=</span><span class="st">";"</span>)                              <span class="co"># columns separated with ;</span></span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a><span class="co"># does the table exist?</span></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a><span class="fu">dbListTables</span>(con)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "crime"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># a quick check to see if all the columns are there</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dbListFields</span>(con,<span class="st">"crime"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "ID"                  "CaseNumber"          "Date"               
 [4] "Block"               "IUCR"                "PrimaryType"        
 [7] "Description"         "LocationDescription" "Arrest"             
[10] "Domestic"            "Beat"                "District"           
[13] "Ward"                "CommunityArea"       "FBICode"            
[16] "XCoordinate"         "YCoordinate"         "Year"               
[19] "UpdatedOn"           "Latitude"            "Longitude"          
[22] "Location"           </code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># disconnect from the database to finalize</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dbDisconnect</span>(con)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You will know if the database has been successfully set up if you find a chicagocrime.db file that has about 2 Gb of data in it. If the file size is 0 or really small, then you may be looking in the wrong folder or the data cleaning and import did not finish.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># how many gigabytes?</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>(<span class="fu">file.size</span>(<span class="st">"chicagocrime.db"</span>)<span class="sc">/</span><span class="dv">10</span><span class="sc">^</span><span class="dv">9</span>) <span class="sc">|&gt;</span> </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>   <span class="fu">round</span>(<span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>   <span class="fu">format</span>(<span class="at">nsmall=</span><span class="dv">1</span>, <span class="at">scientific=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "1.9"</code></pre>
</div>
</div>
<p>Once you have successfully set up your database, there is no reason to run these lines of code again. You should never again need to turn commas into semicolons or run <code>dbWriteTable()</code>. Instead, every time you want to work with your database, you can simply need to reconnect to the database with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>con <span class="ot">&lt;-</span> <span class="fu">dbConnect</span>(<span class="fu">SQLite</span>(), <span class="at">dbname=</span><span class="st">"chicagocrime.db"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note that if you are using a cloud-based backup service like iCloud, OneDrive, or Google Drive, you might need to wait until your “db” file has completely synced before you can access your database. For this reason I typically put my SQLite databases in a folder that does not get backed up. If I accidentally delete it, then I just rerun the code to rebuild the database.</p>
</section>
<section id="sql-queries-select-where-from" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> SQL queries (<code>SELECT</code>, <code>WHERE</code>, <code>FROM</code>)</h1>
<p>You have now created a database chicagocrime.db containing a table called <code>crime</code> that contains those 8 million crime records.</p>
<p>Two important clauses with an SQL query are <code>SELECT</code> and <code>FROM</code>. Unlike R, SQL queries are not case-sensitive and column names are not case-sensitive. So if we were to type “SELECT” as “select” or “Description” as “dEsCrIpTiOn”, the SQL query would do the same thing. However, the tradition is to put SQL keywords in all uppercase to make it easier to distinguish them from table and column names.</p>
<p>The <code>SELECT</code> clause tells SQL which columns in particular you would like to see. The <code>FROM</code> clause simply tells SQL from which table it should pull the data. In this query, we are interested in only the <code>ID</code> and <code>Description</code> columns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con,</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>   <span class="st">"SELECT ID, Description</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="st">    FROM crime"</span>,</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="dv">10</span>) <span class="co"># just the first 10 rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         ID                    Description
1  13311263              CHILD PORNOGRAPHY
2  13053066  MANUFACTURE / DELIVER - CRACK
3  12131221 AGGRAVATED VEHICULAR HIJACKING
4  11227634                 NON-AGGRAVATED
5  13203321                     TO VEHICLE
6  13204489                      OVER $500
7  11695116                 UNLAWFUL ENTRY
8  12419690 SEXUAL EXPLOITATION OF A CHILD
9  12729745 ATTEMPT STRONG ARM - NO WEAPON
10 12835559                     AUTOMOBILE</code></pre>
</div>
</div>
<p><code>dbGetQuery()</code> pulls the selected rows (first 10) from the selected columns (<code>ID</code> and <code>Description</code>). Sometimes it is preferable to get large datasets in smaller chunks using <code>dbSendQuery()</code> and <code>dbFetch()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">dbSendQuery</span>(con, <span class="st">"</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="st">  SELECT ID,Description</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="st">  FROM crime"</span>)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="co"># pull the first 10 lines</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="fu">dbFetch</span>(res, <span class="at">n =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         ID                    Description
1  13311263              CHILD PORNOGRAPHY
2  13053066  MANUFACTURE / DELIVER - CRACK
3  12131221 AGGRAVATED VEHICULAR HIJACKING
4  11227634                 NON-AGGRAVATED
5  13203321                     TO VEHICLE
6  13204489                      OVER $500
7  11695116                 UNLAWFUL ENTRY
8  12419690 SEXUAL EXPLOITATION OF A CHILD
9  12729745 ATTEMPT STRONG ARM - NO WEAPON
10 12835559                     AUTOMOBILE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># pull the next 10 lines</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dbFetch</span>(res, <span class="at">n =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         ID                                                  Description
1  13003649                                               FORCIBLE ENTRY
2  13061203                                      DOMESTIC BATTERY SIMPLE
3  13256787                                      DOMESTIC BATTERY SIMPLE
4  13116982                                            RECKLESS HOMICIDE
5  13364090 "PROTECTED EMPLOYEE - HANDS, FISTS, FEET, NO / MINOR INJURY"
6  13376308    "AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MINOR INJURY"
7     27382                                          FIRST DEGREE MURDER
8     27547                                          FIRST DEGREE MURDER
9   6255892                                              ARMED - HANDGUN
10  6272641                                       STRONG ARM - NO WEAPON</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># when finished, clear the rest of the results</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dbClearResult</span>(res)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>dbClearResult(res)</code> tells SQLite that we are all done with this query. We have displayed the first 20 rows. SQLite is standing by with another 8 million rows to show us, but <code>dbClearResult(res)</code> tells SQLite that we are no longer interested in this query and it can clear out whatever it has stored for us.</p>
<p>In the previous SQL query we just asked for <code>ID</code> and <code>Description</code>. Typing out all of the column names would be tiresome, so SQL lets you use a <code>*</code> to select all the columns. If we want to look at the first 10 rows but all of the columns, we would use this query:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="st">  SELECT *</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="st">  FROM crime"</span>,</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Column `XCoordinate`: mixed type, first seen values of type string,
coercing other values of type integer</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Column `YCoordinate`: mixed type, first seen values of type string,
coercing other values of type integer</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Column `Latitude`: mixed type, first seen values of type string,
coercing other values of type real</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Column `Longitude`: mixed type, first seen values of type string,
coercing other values of type real</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>        ID CaseNumber                   Date                   Block IUCR
1 13311263   JG503434 07/29/2022 03:39:00 AM         023XX S TROY ST 1582
2 13053066   JG103252 01/03/2023 04:44:00 PM 039XX W WASHINGTON BLVD 2017
3 12131221   JD327000 08/10/2020 09:45:00 AM       015XX N DAMEN AVE 0326
                 PrimaryType                    Description LocationDescription
1 OFFENSE INVOLVING CHILDREN              CHILD PORNOGRAPHY           RESIDENCE
2                  NARCOTICS  MANUFACTURE / DELIVER - CRACK            SIDEWALK
3                    ROBBERY AGGRAVATED VEHICULAR HIJACKING              STREET
  Arrest Domestic Beat District Ward CommunityArea FBICode XCoordinate
1   true    false 1033      010   25            30      17            
2   true    false 1122      011   28            26      18            
3   true    false 1424      014    1            24      03     1162795
  YCoordinate Year              UpdatedOn     Latitude    Longitude
1             2022 04/18/2024 03:40:59 PM                          
2             2023 01/20/2024 03:41:12 PM                          
3     1909900 2020 05/17/2025 03:40:52 PM 41.908417822 -87.67740693
                          Location
1                               \r
2                               \r
3 "(41.908417822, -87.67740693)"\r</code></pre>
</div>
</div>
<p>In addition to showing us the first three rows in their entirety, we get some warnings here regarding the coordinates of the crime that we will have to deal with later. The issue involves how SQL stores missing values.</p>
<p>Just as <code>SELECT</code> filters the columns, the <code>WHERE</code> clause filters the rows. Note the use of <code>AND</code> and <code>OR</code> in the <code>WHERE</code> clause. Here we select three columns: <code>ID</code>, <code>Description</code>, and <code>LocationDescription</code>. Also, we want only rows where</p>
<ul>
<li>the value in the <code>Beat</code> column is “611”</li>
<li>the value in the <code>Arrest</code> column is “true”</li>
<li>the value in the <code>ICUR</code> column is either “0486” or “0498”</li>
</ul>
<p>Importantly, note the use of single (not double) quotation marks in the <code>WHERE</code> line. The reason is that if we used double quotes, then R will think that the double quote signals the end of the query.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="st">    SELECT ID, Description, LocationDescription</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="st">    FROM crime</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="st">    WHERE ((Beat=611) AND </span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="st">          (Arrest='true')) AND</span></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a><span class="st">          ((IUCR='0486') OR (IUCR='0498'))"</span>)</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a><span class="co"># show the first few rows of the results</span></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(a, <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        ID             Description LocationDescription
1 13248950 DOMESTIC BATTERY SIMPLE           APARTMENT
2 13254239 DOMESTIC BATTERY SIMPLE            SIDEWALK
3 13287327 DOMESTIC BATTERY SIMPLE           APARTMENT</code></pre>
</div>
</div>
<p>SQL does not like column names with special characters. Only letters (first character <em>must</em> be a letter), numbers, and underscores (<code>_</code>). Column names also cannot be a SQl keyword, like SELECT or WHERE. If you happen to have a table with any special characters, like periods, hyphens, or spaces, you can “protect” the column name in square brackets. For example, <code>SELECT [incident id], [text-description], [location.description], [where]</code>.</p>
<section id="exercises" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="exercises"><span class="header-section-number">4.1</span> Exercises</h2>
<ol type="1">
<li><p>Select records from Beat 234</p></li>
<li><p>Select Beat, District, Ward, and Community Area for all “ASSAULT”s</p></li>
<li><p>Select records on assaults from Beat 234</p></li>
<li><p>Make a table of the number of assaults (IUCR 0560) by Ward</p></li>
</ol>
</section>
</section>
<section id="group_by-and-aggregation-functions" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> <code>GROUP_BY</code> and aggregation functions</h1>
<p>We have already covered SQL clauses <code>SELECT</code>, <code>WHERE</code>, and <code>FROM</code>. The SQL function <code>COUNT(*)</code> and <code>GROUP BY</code> are also very useful. For example, the following query counts how many assaults (IUCR 0560) occurred by ward. <code>COUNT()</code> is a SQL “aggregate” function, a function that performs a calculation on a group of values and returns a single number. Other SQL aggregate functions include <code>AVG()</code>, <code>MIN()</code>, <code>MAX()</code>, and <code>SUM()</code>. This query will group all the records by <code>Ward</code> and then apply the aggregate function <code>COUNT()</code> and report that value in a column called <code>crimecount</code>. <code>AS</code> allows us to give clear column names in the results. Without the <code>AS crimecount</code> column of counts would be called <code>COUNT(*)</code>, which has several characters about which SQL will complain.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="st">   SELECT COUNT(*) AS crimecount,</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="st">          Ward</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="st">   FROM crime</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a><span class="st">   WHERE IUCR='0560'</span></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a><span class="st">   GROUP BY Ward"</span>)</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   crimecount Ward
1       29470     
2        5294    1
3        8084   10
4        5069   11
5        4269   12
6        3845   13
7        4248   14
8        9540   15
9       11296   16
10      13640   17
11       6116   18
12       3539   19
13      10769    2
14      13080   20
15      11463   21
16       4336   22
17       4078   23
18      12580   24
19       5298   25
20       6472   26
21      11677   27
22      15108   28
23       8886   29
24      11755    3
25       4443   30
26       4497   31
27       3240   32
28       2999   33
29      11092   34
30       4457   35
31       3727   36
32       9332   37
33       3418   38
34       2929   39
35       8537    4
36       3728   40
37       3227   41
38       9674   42
39       2185   43
40       3163   44
41       3609   45
42       5186   46
43       2689   47
44       3954   48
45       5184   49
46       9245    5
47       3320   50
48      12902    6
49      11773    7
50      11697    8
51      11710    9</code></pre>
</div>
</div>
<p>The <code>GROUP BY</code> clause is critical. If you forget it then the result is not well defined. That is, different implementations of SQL may produce different results. The rule you should remember is that “every non-aggregated column in the <code>SELECT</code> clause should appear in the <code>GROUP BY</code> clause.” Here <code>Ward</code> is not part of the aggregate function <code>COUNT()</code> so it must appear in the <code>GROUP BY</code> clause.</p>
<section id="exercises-1" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="exercises-1"><span class="header-section-number">5.1</span> Exercises</h2>
<ol start="5" type="1">
<li><p>Count the number of crimes by <code>PrimaryType</code></p></li>
<li><p>Count the number of crimes resulting in arrest</p></li>
<li><p>Count the number of crimes by <code>LocationDescription</code>. <code>LocationDescription</code> is the variable that tells us where (e.g., a parking lot, a barbershop, a fire station, a CTA train, or a motel) a crime occurred</p></li>
</ol>
</section>
</section>
<section id="order_by-and-update" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> <code>ORDER_BY</code> and <code>UPDATE</code></h1>
<p><code>MAX</code>, <code>MIN</code>, <code>SUM</code>, <code>AVG</code> are common (and useful) aggregating functions. The <code>ORDER BY</code> clause sorts the results for us. It is the SQL version of the <code>sort()</code> or <code>arrange()</code> functions. Here is an illustration that gives the range of beat numbers in each policing district.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="st">   SELECT MIN(Beat) AS min_beat,</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="st">          MAX(Beat) AS max_beat,</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="st">          District</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a><span class="st">   FROM crime</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a><span class="st">   GROUP BY District</span></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a><span class="st">   ORDER BY District"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   min_beat max_beat District
1       124     2535         
2       111     2535      001
3       131     2232      002
4       133     2222      003
5       324     2514      004
6       333     2233      005
7       123     2424      006
8       233     2431      007
9       333     2411      008
10      131     2522      009
11      133     2534      010
12      624     2535      011
13      111     2525      012
14      411     2535      014
15      726     2533      015
16      811     2521      016
17      734     2523      017
18      111     2533      018
19      112     2533      019
20      112     2433      020
21     2112     2112      021
22      214     2234      022
23      123     2433      024
24      725     2535      025
25      124     2535      031
26     1614     1614       16</code></pre>
</div>
</div>
<p>Remember that the <code>GROUP BY</code> clause should include every element of the <code>SELECT</code> clause that is not involved with an aggregate function. We have <code>MIN()</code> and <code>MAX()</code> operating on <code>Beat</code>, but <code>District</code> is on its own and should be placed in the <code>GROUP BY</code> clause.</p>
<p>Let’s look at our <code>Latitude</code> and <code>Longitude</code> columns, which will be extremely useful for mapping data points. The following query will give unexpected results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="st">   SELECT MIN(Latitude)  AS min_lat,</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="st">          MAX(Latitude)  AS max_lat,</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="st">          MIN(Longitude) AS min_lon,</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a><span class="st">          MAX(Longitude) AS max_lon,</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a><span class="st">          District</span></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a><span class="st">   FROM crime</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a><span class="st">   GROUP BY District</span></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a><span class="st">   ORDER BY District"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Column `max_lat`: mixed type, first seen values of type real, coercing
other values of type string</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Column `max_lon`: mixed type, first seen values of type real, coercing
other values of type string</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>    min_lat  max_lat   min_lon   max_lon District
1  41.69991 42.00030 -87.87742 -87.59533         
2  36.61945  0.00000 -91.68657   0.00000      001
3  36.61945  0.00000 -91.68657   0.00000      002
4  36.61945  0.00000 -91.68657   0.00000      003
5  36.61945  0.00000 -91.68657   0.00000      004
6  36.61945  0.00000 -91.68657   0.00000      005
7  36.61945  0.00000 -91.68657   0.00000      006
8  36.61945  0.00000 -91.68657   0.00000      007
9  36.61945  0.00000 -91.68657   0.00000      008
10 36.61945  0.00000 -91.68657   0.00000      009
11 36.61945  0.00000 -91.68657   0.00000      010
12 36.61945  0.00000 -91.68657   0.00000      011
13 36.61945  0.00000 -91.68657   0.00000      012
14 36.61945  0.00000 -91.68657   0.00000      014
15 36.61945  0.00000 -91.68657   0.00000      015
16 36.61945  0.00000 -91.68657   0.00000      016
17 36.61945  0.00000 -91.68657   0.00000      017
18 36.61945  0.00000 -91.68657   0.00000      018
19 41.80933  0.00000 -87.76791   0.00000      019
20 41.79145  0.00000 -87.76303   0.00000      020
21 41.83790 41.83790 -87.62192 -87.62192      021
22 36.61945  0.00000 -91.68657   0.00000      022
23 36.61945  0.00000 -91.68657   0.00000      024
24 36.61945  0.00000 -91.68657   0.00000      025
25 41.64619 42.01939 -87.93973 -87.53528      031
26 41.98531 41.98552 -87.83047 -87.82900       16</code></pre>
</div>
</div>
<p>We get some strange results here. <code>max_lat</code> equal to 0.0 is on the equator! It is doubtful that Chicago reported any equatorial crimes. The problem is that we have some blank values in <code>Longitude</code> and <code>Latitude</code>. Here are some of them.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, <span class="st">"SELECT * FROM crime WHERE Longitude=''"</span>, <span class="at">n=</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        ID CaseNumber                   Date                   Block IUCR
1 13311263   JG503434 07/29/2022 03:39:00 AM         023XX S TROY ST 1582
2 13053066   JG103252 01/03/2023 04:44:00 PM 039XX W WASHINGTON BLVD 2017
3 11227634   JB147599 08/26/2017 10:00:00 AM     001XX W RANDOLPH ST 0281
                 PrimaryType                   Description LocationDescription
1 OFFENSE INVOLVING CHILDREN             CHILD PORNOGRAPHY           RESIDENCE
2                  NARCOTICS MANUFACTURE / DELIVER - CRACK            SIDEWALK
3        CRIM SEXUAL ASSAULT                NON-AGGRAVATED         HOTEL/MOTEL
  Arrest Domestic Beat District Ward CommunityArea FBICode XCoordinate
1   true    false 1033      010   25            30      17            
2   true    false 1122      011   28            26      18            
3  false    false  122      001   42            32      02            
  YCoordinate Year              UpdatedOn Latitude Longitude Location
1             2022 04/18/2024 03:40:59 PM                          \r
2             2023 01/20/2024 03:41:12 PM                          \r
3             2017 02/11/2018 03:57:41 PM                          \r</code></pre>
</div>
</div>
<p>Note the <code>Latitude</code> and the <code>Longitude</code> columns are blank. And have a look at these</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, <span class="st">"SELECT * FROM crime where Latitude&lt;36.61946"</span>, <span class="at">n=</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    ID CaseNumber                   Date               Block IUCR PrimaryType
1 1482   HH367441 05/13/2002 05:00:00 AM 061XX S ARTESIAN ST 0110    HOMICIDE
2  838    G311269 05/29/2001 11:35:00 PM   059XX S MORGAN AV 0110    HOMICIDE
3  637    G005960 01/06/2001 10:35:00 AM  014XX N HARDING ST 0110    HOMICIDE
          Description LocationDescription Arrest Domestic Beat District Ward
1 FIRST DEGREE MURDER               HOUSE   true    false  825      008     
2 FIRST DEGREE MURDER            DUMPSTER   true    false  712      007     
3 FIRST DEGREE MURDER              STREET   true    false 2535      025     
  CommunityArea FBICode XCoordinate YCoordinate Year              UpdatedOn
1                   01A           0           0 2002 01/28/2024 03:40:59 PM
2                   01A           0           0 2001 01/28/2024 03:40:59 PM
3                   01A           0           0 2001 01/28/2024 03:40:59 PM
  Latitude Longitude                          Location
1 36.61945 -91.68657 "(36.619446395, -91.686565684)"\r
2 36.61945 -91.68657 "(36.619446395, -91.686565684)"\r
3 36.61945 -91.68657 "(36.619446395, -91.686565684)"\r</code></pre>
</div>
</div>
<p>The point (-91.68657, 36.61945) lands in Brandsville, Missouri, also highly unlikely locations for Chicago crime</p>
<p>We can tell SQLite to make the empty or missing values <code>NULL</code>, a more proper way to encode that these rows have missing coordinates. The <code>UPDATE</code> clause edits our table. R will read in <code>NULL</code> values as <code>NA</code>. After we do the update, we can rerun the <code>MIN()</code>, <code>MAX()</code> query. We can also assign <code>NULL</code> to latitudes and longitudes that are very close to 0.</p>
<p>Note that we use <code>dbSendQuery()</code> when updating since we are not asking for any rows of data to come back to us.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">dbSendQuery</span>(con, <span class="st">"</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="st">   UPDATE crime SET Latitude=NULL</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="st">   WHERE (Latitude='') OR (ABS(Latitude-0.0) &lt; 0.01) OR (Latitude &lt; 36.7)"</span>)</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a><span class="fu">dbClearResult</span>(res)</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">dbSendQuery</span>(con, <span class="st">"</span></span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a><span class="st">   UPDATE crime SET Longitude=NULL</span></span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a><span class="st">   WHERE (Longitude='') OR (ABS(Longitude-0.0) &lt; 0.01) OR (Longitude &lt; -91.6)"</span>)</span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a><span class="fu">dbClearResult</span>(res)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s rerun that query and check that we get more sensible results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="st">   SELECT MIN(Latitude)  AS min_lat,</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="st">          MAX(Latitude)  AS max_lat,</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a><span class="st">          MIN(Longitude) AS min_lon,</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a><span class="st">          MAX(Longitude) AS max_lon,</span></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a><span class="st">          District</span></span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a><span class="st">   FROM crime</span></span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a><span class="st">   GROUP BY District</span></span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a><span class="st">   ORDER BY District"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    min_lat  max_lat   min_lon   max_lon District
1  41.69991 42.00030 -87.87742 -87.59533         
2  41.72827 41.98740 -87.84349 -87.54925      001
3  41.73298 41.97608 -87.70277 -87.56954      002
4  41.71424 41.79946 -87.73941 -87.55261      003
5  41.64467 41.79220 -87.72436 -87.52453      004
6  41.64459 41.88693 -87.73145 -87.54348      005
7  41.69249 42.01876 -87.77138 -87.55810      006
8  41.66806 42.01369 -87.68723 -87.57906      007
9  41.73453 42.01765 -87.80161 -87.55239      008
10 41.77015 41.97645 -87.71397 -87.60282      009
11 41.68357 41.94304 -87.74364 -87.61895      010
12 41.77163 41.90624 -87.76332 -87.62328      011
13 41.68544 41.96539 -87.76321 -87.60502      012
14 41.77688 42.01938 -87.80222 -87.65657      014
15 41.76641 41.94234 -87.77535 -87.63087      015
16 41.78464 42.01938 -87.93457 -87.58256      016
17 41.77950 42.01390 -87.75780 -87.66131      017
18 41.85952 41.96879 -87.76313 -87.60136      018
19 41.80933 41.98397 -87.76791 -87.58775      019
20 41.79145 42.00458 -87.76303 -87.62992      020
21 41.83790 41.83790 -87.62192 -87.62192      021
22 41.67709 41.85572 -87.74328 -87.58965      022
23 41.75988 42.02291 -87.79757 -87.62545      024
24 41.83930 41.94586 -87.81648 -87.64093      025
25 41.64619 42.01939 -87.93973 -87.53528      031
26 41.98531 41.98552 -87.83047 -87.82900       16</code></pre>
</div>
</div>
<p>Now we have results that are more in line with where Chicago actually is. Make it a habit to do some checks of your data before doing too much analysis.</p>
<p>And what city does the following plot have the shape of? Let’s plot the location of these crimes. Plotting all 8 million would be overkill, so let’s take a random sample of 10,000 crimes. Here is a SQL query that will do that. It uses some tricks we will learn more about later including the use of <code>IN</code>, the use of subqueries (a query within a query), and <code>LIMIT</code>. Does the shape of the plot look right?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="st">   SELECT Longitude, Latitude </span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="st">   FROM crime </span></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a><span class="st">   WHERE id IN (SELECT id </span></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a><span class="st">                FROM crime </span></span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a><span class="st">                ORDER BY RANDOM() </span></span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a><span class="st">                LIMIT 10000)"</span>)</span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Latitude<span class="sc">~</span>Longitude, <span class="at">data=</span>a, </span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch=</span><span class="st">"."</span>, </span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Longitude"</span>, <span class="at">ylab=</span><span class="st">"Latitude"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06_Introduction_to_SQL1_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="exercises-2" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="exercises-2"><span class="header-section-number">6.1</span> Exercises</h2>
<ol start="8" type="1">
<li><p>Plot the longitude and latitude of all “ASSAULT”s for Ward 22</p></li>
<li><p>What is the most common (Long,Lat) for assaults in Ward 22? Add the point to your plot using the <code>points()</code> function. <code>points()</code> simply draws a point (or sequence of points) at the specified coordinates</p></li>
</ol>
</section>
</section>
<section id="solutions-to-the-exercises" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Solutions to the exercises</h1>
<ol type="1">
<li>Select records from Beat 234</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="st">   SELECT *</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a><span class="st">   FROM crime</span></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a><span class="st">   WHERE Beat=234"</span>,</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>   <span class="at">n=</span><span class="dv">5</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Column `XCoordinate`: mixed type, first seen values of type integer,
coercing other values of type string</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Column `YCoordinate`: mixed type, first seen values of type integer,
coercing other values of type string</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>        ID CaseNumber                   Date                  Block IUCR
1 13208531   JG408244 08/01/2023 12:00:00 PM 054XX S EAST VIEW PARK 0820
2 13203370   JG415497 09/07/2023 07:30:00 PM    051XX S KENWOOD AVE 1310
3 13207450   JG420345 09/07/2023 01:54:00 PM 054XX S BLACKSTONE AVE 0890
4 13203210   JG415469 09/07/2023 06:30:00 PM 052XX S BLACKSTONE AVE 0890
5 13206379   JG418537 01/01/2007 04:40:00 PM       053XX S SHORE DR 1153
         PrimaryType                         Description LocationDescription
1              THEFT                      $500 AND UNDER              STREET
2    CRIMINAL DAMAGE                         TO PROPERTY           APARTMENT
3              THEFT                       FROM BUILDING           APARTMENT
4              THEFT                       FROM BUILDING           APARTMENT
5 DECEPTIVE PRACTICE FINANCIAL IDENTITY THEFT OVER $ 300                    
  Arrest Domestic Beat District Ward CommunityArea FBICode XCoordinate
1  false    false  234      002    5            41      06     1188934
2  false     true  234      002    4            41      14     1185980
3  false    false  234      002    5            41      06     1186841
4  false    false  234      002    4            41      06     1186800
5  false    false  234      002    5            41      11           0
  YCoordinate Year              UpdatedOn Latitude Longitude
1     1869643 2023 09/14/2023 03:41:59 PM 41.79736 -87.58268
2     1871242 2023 09/15/2023 03:42:23 PM 41.80182 -87.59346
3     1869253 2023 09/15/2023 03:42:23 PM 41.79634 -87.59037
4     1870814 2023 09/15/2023 03:42:23 PM 41.80063 -87.59047
5           0 2007 09/16/2023 03:42:58 PM       NA        NA
                           Location
1  "(41.79736226, -87.582679493)"\r
2 "(41.801820311, -87.593461583)"\r
3 "(41.796341968, -87.590367054)"\r
4  "(41.80062644, -87.590467932)"\r
5                                \r</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Select Beat, District, Ward, and Community Area for all “ASSAULT”s</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="st">   SELECT Beat, District, Ward, CommunityArea, PrimaryType</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a><span class="st">   FROM crime</span></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a><span class="st">   WHERE PrimaryType='ASSAULT'"</span>,</span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>   <span class="at">n=</span><span class="dv">5</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Beat District Ward CommunityArea PrimaryType
1 2515      025   36            19     ASSAULT
2 1713      017   33            14     ASSAULT
3  631      006    6            44     ASSAULT
4  322      003    6            69     ASSAULT
5 1533      015   29            25     ASSAULT</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>Select records on assaults from Beat 234</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="st">   SELECT *</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a><span class="st">   FROM crime</span></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a><span class="st">   WHERE (Beat=234) AND (PrimaryType='ASSAULT')"</span>,</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>   <span class="at">n=</span><span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        ID CaseNumber                   Date                  Block IUCR
1 13276965   JG502615 11/10/2023 09:00:00 AM 015XX E HYDE PARK BLVD 0560
2 13207370   JG420456 09/10/2023 05:19:00 PM 053XX S HYDE PARK BLVD 0560
3 13210166   JG421339 09/12/2023 01:30:00 PM        015XX E 53RD ST 0560
4 13273166   JG499223 11/10/2023 04:39:00 PM        015XX E 53RD ST 0560
5 13225905   JG442370 09/11/2023 04:15:00 PM    054XX S CORNELL AVE 0560
  PrimaryType Description LocationDescription Arrest Domestic Beat District
1     ASSAULT      SIMPLE       ATHLETIC CLUB  false    false  234      002
2     ASSAULT      SIMPLE           APARTMENT  false    false  234      002
3     ASSAULT      SIMPLE              STREET  false    false  234      002
4     ASSAULT      SIMPLE  SMALL RETAIL STORE  false    false  234      002
5     ASSAULT      SIMPLE           APARTMENT  false    false  234      002
  Ward CommunityArea FBICode XCoordinate YCoordinate Year
1    4            41     08A     1187293     1871488 2023
2    5            41     08A     1188556     1870311 2023
3    4            41     08A     1187634     1870434 2023
4    5            41     08A     1187748     1870436 2023
5    5            41     08A     1188178     1869513 2023
               UpdatedOn Latitude Longitude                          Location
1 11/18/2023 03:40:25 PM 41.80246 -87.58864 "(41.802464238, -87.588638554)"\r
2 09/18/2023 03:42:32 PM 41.79920 -87.58404 "(41.799204348, -87.584044296)"\r
3 09/20/2023 03:42:29 PM 41.79956 -87.58742 "(41.799563873, -87.587421525)"\r
4 11/18/2023 03:40:25 PM 41.79957 -87.58700   "(41.799566646, -87.5870034)"\r
5 09/30/2023 03:41:20 PM 41.79702 -87.58546 "(41.797023613, -87.585455951)"\r</code></pre>
</div>
</div>
<ol start="4" type="1">
<li>Make a table of the number of assaults (IUCR 0560) by Ward</li>
</ol>
<p>We could select all the IUCR codes and ward with SQL and then filter and tabulate the data in R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># system.time() reports how long it takes to run the SQL query</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="co">#   How long if we retrieve data from SQL and tabulate in R?</span></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a><span class="fu">system.time</span>(</span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>   data <span class="ot">&lt;-</span> <span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a><span class="st">                    SELECT IUCR,Ward</span></span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a><span class="st">                    FROM crime"</span>)</span>
<span id="cb69-8"><a href="#cb69-8" aria-hidden="true" tabindex="-1"></a>   data <span class="sc">|&gt;</span></span>
<span id="cb69-9"><a href="#cb69-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(IUCR<span class="sc">==</span><span class="st">"0560"</span>) <span class="sc">|&gt;</span></span>
<span id="cb69-10"><a href="#cb69-10" aria-hidden="true" tabindex="-1"></a>      <span class="fu">count</span>(Ward)</span>
<span id="cb69-11"><a href="#cb69-11" aria-hidden="true" tabindex="-1"></a>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   user  system elapsed 
   3.08    1.96    5.14 </code></pre>
</div>
</div>
<p>Or we could make SQL do all the work selecting and tabulating.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co">#   How long if we make SQL do all the work?</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="fu">system.time</span>(</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>   a <span class="ot">&lt;-</span> <span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a><span class="st">      SELECT COUNT(*) AS crimecount,</span></span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a><span class="st">             Ward</span></span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a><span class="st">      FROM crime</span></span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a><span class="st">      WHERE IUCR='0560'</span></span>
<span id="cb71-9"><a href="#cb71-9" aria-hidden="true" tabindex="-1"></a><span class="st">      GROUP BY Ward"</span>)</span>
<span id="cb71-10"><a href="#cb71-10" aria-hidden="true" tabindex="-1"></a>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   user  system elapsed 
   0.57    1.67    2.22 </code></pre>
</div>
</div>
<p>Generally, SQL will be much faster for general selecting, filtering, tabulating, and linking data.</p>
<ol start="5" type="1">
<li>Count the number of crimes by <code>PrimaryType</code></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a><span class="st">   SELECT COUNT(*) AS crimecount, </span></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a><span class="st">          PrimaryType</span></span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a><span class="st">   FROM crime</span></span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a><span class="st">   GROUP BY PrimaryType"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   crimecount                       PrimaryType
1       14354                             ARSON
2      560071                           ASSAULT
3     1526524                           BATTERY
4      443249                          BURGLARY
5        1609 CONCEALED CARRY LICENSE VIOLATION
6       27303               CRIM SEXUAL ASSAULT
7      952792                   CRIMINAL DAMAGE
8       11111           CRIMINAL SEXUAL ASSAULT
9      225607                 CRIMINAL TRESPASS
10     384905                DECEPTIVE PRACTICE
11          1                 DOMESTIC VIOLENCE
12      14660                          GAMBLING
13      13883                          HOMICIDE
14        136                 HUMAN TRAFFICKING
15      20050  INTERFERENCE WITH PUBLIC OFFICER
16       5067                      INTIMIDATION
17       7478                        KIDNAPPING
18      15348              LIQUOR LAW VIOLATION
19     427418               MOTOR VEHICLE THEFT
20     762440                         NARCOTICS
21         38                    NON - CRIMINAL
22        190                      NON-CRIMINAL
23          9  NON-CRIMINAL (SUBJECT SPECIFIED)
24        942                         OBSCENITY
25      60129        OFFENSE INVOLVING CHILDREN
26        162          OTHER NARCOTIC VIOLATION
27     522174                     OTHER OFFENSE
28      70363                      PROSTITUTION
29        215                  PUBLIC INDECENCY
30      54573            PUBLIC PEACE VIOLATION
31         24                         RITUALISM
32     313479                           ROBBERY
33      33970                       SEX OFFENSE
34       6032                          STALKING
35    1777761                             THEFT
36     123924                 WEAPONS VIOLATION</code></pre>
</div>
</div>
<ol start="6" type="1">
<li>Count the number of crimes resulting in arrest</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="st">   SELECT COUNT(*) AS crimecount, PrimaryType</span></span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a><span class="st">   FROM crime</span></span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a><span class="st">   WHERE Arrest='true'</span></span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a><span class="st">   GROUP BY PrimaryType"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   crimecount                       PrimaryType
1        1769                             ARSON
2      113606                           ASSAULT
3      330925                           BATTERY
4       25340                          BURGLARY
5        1554 CONCEALED CARRY LICENSE VIOLATION
6        4365               CRIM SEXUAL ASSAULT
7       62027                   CRIMINAL DAMAGE
8         811           CRIMINAL SEXUAL ASSAULT
9      153567                 CRIMINAL TRESPASS
10      47726                DECEPTIVE PRACTICE
11          1                 DOMESTIC VIOLENCE
12      14554                          GAMBLING
13       6659                          HOMICIDE
14         13                 HUMAN TRAFFICKING
15      18365  INTERFERENCE WITH PUBLIC OFFICER
16        731                      INTIMIDATION
17        798                        KIDNAPPING
18      15199              LIQUOR LAW VIOLATION
19      32501               MOTOR VEHICLE THEFT
20     757507                         NARCOTICS
21          6                    NON - CRIMINAL
22         18                      NON-CRIMINAL
23          3  NON-CRIMINAL (SUBJECT SPECIFIED)
24        699                         OBSCENITY
25      11627        OFFENSE INVOLVING CHILDREN
26        108          OTHER NARCOTIC VIOLATION
27      92239                     OTHER OFFENSE
28      70052                      PROSTITUTION
29        211                  PUBLIC INDECENCY
30      34078            PUBLIC PEACE VIOLATION
31          3                         RITUALISM
32      28982                           ROBBERY
33       8656                       SEX OFFENSE
34        730                          STALKING
35     192818                             THEFT
36      89935                 WEAPONS VIOLATION</code></pre>
</div>
</div>
<p>Or, if we were not interested in differentiating based on the <code>PrimaryType</code>, we could simply do the following:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="st">   SELECT COUNT(*) AS crimecount</span></span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a><span class="st">   FROM crime</span></span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a><span class="st">   WHERE Arrest='true'"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  crimecount
1    2118183</code></pre>
</div>
</div>
<ol start="7" type="1">
<li>Count the number of crimes by <code>LocationDescription</code></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a><span class="st">   SELECT COUNT(*) AS crimecount, LocationDescription</span></span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a><span class="st">   FROM crime</span></span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a><span class="st">   GROUP BY LocationDescription</span></span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a><span class="st">   ORDER BY crimecount DESC"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    crimecount                                     LocationDescription
1      2188634                                                  STREET
2      1378068                                               RESIDENCE
3       992559                                               APARTMENT
4       759893                                                SIDEWALK
5       269956                                                   OTHER
6       202933                          PARKING LOT/GARAGE(NON.RESID.)
7       186576                                                   ALLEY
8       167776                                      SMALL RETAIL STORE
9       146370                              "SCHOOL, PUBLIC, BUILDING"
10      140579                                              RESTAURANT
11      135280                                        RESIDENCE-GARAGE
12      132667                                  VEHICLE NON-COMMERCIAL
13      124167                                 RESIDENCE PORCH/HALLWAY
14      110654                                        DEPARTMENT STORE
15      104657                                      GROCERY FOOD STORE
16       93505                                             GAS STATION
17       75140                           RESIDENTIAL YARD (FRONT/BACK)
18       68975                            COMMERCIAL / BUSINESS OFFICE
19       63192                                           PARK PROPERTY
20       56098                                 CHA PARKING LOT/GROUNDS
21       46948                                           BAR OR TAVERN
22       44351                  PARKING LOT / GARAGE (NON RESIDENTIAL)
23       41231                                            CTA PLATFORM
24       40395                                           CHA APARTMENT
25       39543                                              DRUG STORE
26       34321                                               CTA TRAIN
27       33028                                                    BANK
28       30249                               "SCHOOL, PUBLIC, GROUNDS"
29       29723                                             HOTEL/MOTEL
30       27614                                       CONVENIENCE STORE
31       27368                                                 CTA BUS
32       25021                          CHA HALLWAY/STAIRWELL/ELEVATOR
33       24679                                         VACANT LOT/LAND
34       24623                                  DRIVEWAY - RESIDENTIAL
35       22836                                         OTHER (SPECIFY)
36       22458                                     TAVERN/LIQUOR STORE
37       22189                               HOSPITAL BUILDING/GROUNDS
38       18560                         POLICE FACILITY/VEH PARKING LOT
39       17570                             RESIDENCE - PORCH / HALLWAY
40       16296                                        AIRPORT/AIRCRAFT
41       15488                       CHURCH/SYNAGOGUE/PLACE OF WORSHIP
42       15153                         RESIDENCE - YARD (FRONT / BACK)
43       14757                            GOVERNMENT BUILDING/PROPERTY
44       14671                                                        
45       14656                            NURSING HOME/RETIREMENT HOME
46       14357                                      RESIDENCE - GARAGE
47       14324                                       CONSTRUCTION SITE
48       14182                             "SCHOOL, PRIVATE, BUILDING"
49       12404                                       CURRENCY EXCHANGE
50       12174                                      ABANDONED BUILDING
51       10697                                               WAREHOUSE
52       10276                             CTA GARAGE / OTHER PROPERTY
53       10238                                           ATHLETIC CLUB
54        8800                                            CTA BUS STOP
55        8772                                              BARBERSHOP
56        8705                          ATM (AUTOMATIC TELLER MACHINE)
57        7814                                                 TAXICAB
58        7803                                             CTA STATION
59        7553                                SCHOOL - PUBLIC BUILDING
60        7453                                                 LIBRARY
61        7429                                   MEDICAL/DENTAL OFFICE
62        7395                             HOSPITAL BUILDING / GROUNDS
63        6892                          FACTORY/MANUFACTURING BUILDING
64        6703                                 SCHOOL - PUBLIC GROUNDS
65        6656                                           HOTEL / MOTEL
66        5930                       OTHER RAILROAD PROP / TRAIN DEPOT
67        5787                              COLLEGE/UNIVERSITY GROUNDS
68        5627              AIRPORT TERMINAL UPPER LEVEL - SECURE AREA
69        5615                                      VEHICLE-COMMERCIAL
70        5333                                          CLEANING STORE
71        5290                                    SPORTS ARENA/STADIUM
72        4292                              "SCHOOL, PRIVATE, GROUNDS"
73        4195                   POLICE FACILITY / VEHICLE PARKING LOT
74        4051                               NURSING / RETIREMENT HOME
75        3849                                       VACANT LOT / LAND
76        3760                                         DAY CARE CENTER
77        3600                                                CAR WASH
78        3567                         OTHER COMMERCIAL TRANSPORTATION
79        2800                                   TAVERN / LIQUOR STORE
80        2732                                     MOVIE HOUSE/THEATER
81        2676                          GOVERNMENT BUILDING / PROPERTY
82        2668          AIRPORT TERMINAL LOWER LEVEL - NON-SECURE AREA
83        2594                                         APPLIANCE STORE
84        2351                               CHA PARKING LOT / GROUNDS
85        2343                   CHURCH / SYNAGOGUE / PLACE OF WORSHIP
86        1865                                     AIRPORT PARKING LOT
87        1652                                 MEDICAL / DENTAL OFFICE
88        1630                             AUTO / BOAT / RV DEALERSHIP
89        1528         AIRPORT BUILDING NON-TERMINAL - NON-SECURE AREA
90        1497                                SCHOOL - PRIVATE GROUNDS
91        1399                       COLLEGE/UNIVERSITY RESIDENCE HALL
92        1387                                                    AUTO
93        1318          AIRPORT TERMINAL UPPER LEVEL - NON-SECURE AREA
94        1309                                            FIRE STATION
95        1304                                 JAIL / LOCK-UP FACILITY
96        1301                      AIRPORT EXTERIOR - NON-SECURE AREA
97        1272                                    VEHICLE - COMMERCIAL
98        1181                          LAKEFRONT/WATERFRONT/RIVERBANK
99        1168                                   COIN OPERATED MACHINE
100       1153              AIRPORT TERMINAL LOWER LEVEL - SECURE AREA
101       1133                               SCHOOL - PRIVATE BUILDING
102       1085                                      HIGHWAY/EXPRESSWAY
103       1076                                        FEDERAL BUILDING
104       1012                           AIRPORT VENDING ESTABLISHMENT
105       1003                                               POOL ROOM
106        977                                                AIRCRAFT
107        962                                          DELIVERY TRUCK
108        920             AIRPORT BUILDING NON-TERMINAL - SECURE AREA
109        910                                         ANIMAL HOSPITAL
110        909               CTA PARKING LOT / GARAGE / OTHER PROPERTY
111        890                      CHA HALLWAY / STAIRWELL / ELEVATOR
112        825                                           BOWLING ALLEY
113        761                                               PAWN SHOP
114        749                                  SPORTS ARENA / STADIUM
115        734                   OTHER RAILROAD PROPERTY / TRAIN DEPOT
116        720                        FACTORY / MANUFACTURING BUILDING
117        705                                                   HOUSE
118        698                                         BOAT/WATERCRAFT
119        593                          AIRPORT EXTERIOR - SECURE AREA
120        592                                            CREDIT UNION
121        589 "VEHICLE - OTHER RIDE SHARE SERVICE (LYFT, UBER, ETC.)"
122        518                                                  BRIDGE
123        514                      LAKEFRONT / WATERFRONT / RIVERBANK
124        472                                         FOREST PRESERVE
125        467 "VEHICLE - OTHER RIDE SHARE SERVICE (E.G., UBER, LYFT)"
126        436                                                CEMETARY
127        426                                VEHICLE - DELIVERY TRUCK
128        407                                                   PORCH
129        403                          COLLEGE / UNIVERSITY - GROUNDS
130        395                                        SAVINGS AND LOAN
131        382                                   MOVIE HOUSE / THEATER
132        331                            VEHICLE - OTHER RIDE SERVICE
133        330                                                    YARD
134        282                                             PARKING LOT
135        269                                    HIGHWAY / EXPRESSWAY
136        245                                               NEWSSTAND
137        202                               CTA TRACKS - RIGHT OF WAY
138        174                     AIRPORT TRANSPORTATION SYSTEM (ATS)
139        157                                       BOAT / WATERCRAFT
140        152            AIRPORT TERMINAL MEZZANINE - NON-SECURE AREA
141        144                                              VACANT LOT
142        122                   COLLEGE / UNIVERSITY - RESIDENCE HALL
143        111                                                 HALLWAY
144        103                                            RETAIL STORE
145         79                           CASINO/GAMBLING ESTABLISHMENT
146         75                                                  GARAGE
147         75                                                 GANGWAY
148         71                                 GAS STATION DRIVE/PROP.
149         60                                         CHA PARKING LOT
150         51                                             CHA GROUNDS
151         40                                                  TAVERN
152         39                                             CHA HALLWAY
153         35                                                BASEMENT
154         28                                               VESTIBULE
155         28                                                DRIVEWAY
156         27                                               STAIRWELL
157         27                                                   HOTEL
158         27                                BARBER SHOP/BEAUTY SALON
159         22                                                  OFFICE
160         20                       VEHICLE - COMMERCIAL: TROLLEY BUS
161         20                                                  KENNEL
162         19                                                HOSPITAL
163         18                                       RAILROAD PROPERTY
164         18                                                    CLUB
165         17         VEHICLE - COMMERCIAL: ENTERTAINMENT / PARTY BUS
166         17                                             SCHOOL YARD
167         13                                            LIQUOR STORE
168         13                                    "CTA ""L"" PLATFORM"
169         11                                      GARAGE/AUTO REPAIR
170         11                                                    FARM
171         11                                       "CTA ""L"" TRAIN"
172         10                        VEHICLE-COMMERCIAL - TROLLEY BUS
173         10            VEHICLE-COMMERCIAL - ENTERTAINMENT/PARTY BUS
174         10                                            CTA PROPERTY
175         10                                           CHA STAIRWELL
176          9                                                   TRUCK
177          9                                               CHA LOBBY
178          7                                             WOODED AREA
179          7                                                   MOTEL
180          7                                                DUMPSTER
181          6                                                TAXI CAB
182          6                                              RIVER BANK
183          6                                            NURSING HOME
184          6                                                  CHURCH
185          5                                                    LAKE
186          4                                                 TRAILER
187          4                                                   RIVER
188          4                                            CHA PLAY LOT
189          3                                                    YMCA
190          3                                                   SEWER
191          3                                            HORSE STABLE
192          3                                             COACH HOUSE
193          3                                            CHA ELEVATOR
194          3                                           CHA BREEZEWAY
195          2                                           ROOMING HOUSE
196          2                                      PUBLIC HIGH SCHOOL
197          2                                   PUBLIC GRAMMAR SCHOOL
198          2                                                 PRAIRIE
199          2                                     LIVERY STAND OFFICE
200          2                                            LAUNDRY ROOM
201          2                                     GOVERNMENT BUILDING
202          2                                                 FACTORY
203          2                                                ELEVATOR
204          2                                      CTA SUBWAY STATION
205          2                                             COUNTY JAIL
206          2                                         CHURCH PROPERTY
207          2                                            BANQUET HALL
208          1                                       TRUCKING TERMINAL
209          1                                                    ROOF
210          1                                                POOLROOM
211          1                                         POLICE FACILITY
212          1                                            LOADING DOCK
213          1                                             LIVERY AUTO
214          1                                                  LAGOON
215          1                                  JUNK YARD/GARBAGE DUMP
216          1                                          FUNERAL PARLOR
217          1                                   EXPRESSWAY EMBANKMENT
218          1                                     CLEANERS/LAUNDROMAT
219          1                                                   BEACH</code></pre>
</div>
</div>
<ol start="8" type="1">
<li>Plot the longitude and latitude of all “ASSAULT”s for Ward 22</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="st">   SELECT Latitude, Longitude</span></span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a><span class="st">   FROM crime</span></span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a><span class="st">   WHERE PrimaryType='ASSAULT' AND Ward='22'"</span>)</span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Latitude<span class="sc">~</span>Longitude, <span class="at">data=</span>a, <span class="at">pch=</span><span class="st">"."</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06_Introduction_to_SQL1_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol start="9" type="1">
<li>What is the most common (Long,Lat) for assaults in Ward 22?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="st">   SELECT COUNT(*) AS crimecount,</span></span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a><span class="st">          Latitude, Longitude</span></span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a><span class="st">   FROM   crime</span></span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a><span class="st">   WHERE  PrimaryType='ASSAULT' AND Ward=22</span></span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a><span class="st">   GROUP BY Latitude, Longitude</span></span>
<span id="cb82-7"><a href="#cb82-7" aria-hidden="true" tabindex="-1"></a><span class="st">   ORDER BY crimecount DESC</span></span>
<span id="cb82-8"><a href="#cb82-8" aria-hidden="true" tabindex="-1"></a><span class="st">   LIMIT 1"</span>)</span>
<span id="cb82-9"><a href="#cb82-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-10"><a href="#cb82-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Latitude<span class="sc">~</span>Longitude, <span class="at">data=</span>a, <span class="at">pch=</span><span class="st">"."</span>)</span>
<span id="cb82-11"><a href="#cb82-11" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(Latitude<span class="sc">~</span>Longitude, </span>
<span id="cb82-12"><a href="#cb82-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">data=</span>b,</span>
<span id="cb82-13"><a href="#cb82-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">pch=</span><span class="dv">16</span>, </span>
<span id="cb82-14"><a href="#cb82-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">col=</span><span class="st">"salmon"</span>,</span>
<span id="cb82-15"><a href="#cb82-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">cex=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06_Introduction_to_SQL1_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>b</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  crimecount Latitude Longitude
1        229 41.84905 -87.70883</code></pre>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = true;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>