<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Greg Ridgeway">
<meta name="author" content="Ruth Moyer">
<meta name="dcterms.date" content="2025-09-21">

<title>Introduction to SQL, Part 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="08_Introduction_to_SQL2_files/libs/clipboard/clipboard.min.js"></script>
<script src="08_Introduction_to_SQL2_files/libs/quarto-html/quarto.js"></script>
<script src="08_Introduction_to_SQL2_files/libs/quarto-html/popper.min.js"></script>
<script src="08_Introduction_to_SQL2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="08_Introduction_to_SQL2_files/libs/quarto-html/anchor.min.js"></script>
<link href="08_Introduction_to_SQL2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="08_Introduction_to_SQL2_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="08_Introduction_to_SQL2_files/libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="08_Introduction_to_SQL2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="08_Introduction_to_SQL2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="08_Introduction_to_SQL2_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="08_Introduction_to_SQL2_files/libs/bootstrap/bootstrap-dark.min.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#creating-an-iucr-lookup-table" id="toc-creating-an-iucr-lookup-table" class="nav-link active" data-scroll-target="#creating-an-iucr-lookup-table"><span class="header-section-number">1</span> Creating an IUCR lookup table</a>
  <ul class="collapse">
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">1.1</span> Exercises</a></li>
  </ul></li>
  <li><a href="#sql-dates" id="toc-sql-dates" class="nav-link" data-scroll-target="#sql-dates"><span class="header-section-number">2</span> SQL dates</a></li>
  <li><a href="#creating-the-final-table" id="toc-creating-the-final-table" class="nav-link" data-scroll-target="#creating-the-final-table"><span class="header-section-number">3</span> Creating the final table</a></li>
  <li><a href="#joining-data-across-tables" id="toc-joining-data-across-tables" class="nav-link" data-scroll-target="#joining-data-across-tables"><span class="header-section-number">4</span> Joining data across tables</a>
  <ul class="collapse">
  <li><a href="#exercises-1" id="toc-exercises-1" class="nav-link" data-scroll-target="#exercises-1"><span class="header-section-number">4.1</span> Exercises</a></li>
  </ul></li>
  <li><a href="#subqueries" id="toc-subqueries" class="nav-link" data-scroll-target="#subqueries"><span class="header-section-number">5</span> Subqueries</a>
  <ul class="collapse">
  <li><a href="#exercise" id="toc-exercise" class="nav-link" data-scroll-target="#exercise"><span class="header-section-number">5.1</span> Exercise</a></li>
  </ul></li>
  <li><a href="#solutions" id="toc-solutions" class="nav-link" data-scroll-target="#solutions"><span class="header-section-number">6</span> Solutions</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="08_Introduction_to_SQL2.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Introduction to SQL, Part 2</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Greg Ridgeway <a href="mailto:gridge@upenn.edu" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Pennsylvania
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Ruth Moyer <a href="mailto:moyruth@upenn.edu" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Pennsylvania
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 21, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<!-- quarto render 08_Introduction_to_SQL2.qmd -->
<!-- git commit 08* -m "commit message" -->
<!-- git status -->
<!-- git push -->
<!-- A function for automating the numbering and wording of the exercise questions -->
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<section id="creating-an-iucr-lookup-table" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Creating an IUCR lookup table</h1>
<p>The crime table in our Chicago crime database is not ideal. It is overly complicated to extract the year from a date. There is also a lot of redundant information in the table.</p>
<p>Let’s take a look at a few example rows.</p>
<table class="table">
<colgroup>
<col style="width: 34%">
<col style="width: 5%">
<col style="width: 21%">
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Block</th>
<th style="text-align: left;">IUCR</th>
<th style="text-align: left;">PrimaryType</th>
<th style="text-align: left;">FBICode</th>
<th style="text-align: left;">Longitude</th>
<th style="text-align: left;">Latitude</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">040XX W 26TH ST</td>
<td style="text-align: left;">0560</td>
<td style="text-align: left;">ASSAULT</td>
<td style="text-align: left;">08A</td>
<td style="text-align: left;">-87.67741</td>
<td style="text-align: left;">41.90842</td>
</tr>
<tr class="even">
<td style="text-align: left;">089XX S SOUTH CHICAGO AVE</td>
<td style="text-align: left;">0498</td>
<td style="text-align: left;">BATTERY</td>
<td style="text-align: left;">04B</td>
<td style="text-align: left;">-87.63394</td>
<td style="text-align: left;">41.88602</td>
</tr>
<tr class="odd">
<td style="text-align: left;">052XX S HARPER AVE</td>
<td style="text-align: left;">2820</td>
<td style="text-align: left;">OTHER OFFENSE</td>
<td style="text-align: left;">26</td>
<td style="text-align: left;">-87.62615</td>
<td style="text-align: left;">41.87183</td>
</tr>
<tr class="even">
<td style="text-align: left;">033XX N TROY ST</td>
<td style="text-align: left;">2825</td>
<td style="text-align: left;">OTHER OFFENSE</td>
<td style="text-align: left;">26</td>
<td style="text-align: left;">-87.69560</td>
<td style="text-align: left;">41.85655</td>
</tr>
<tr class="odd">
<td style="text-align: left;">015XX W 107TH ST</td>
<td style="text-align: left;">1310</td>
<td style="text-align: left;">CRIMINAL DAMAGE</td>
<td style="text-align: left;">14</td>
<td style="text-align: left;">-87.59488</td>
<td style="text-align: left;">41.65512</td>
</tr>
<tr class="even">
<td style="text-align: left;">0000X N LARAMIE AVE</td>
<td style="text-align: left;">2018</td>
<td style="text-align: left;">NARCOTICS</td>
<td style="text-align: left;">18</td>
<td style="text-align: left;">-87.76673</td>
<td style="text-align: left;">41.94523</td>
</tr>
<tr class="odd">
<td style="text-align: left;">0000X N KEELER AVE</td>
<td style="text-align: left;">0554</td>
<td style="text-align: left;">ASSAULT</td>
<td style="text-align: left;">08A</td>
<td style="text-align: left;">-87.61501</td>
<td style="text-align: left;">41.76935</td>
</tr>
<tr class="even">
<td style="text-align: left;">026XX N ELSTON AVE</td>
<td style="text-align: left;">0560</td>
<td style="text-align: left;">ASSAULT</td>
<td style="text-align: left;">08A</td>
<td style="text-align: left;">-87.57389</td>
<td style="text-align: left;">41.76742</td>
</tr>
<tr class="odd">
<td style="text-align: left;">076XX S ABERDEEN ST</td>
<td style="text-align: left;">0486</td>
<td style="text-align: left;">BATTERY</td>
<td style="text-align: left;">08B</td>
<td style="text-align: left;">-87.64308</td>
<td style="text-align: left;">41.76094</td>
</tr>
<tr class="even">
<td style="text-align: left;">3XX N SHEFFIELD AVE</td>
<td style="text-align: left;">1811</td>
<td style="text-align: left;">NARCOTICS</td>
<td style="text-align: left;">18</td>
<td style="text-align: left;">-87.70109</td>
<td style="text-align: left;">41.79261</td>
</tr>
</tbody>
</table>
<p>Note that whenever <code>IUCR</code> is 0560, then <code>PrimaryType</code> is ASSAULT and <code>FBICode</code> is 08A. There is no reason to store the IUCR code, the primary crime type, and the FBI code all in the same file. We should keep a separate table that links the IUCR codes, the primary crime types, and the FBI codes. Note that it is essential to store the IUCR code in the crime table. Both IUCR codes 2018 and 1811 both link to NARCOTICS and FBI code 18. If we deleted IUCR from the crime table and kept only the primary crime type, then we would lose some detailed information. Here is Chicago PD’s <a href="https://www.chicagopolice.org/statistics-data/data-requests/">listing of FBI codes</a>.</p>
<p>Aside from reducing database size, eliminating redundant information also provides “update consistency.” In the table’s current form, we could erroneously add a row that had <code>IUCR</code> 0560, <code>PrimaryType</code> as BATTERY, and <code>FBICode</code> 14.</p>
<table class="table">
<colgroup>
<col style="width: 34%">
<col style="width: 5%">
<col style="width: 21%">
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Block</th>
<th style="text-align: left;">IUCR</th>
<th style="text-align: left;">PrimaryType</th>
<th style="text-align: left;">FBICode</th>
<th style="text-align: left;">Longitude</th>
<th style="text-align: left;">Latitude</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">040XX W 26TH ST</td>
<td style="text-align: left;">0560</td>
<td style="text-align: left;">ASSAULT</td>
<td style="text-align: left;">08A</td>
<td style="text-align: left;">-87.67741</td>
<td style="text-align: left;">41.90842</td>
</tr>
<tr class="even">
<td style="text-align: left;">040XX W 26TH ST</td>
<td style="text-align: left;">0560</td>
<td style="text-align: left;">BATTERY</td>
<td style="text-align: left;">14</td>
<td style="text-align: left;">-87.67741</td>
<td style="text-align: left;">41.90842</td>
</tr>
</tbody>
</table>
<p>The database would not complain even though this is an incorrect combination. IUCR code 0560 <em>must</em> link with ASSAULT and 08A. An IUCR lookup table avoids this possibility. The lookup table has each IUCR code showing up only once and always linking to the correct <code>PrimaryType</code> and <code>FBICode</code>.</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">IUCR</th>
<th style="text-align: left;">PrimaryType</th>
<th style="text-align: left;">FBICode</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0486</td>
<td style="text-align: left;">BATTERY</td>
<td style="text-align: left;">08B</td>
</tr>
<tr class="even">
<td style="text-align: left;">0498</td>
<td style="text-align: left;">BATTERY</td>
<td style="text-align: left;">04B</td>
</tr>
<tr class="odd">
<td style="text-align: left;">0554</td>
<td style="text-align: left;">ASSAULT</td>
<td style="text-align: left;">08A</td>
</tr>
<tr class="even">
<td style="text-align: left;">0560</td>
<td style="text-align: left;">ASSAULT</td>
<td style="text-align: left;">08A</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1310</td>
<td style="text-align: left;">CRIMINAL DAMAGE</td>
<td style="text-align: left;">14</td>
</tr>
<tr class="even">
<td style="text-align: left;">1811</td>
<td style="text-align: left;">NARCOTICS</td>
<td style="text-align: left;">18</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2018</td>
<td style="text-align: left;">NARCOTICS</td>
<td style="text-align: left;">18</td>
</tr>
<tr class="even">
<td style="text-align: left;">2820</td>
<td style="text-align: left;">OTHER OFFENSE</td>
<td style="text-align: left;">26</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2825</td>
<td style="text-align: left;">OTHER OFFENSE</td>
<td style="text-align: left;">26</td>
</tr>
</tbody>
</table>
<p>Then we can remove <code>PrimaryType</code> and <code>FBICode</code> from the crime table and look up the associated <code>PrimaryType</code> and <code>FBICode</code> from the IUCR lookup table whenever we need that information.</p>
<p>Let’s start by reconnecting to the Chicago crime database.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(RSQLite)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>con <span class="ot">&lt;-</span> <span class="fu">dbConnect</span>(<span class="fu">SQLite</span>(), <span class="st">"chicagocrime.db"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The SQL keyword <code>DISTINCT</code> will filter out any duplicated rows in the result set so that every row is a unique combination of values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="st">  SELECT DISTINCT IUCR, PrimaryType, FBIcode</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="st">  FROM crime"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  IUCR                PrimaryType FBICode
1 1582 OFFENSE INVOLVING CHILDREN      17
2 2017                  NARCOTICS      18
3 0326                    ROBBERY      03
4 0281        CRIM SEXUAL ASSAULT      02
5 1320            CRIMINAL DAMAGE      14
6 0810                      THEFT      06</code></pre>
</div>
</div>
<p>This creates a lookup table showing how IUCR links to the primary crime types and FBI codes. We should check that each IUCR code uniquely links to a single primary type and a single FBI code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>a <span class="sc">|&gt;</span> <span class="fu">count</span>(IUCR) <span class="sc">|&gt;</span> <span class="fu">filter</span>(n <span class="sc">&gt;</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   IUCR n
1  0261 2
2  0262 2
3  0263 2
4  0264 2
5  0265 2
6  0266 2
7  0271 2
8  0272 2
9  0273 2
10 0274 2
11 0275 2
12 0281 2
13 0291 2
14 1030 2
15 1035 2
16 1261 2
17 1537 2
18 1540 2
19 1541 2
20 1576 2
21 1581 2
22 1710 2
23 1715 2
24 1725 2
25 1750 2
26 1751 2
27 1752 2
28 1755 2
29 1780 2
30 1790 2
31 1792 2
32 2091 2
33 2092 2
34 2093 2
35 2820 2
36 2850 2
37 2851 2
38 2890 2
39 2895 2
40 3300 2
41 3400 2
42 3960 2
43 3961 2
44 3966 2
45 5114 2</code></pre>
</div>
</div>
<p>Unfortunately, it looks like several IUCR codes have multiple values for <code>PrimaryType</code> and/or <code>FBICode</code>. Let’s start by examining codes 2091, 2092, and 2093.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="st">  SELECT COUNT(*) AS crimecount,</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="st">         IUCR,</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="st">         PrimaryType,</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="st">         FBICode,</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="st">         SUBSTR(Date, 7, 4) AS year</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="st">  FROM crime</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="st">  WHERE IUCR IN ('2091', '2092', '2093')</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="st">  GROUP BY IUCR, PrimaryType, year, FBICode</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="st">  ORDER BY IUCR, PrimaryType, year, FBICode"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   crimecount IUCR PrimaryType FBICode year
1         389 2091   NARCOTICS      26 2001
2         267 2091   NARCOTICS      26 2002
3         238 2091   NARCOTICS      26 2003
4         288 2091   NARCOTICS      26 2004
5         253 2091   NARCOTICS      26 2005
6         232 2091   NARCOTICS      26 2006
7         221 2091   NARCOTICS      26 2007
8         225 2091   NARCOTICS      26 2008
9         246 2091   NARCOTICS      26 2009
10        208 2091   NARCOTICS      26 2010
11        178 2091   NARCOTICS      26 2011
12          1 2091   NARCOTICS      18 2012
13        205 2091   NARCOTICS      26 2012
14          2 2091   NARCOTICS      18 2013
15        195 2091   NARCOTICS      26 2013
16         27 2091   NARCOTICS      18 2014
17        166 2091   NARCOTICS      26 2014
18        136 2091   NARCOTICS      18 2015
19         28 2091   NARCOTICS      26 2015
20        123 2091   NARCOTICS      18 2016
21        113 2091   NARCOTICS      18 2017
22        105 2091   NARCOTICS      18 2018
23        106 2091   NARCOTICS      18 2019
24         83 2091   NARCOTICS      18 2020
25         61 2091   NARCOTICS      18 2021
26         48 2091   NARCOTICS      18 2022
27         29 2091   NARCOTICS      18 2023
28         15 2091   NARCOTICS      18 2024
29          6 2091   NARCOTICS      18 2025
30       1675 2092   NARCOTICS      26 2001
31       2373 2092   NARCOTICS      26 2002
32       2775 2092   NARCOTICS      26 2003
33       3094 2092   NARCOTICS      26 2004
34       3130 2092   NARCOTICS      26 2005
35       3049 2092   NARCOTICS      26 2006
36       2726 2092   NARCOTICS      26 2007
37       1523 2092   NARCOTICS      26 2008
38       1435 2092   NARCOTICS      26 2009
39       1056 2092   NARCOTICS      26 2010
40        767 2092   NARCOTICS      26 2011
41        672 2092   NARCOTICS      26 2012
42        679 2092   NARCOTICS      26 2013
43        542 2092   NARCOTICS      26 2014
44        126 2092   NARCOTICS      18 2015
45        237 2092   NARCOTICS      26 2015
46        212 2092   NARCOTICS      18 2016
47        373 2092   NARCOTICS      18 2017
48        595 2092   NARCOTICS      18 2018
49        678 2092   NARCOTICS      18 2019
50        271 2092   NARCOTICS      18 2020
51         71 2092   NARCOTICS      18 2021
52        144 2092   NARCOTICS      18 2022
53        125 2092   NARCOTICS      18 2023
54         45 2092   NARCOTICS      18 2024
55         71 2092   NARCOTICS      18 2025
56        972 2093   NARCOTICS      26 2001
57        866 2093   NARCOTICS      26 2002
58        968 2093   NARCOTICS      26 2003
59        864 2093   NARCOTICS      26 2004
60        839 2093   NARCOTICS      26 2005
61        909 2093   NARCOTICS      26 2006
62       1033 2093   NARCOTICS      26 2007
63          2 2093   NARCOTICS      18 2008
64       1208 2093   NARCOTICS      26 2008
65          1 2093   NARCOTICS      18 2009
66       1099 2093   NARCOTICS      26 2009
67          2 2093   NARCOTICS      18 2010
68       1017 2093   NARCOTICS      26 2010
69          2 2093   NARCOTICS      18 2011
70        934 2093   NARCOTICS      26 2011
71         16 2093   NARCOTICS      18 2012
72        935 2093   NARCOTICS      26 2012
73         16 2093   NARCOTICS      18 2013
74        760 2093   NARCOTICS      26 2013
75         15 2093   NARCOTICS      18 2014
76        676 2093   NARCOTICS      26 2014
77        323 2093   NARCOTICS      18 2015
78        332 2093   NARCOTICS      26 2015
79        846 2093   NARCOTICS      18 2016
80       1000 2093   NARCOTICS      18 2017
81       1067 2093   NARCOTICS      18 2018
82       1052 2093   NARCOTICS      18 2019
83        760 2093   NARCOTICS      18 2020
84        776 2093   NARCOTICS      18 2021
85        634 2093   NARCOTICS      18 2022
86        641 2093   NARCOTICS      18 2023
87        693 2093   NARCOTICS      18 2024
88        477 2093   NARCOTICS      18 2025</code></pre>
</div>
</div>
<p>These are all narcotics cases, but we see that in some years, these charges are marked as FBI code 18 (crimes of production, sale, use of drugs) and sometimes 26 (a miscellaneous category). FBI code 26 appears more commonly, but the FBI code 26 appears to phase out after 2015. 2091 is a narcotics code for “forfeit property,” 2092 is for “soliciting narcotics on a public way,” and 2093 is for “found suspect narcotics.” It appears that the CPD is now using the more specific FBI codes rather than the generic miscellaneous. The most practical decision is to use the most modern coding and use code 18 for these crimes.</p>
<p>A similar story applies to IUCR crimes 1710, 1715, 1725, 1755, and 1780. These are all offenses involving children that prior to 2016 had been given the FBI miscellaneous code 26, but more recently have been coded as 20 (offenses against family). Again, it seems reasonable to use the most modern coding choice and use FBI code 20.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="st">  SELECT COUNT(*) AS crimecount,</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="st">         IUCR,</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="st">         PrimaryType,</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="st">         FBICode,</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="st">         SUBSTR(Date, 7, 4) AS year</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="st">  FROM crime</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="st">  WHERE IUCR IN ('1710','1715','1725','1755','1780')</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="st">  GROUP BY IUCR, PrimaryType, year, FBICode</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="st">  ORDER BY IUCR, PrimaryType, year, FBICode"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    crimecount IUCR                PrimaryType FBICode year
1          503 1710 OFFENSE INVOLVING CHILDREN      26 2001
2          506 1710 OFFENSE INVOLVING CHILDREN      26 2002
3          479 1710 OFFENSE INVOLVING CHILDREN      26 2003
4          427 1710 OFFENSE INVOLVING CHILDREN      26 2004
5          413 1710 OFFENSE INVOLVING CHILDREN      26 2005
6          392 1710 OFFENSE INVOLVING CHILDREN      26 2006
7          403 1710 OFFENSE INVOLVING CHILDREN      26 2007
8          337 1710 OFFENSE INVOLVING CHILDREN      26 2008
9          374 1710 OFFENSE INVOLVING CHILDREN      26 2009
10         362 1710 OFFENSE INVOLVING CHILDREN      26 2010
11           1 1710 OFFENSE INVOLVING CHILDREN      20 2011
12         331 1710 OFFENSE INVOLVING CHILDREN      26 2011
13           1 1710 OFFENSE INVOLVING CHILDREN      20 2012
14         333 1710 OFFENSE INVOLVING CHILDREN      26 2012
15           6 1710 OFFENSE INVOLVING CHILDREN      20 2013
16         270 1710 OFFENSE INVOLVING CHILDREN      26 2013
17           2 1710 OFFENSE INVOLVING CHILDREN      20 2014
18         315 1710 OFFENSE INVOLVING CHILDREN      26 2014
19          22 1710 OFFENSE INVOLVING CHILDREN      20 2015
20         265 1710 OFFENSE INVOLVING CHILDREN      26 2015
21         276 1710 OFFENSE INVOLVING CHILDREN      20 2016
22           8 1710 OFFENSE INVOLVING CHILDREN      26 2016
23         328 1710 OFFENSE INVOLVING CHILDREN      20 2017
24         334 1710 OFFENSE INVOLVING CHILDREN      20 2018
25         384 1710 OFFENSE INVOLVING CHILDREN      20 2019
26         289 1710 OFFENSE INVOLVING CHILDREN      20 2020
27         261 1710 OFFENSE INVOLVING CHILDREN      20 2021
28         289 1710 OFFENSE INVOLVING CHILDREN      20 2022
29         262 1710 OFFENSE INVOLVING CHILDREN      20 2023
30         349 1710 OFFENSE INVOLVING CHILDREN      20 2024
31         219 1710 OFFENSE INVOLVING CHILDREN      20 2025
32           4 1715 OFFENSE INVOLVING CHILDREN      26 2003
33           1 1715 OFFENSE INVOLVING CHILDREN      26 2006
34           1 1715 OFFENSE INVOLVING CHILDREN      26 2007
35           3 1715 OFFENSE INVOLVING CHILDREN      26 2008
36           2 1715 OFFENSE INVOLVING CHILDREN      26 2009
37           3 1715 OFFENSE INVOLVING CHILDREN      26 2010
38           2 1715 OFFENSE INVOLVING CHILDREN      26 2011
39           4 1715 OFFENSE INVOLVING CHILDREN      26 2012
40           1 1715 OFFENSE INVOLVING CHILDREN      26 2013
41           1 1715 OFFENSE INVOLVING CHILDREN      26 2015
42           1 1715 OFFENSE INVOLVING CHILDREN      20 2016
43           1 1715 OFFENSE INVOLVING CHILDREN      20 2017
44           2 1715 OFFENSE INVOLVING CHILDREN      20 2018
45           3 1715 OFFENSE INVOLVING CHILDREN      20 2019
46           2 1715 OFFENSE INVOLVING CHILDREN      20 2020
47           2 1715 OFFENSE INVOLVING CHILDREN      20 2021
48           1 1715 OFFENSE INVOLVING CHILDREN      20 2024
49           2 1725 OFFENSE INVOLVING CHILDREN      26 2002
50           4 1725 OFFENSE INVOLVING CHILDREN      26 2003
51           1 1725 OFFENSE INVOLVING CHILDREN      26 2004
52           5 1725 OFFENSE INVOLVING CHILDREN      26 2005
53           4 1725 OFFENSE INVOLVING CHILDREN      26 2006
54           9 1725 OFFENSE INVOLVING CHILDREN      26 2007
55           4 1725 OFFENSE INVOLVING CHILDREN      26 2008
56           3 1725 OFFENSE INVOLVING CHILDREN      26 2009
57          16 1725 OFFENSE INVOLVING CHILDREN      26 2010
58           9 1725 OFFENSE INVOLVING CHILDREN      26 2011
59           7 1725 OFFENSE INVOLVING CHILDREN      26 2012
60          12 1725 OFFENSE INVOLVING CHILDREN      26 2013
61           2 1725 OFFENSE INVOLVING CHILDREN      20 2014
62          12 1725 OFFENSE INVOLVING CHILDREN      26 2014
63           1 1725 OFFENSE INVOLVING CHILDREN      20 2015
64           9 1725 OFFENSE INVOLVING CHILDREN      26 2015
65           4 1725 OFFENSE INVOLVING CHILDREN      20 2016
66          15 1725 OFFENSE INVOLVING CHILDREN      20 2017
67           6 1725 OFFENSE INVOLVING CHILDREN      20 2018
68           7 1725 OFFENSE INVOLVING CHILDREN      20 2019
69           5 1725 OFFENSE INVOLVING CHILDREN      20 2020
70           1 1725 OFFENSE INVOLVING CHILDREN      20 2021
71           1 1725 OFFENSE INVOLVING CHILDREN      20 2022
72           4 1725 OFFENSE INVOLVING CHILDREN      20 2023
73           5 1725 OFFENSE INVOLVING CHILDREN      20 2024
74           3 1725 OFFENSE INVOLVING CHILDREN      20 2025
75          37 1755 OFFENSE INVOLVING CHILDREN      26 2002
76          75 1755 OFFENSE INVOLVING CHILDREN      26 2003
77          69 1755 OFFENSE INVOLVING CHILDREN      26 2004
78          64 1755 OFFENSE INVOLVING CHILDREN      26 2005
79          70 1755 OFFENSE INVOLVING CHILDREN      26 2006
80          59 1755 OFFENSE INVOLVING CHILDREN      26 2007
81          49 1755 OFFENSE INVOLVING CHILDREN      26 2008
82          34 1755 OFFENSE INVOLVING CHILDREN      26 2009
83          52 1755 OFFENSE INVOLVING CHILDREN      26 2010
84          52 1755 OFFENSE INVOLVING CHILDREN      26 2011
85          39 1755 OFFENSE INVOLVING CHILDREN      26 2012
86          49 1755 OFFENSE INVOLVING CHILDREN      26 2013
87          43 1755 OFFENSE INVOLVING CHILDREN      26 2014
88           3 1755 OFFENSE INVOLVING CHILDREN      20 2015
89          32 1755 OFFENSE INVOLVING CHILDREN      26 2015
90          32 1755 OFFENSE INVOLVING CHILDREN      20 2016
91          46 1755 OFFENSE INVOLVING CHILDREN      20 2017
92          29 1755 OFFENSE INVOLVING CHILDREN      20 2018
93          38 1755 OFFENSE INVOLVING CHILDREN      20 2019
94          36 1755 OFFENSE INVOLVING CHILDREN      20 2020
95          36 1755 OFFENSE INVOLVING CHILDREN      20 2021
96          30 1755 OFFENSE INVOLVING CHILDREN      20 2022
97          59 1755 OFFENSE INVOLVING CHILDREN      20 2023
98          53 1755 OFFENSE INVOLVING CHILDREN      20 2024
99          41 1755 OFFENSE INVOLVING CHILDREN      20 2025
100         11 1780 OFFENSE INVOLVING CHILDREN      26 2001
101        166 1780 OFFENSE INVOLVING CHILDREN      26 2002
102        352 1780 OFFENSE INVOLVING CHILDREN      26 2003
103        559 1780 OFFENSE INVOLVING CHILDREN      26 2004
104        465 1780 OFFENSE INVOLVING CHILDREN      26 2005
105        504 1780 OFFENSE INVOLVING CHILDREN      26 2006
106        613 1780 OFFENSE INVOLVING CHILDREN      26 2007
107        624 1780 OFFENSE INVOLVING CHILDREN      26 2008
108        658 1780 OFFENSE INVOLVING CHILDREN      26 2009
109          2 1780 OFFENSE INVOLVING CHILDREN      20 2010
110        616 1780 OFFENSE INVOLVING CHILDREN      26 2010
111          1 1780 OFFENSE INVOLVING CHILDREN      20 2011
112        649 1780 OFFENSE INVOLVING CHILDREN      26 2011
113          2 1780 OFFENSE INVOLVING CHILDREN      20 2012
114        628 1780 OFFENSE INVOLVING CHILDREN      26 2012
115          1 1780 OFFENSE INVOLVING CHILDREN      20 2013
116        628 1780 OFFENSE INVOLVING CHILDREN      26 2013
117          2 1780 OFFENSE INVOLVING CHILDREN      20 2014
118        608 1780 OFFENSE INVOLVING CHILDREN      26 2014
119         17 1780 OFFENSE INVOLVING CHILDREN      20 2015
120        516 1780 OFFENSE INVOLVING CHILDREN      26 2015
121        540 1780 OFFENSE INVOLVING CHILDREN      20 2016
122         38 1780 OFFENSE INVOLVING CHILDREN      26 2016
123        415 1780 OFFENSE INVOLVING CHILDREN      20 2017
124        398 1780 OFFENSE INVOLVING CHILDREN      20 2018
125        341 1780 OFFENSE INVOLVING CHILDREN      20 2019
126        419 1780 OFFENSE INVOLVING CHILDREN      20 2020
127        393 1780 OFFENSE INVOLVING CHILDREN      20 2021
128        330 1780 OFFENSE INVOLVING CHILDREN      20 2022
129        260 1780 OFFENSE INVOLVING CHILDREN      20 2023
130        261 1780 OFFENSE INVOLVING CHILDREN      20 2024
131        208 1780 OFFENSE INVOLVING CHILDREN      20 2025</code></pre>
</div>
</div>
<p>IUCR codes 1030 and 1035, which involve possession of incendiary devices, are now being coded as arson (09) rather than miscellaneous (26).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="st">  SELECT COUNT(*) AS crimecount,</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="st">         IUCR,</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="st">         PrimaryType,</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="st">         FBICode,</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="st">         SUBSTR(Date,7,4) AS year</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="st">  FROM crime</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="st">  WHERE IUCR IN ('1030','1035')</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="st">  GROUP BY IUCR, PrimaryType, year, FBICode</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="st">  ORDER BY IUCR, PrimaryType, year, FBICode"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   crimecount IUCR PrimaryType FBICode year
1           6 1030       ARSON      26 2001
2           2 1030       ARSON      26 2002
3           5 1030       ARSON      26 2003
4           4 1030       ARSON      26 2004
5           3 1030       ARSON      26 2005
6           7 1030       ARSON      26 2006
7           5 1030       ARSON      26 2007
8           7 1030       ARSON      26 2008
9           5 1030       ARSON      26 2009
10          9 1030       ARSON      26 2010
11          5 1030       ARSON      26 2011
12          2 1030       ARSON      26 2012
13          6 1030       ARSON      26 2013
14          2 1030       ARSON      26 2014
15          5 1030       ARSON      26 2015
16          2 1030       ARSON      09 2016
17          1 1030       ARSON      26 2016
18          3 1030       ARSON      09 2017
19          1 1030       ARSON      09 2018
20          3 1030       ARSON      09 2019
21          4 1030       ARSON      09 2020
22          9 1030       ARSON      09 2021
23          4 1030       ARSON      09 2022
24          7 1030       ARSON      09 2023
25          4 1030       ARSON      09 2024
26          7 1030       ARSON      09 2025
27          7 1035       ARSON      26 2002
28          2 1035       ARSON      26 2004
29          3 1035       ARSON      26 2005
30          8 1035       ARSON      26 2006
31          6 1035       ARSON      26 2007
32          6 1035       ARSON      26 2008
33          4 1035       ARSON      26 2009
34          1 1035       ARSON      26 2010
35          1 1035       ARSON      26 2011
36          1 1035       ARSON      26 2012
37          1 1035       ARSON      09 2016</code></pre>
</div>
</div>
<p>This all points to a modernization of FBI codes where Chicago adopted more specific FBI codes rather than placing them in the miscellaneous category.</p>
<p>Lastly, there are some inconsistent spellings of primary crime types. The spelling of the primary type for 5114 has changed to remove the extra spaces. Even though they differ only by a few spaces, SQL will conclude that these are different values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>   <span class="st">"SELECT COUNT(*) AS crimecount,</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="st">           IUCR,</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="st">           PrimaryType,</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="st">           FBICode,</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="st">           SUBSTR(Date, 7, 4) AS year</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="st">    FROM crime</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="st">    WHERE IUCR='5114'</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="st">    GROUP BY IUCR, PrimaryType, FBICode, year"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  crimecount IUCR    PrimaryType FBICode year
1          3 5114 NON - CRIMINAL      26 2013
2         10 5114 NON - CRIMINAL      26 2014
3         20 5114 NON - CRIMINAL      26 2015
4          5 5114 NON - CRIMINAL      26 2016
5          1 5114   NON-CRIMINAL      26 2015
6         14 5114   NON-CRIMINAL      26 2016
7          7 5114   NON-CRIMINAL      26 2017
8         15 5114   NON-CRIMINAL      26 2018
9          1 5114   NON-CRIMINAL      26 2019</code></pre>
</div>
</div>
<p>Criminal sexual assault also has an inconsistent spelling.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="st">  SELECT COUNT(*) AS crimcount,</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="st">         PrimaryType,</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="st">         year</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="st">  FROM crime</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="st">  WHERE iucr IN ('0261','0263','0264','0265','0266','0271','0281','0291')</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="st">  GROUP BY PrimaryType, year</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="st">  ORDER BY year"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   crimcount             PrimaryType Year
1       1712     CRIM SEXUAL ASSAULT 2001
2         42 CRIMINAL SEXUAL ASSAULT 2001
3       1740     CRIM SEXUAL ASSAULT 2002
4         38 CRIMINAL SEXUAL ASSAULT 2002
5       1532     CRIM SEXUAL ASSAULT 2003
6         53 CRIMINAL SEXUAL ASSAULT 2003
7       1495     CRIM SEXUAL ASSAULT 2004
8         56 CRIMINAL SEXUAL ASSAULT 2004
9       1485     CRIM SEXUAL ASSAULT 2005
10        52 CRIMINAL SEXUAL ASSAULT 2005
11      1402     CRIM SEXUAL ASSAULT 2006
12        59 CRIMINAL SEXUAL ASSAULT 2006
13      1469     CRIM SEXUAL ASSAULT 2007
14        66 CRIMINAL SEXUAL ASSAULT 2007
15      1477     CRIM SEXUAL ASSAULT 2008
16        65 CRIMINAL SEXUAL ASSAULT 2008
17      1366     CRIM SEXUAL ASSAULT 2009
18        59 CRIMINAL SEXUAL ASSAULT 2009
19      1291     CRIM SEXUAL ASSAULT 2010
20        78 CRIMINAL SEXUAL ASSAULT 2010
21      1414     CRIM SEXUAL ASSAULT 2011
22        74 CRIMINAL SEXUAL ASSAULT 2011
23      1360     CRIM SEXUAL ASSAULT 2012
24        89 CRIMINAL SEXUAL ASSAULT 2012
25      1224     CRIM SEXUAL ASSAULT 2013
26       103 CRIMINAL SEXUAL ASSAULT 2013
27      1275     CRIM SEXUAL ASSAULT 2014
28       104 CRIMINAL SEXUAL ASSAULT 2014
29      1311     CRIM SEXUAL ASSAULT 2015
30       131 CRIMINAL SEXUAL ASSAULT 2015
31      1453     CRIM SEXUAL ASSAULT 2016
32       156 CRIMINAL SEXUAL ASSAULT 2016
33      1453     CRIM SEXUAL ASSAULT 2017
34       229 CRIMINAL SEXUAL ASSAULT 2017
35      1364     CRIM SEXUAL ASSAULT 2018
36       364 CRIMINAL SEXUAL ASSAULT 2018
37       884     CRIM SEXUAL ASSAULT 2019
38       771 CRIMINAL SEXUAL ASSAULT 2019
39        75     CRIM SEXUAL ASSAULT 2020
40      1169 CRIMINAL SEXUAL ASSAULT 2020
41      1516 CRIMINAL SEXUAL ASSAULT 2021
42      1591 CRIMINAL SEXUAL ASSAULT 2022
43      1646 CRIMINAL SEXUAL ASSAULT 2023
44      1576 CRIMINAL SEXUAL ASSAULT 2024
45      1034 CRIMINAL SEXUAL ASSAULT 2025</code></pre>
</div>
</div>
<p>The conclusion of all of this is that if there is any inconsistency in the connection between <code>IUCR</code>, <code>PrimaryType</code>, and <code>FBICode</code>, then we should choose the most recent combination and delete the rest as options. The following SQL query finds for each IUCR the most recent year that it occurred in the dataset. Not all codes appear in the most recent year. Several IUCR codes last occurred before 2015.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="st">    SELECT IUCR, MAX(year) AS maxyear</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="st">    FROM crime</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="st">    GROUP BY IUCR"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    IUCR maxyear
1   0110    2025
2   0130    2022
3   0141    2022
4   0142    2025
5   0261    2025
6   0262    2025
7   0263    2025
8   0264    2025
9   0265    2025
10  0266    2025
11  0271    2025
12  0272    2024
13  0273    2025
14  0274    2024
15  0275    2025
16  0281    2025
17  0291    2025
18  0312    2025
19  0313    2025
20  031A    2025
21  031B    2025
22  0320    2025
23  0325    2025
24  0326    2025
25  0330    2025
26  0331    2025
27  0334    2025
28  0337    2025
29  033A    2025
30  033B    2025
31  0340    2025
32  041A    2025
33  041B    2025
34  0420    2025
35  0430    2025
36  0440    2025
37  0450    2025
38  0451    2021
39  0452    2025
40  0453    2025
41  0454    2025
42  0460    2025
43  0461    2025
44  0462    2025
45  0470    2025
46  0475    2025
47  0479    2025
48  0480    2021
49  0481    2015
50  0482    2025
51  0483    2025
52  0484    2025
53  0485    2025
54  0486    2025
55  0487    2025
56  0488    2025
57  0489    2024
58  0490    2006
59  0492    2005
60  0493    2006
61  0494    2006
62  0495    2025
63  0496    2025
64  0497    2025
65  0498    2025
66  0499    2009
67  0510    2020
68  051A    2025
69  051B    2025
70  0520    2025
71  0530    2025
72  0545    2025
73  0550    2025
74  0551    2025
75  0552    2025
76  0553    2025
77  0554    2025
78  0555    2025
79  0556    2025
80  0557    2025
81  0558    2025
82  0560    2025
83  0580    2025
84  0581    2025
85  0583    2025
86  0584    2025
87  0585    2018
88  0610    2025
89  0620    2025
90  0630    2025
91  0650    2025
92  0710    2025
93  0760    2025
94  0810    2025
95  0820    2025
96  0830    2016
97  0840    2014
98  0841    2014
99  0842    2014
100 0843    2014
101 0850    2025
102 0860    2025
103 0865    2025
104 0870    2025
105 0880    2025
106 0890    2025
107 0895    2025
108 0910    2025
109 0915    2025
110 0917    2025
111 0918    2025
112 0920    2025
113 0925    2025
114 0927    2025
115 0928    2025
116 0930    2025
117 0935    2025
118 0937    2025
119 0938    2025
120 1010    2025
121 1020    2025
122 1025    2025
123 1030    2025
124 1035    2016
125 1050    2025
126 1055    2025
127 1090    2025
128 1101    2025
129 1102    2025
130 1110    2025
131 1120    2025
132 1121    2025
133 1122    2025
134 1130    2025
135 1135    2025
136 1140    2025
137 1145    2025
138 1147    2025
139 1150    2025
140 1151    2025
141 1152    2025
142 1153    2025
143 1154    2025
144 1155    2025
145 1156    2025
146 1160    2018
147 1170    2025
148 1185    2025
149 1187    2025
150 1192    2025
151 1195    2025
152 1197    2025
153 1199    2025
154 1200    2025
155 1205    2025
156 1206    2025
157 1210    2025
158 1220    2025
159 1230    2023
160 1235    2024
161 1240    2025
162 1241    2025
163 1242    2025
164 1245    2025
165 1255    2018
166 1260    2025
167 1261    2025
168 1262    2025
169 1263    2025
170 1265    2024
171 1305    2025
172 1310    2025
173 1320    2025
174 1330    2025
175 1335    2025
176 1340    2025
177 1345    2025
178 1350    2025
179 1360    2025
180 1365    2025
181 1370    2025
182 1375    2025
183 141A    2025
184 141B    2025
185 141C    2025
186 142A    2025
187 142B    2025
188 1435    2025
189 143A    2025
190 143B    2025
191 143C    2025
192 1440    2008
193 1450    2025
194 1460    2025
195 1476    2023
196 1477    2025
197 1478    2025
198 1479    2025
199 1480    2025
200 1481    2025
201 1504    2025
202 1505    2025
203 1506    2025
204 1507    2025
205 1510    2017
206 1511    2020
207 1512    2024
208 1513    2025
209 1515    2023
210 1518    2025
211 1519    2025
212 1520    2025
213 1521    2006
214 1525    2019
215 1526    2018
216 1530    2024
217 1531    2025
218 1535    2025
219 1536    2025
220 1537    2024
221 1540    2025
222 1541    2025
223 1542    2015
224 1544    2025
225 1549    2025
226 1562    2025
227 1563    2025
228 1564    2024
229 1565    2025
230 1566    2025
231 1570    2025
232 1572    2007
233 1573    2025
234 1574    2024
235 1576    2024
236 1577    2025
237 1578    2005
238 1580    2023
239 1581    2025
240 1582    2025
241 1585    2025
242 1590    2025
243 1599    2025
244 1610    2008
245 1611    2012
246 1620    2008
247 1621    2009
248 1622    2008
249 1624    2008
250 1625    2005
251 1626    2009
252 1627    2011
253 1630    2007
254 1631    2011
255 1633    2004
256 1640    2008
257 1650    2008
258 1651    2021
259 1661    2025
260 1670    2024
261 1680    2025
262 1681    2006
263 1682    2022
264 1697    2002
265 1710    2025
266 1715    2024
267 1720    2025
268 1725    2025
269 1726    2025
270 1750    2025
271 1751    2025
272 1752    2025
273 1753    2025
274 1754    2025
275 1755    2025
276 1780    2025
277 1790    2025
278 1791    2025
279 1792    2025
280 1811    2025
281 1812    2025
282 1821    2025
283 1822    2025
284 1840    2025
285 1850    2025
286 1860    2023
287 1900    2025
288 2010    2025
289 2011    2025
290 2012    2025
291 2013    2025
292 2014    2025
293 2015    2025
294 2016    2025
295 2017    2025
296 2018    2025
297 2019    2025
298 2020    2025
299 2021    2025
300 2022    2025
301 2023    2025
302 2024    2025
303 2025    2025
304 2026    2025
305 2027    2025
306 2028    2025
307 2029    2025
308 2030    2024
309 2031    2025
310 2032    2025
311 2033    2025
312 2034    2025
313 2040    2025
314 2050    2025
315 2060    2016
316 2070    2022
317 2080    2024
318 2090    2025
319 2091    2025
320 2092    2025
321 2093    2025
322 2094    2024
323 2095    2025
324 2110    2025
325 2111    2014
326 2120    2007
327 2160    2025
328 2170    2025
329 2210    2025
330 2220    2025
331 2230    2025
332 2240    2023
333 2250    2025
334 2251    2023
335 2820    2025
336 2825    2025
337 2826    2025
338 2830    2025
339 2840    2025
340 2850    2025
341 2851    2025
342 2860    2025
343 2870    2025
344 2890    2025
345 2895    2024
346 2896    2025
347 2900    2025
348 3000    2025
349 3100    2025
350 3200    2025
351 3300    2025
352 3400    2020
353 3610    2024
354 3710    2025
355 3720    2020
356 3730    2025
357 3731    2025
358 3740    2016
359 3750    2025
360 3751    2021
361 3760    2025
362 3770    2016
363 3800    2025
364 3910    2024
365 3920    2025
366 3960    2025
367 3961    2024
368 3966    2022
369 3970    2024
370 3975    2016
371 3980    2019
372 4210    2025
373 4220    2025
374 4230    2025
375 4240    2025
376 4255    2025
377 4310    2025
378 4386    2025
379 4387    2025
380 4388    2025
381 4389    2025
382 4510    2024
383 4625    2025
384 4650    2025
385 4651    2025
386 4652    2025
387 4740    2025
388 4750    2021
389 4800    2025
390 4810    2025
391 4860    2025
392 5000    2025
393 5001    2025
394 5002    2025
395 5003    2025
396 5004    2025
397 5005    2002
398 5007    2025
399 5008    2013
400 5009    2025
401 500E    2025
402 500N    2025
403 5011    2025
404 5013    2025
405 501A    2025
406 501H    2025
407 502P    2025
408 502R    2025
409 502T    2025
410 5073    2018
411 5093    2018
412 5094    2017
413 5110    2025
414 5111    2025
415 5112    2025
416 5113    2017
417 5114    2019
418 5120    2018
419 5121    2024
420 5122    2025
421 5130    2025
422 5131    2025
423 5132    2025
424 9901    2001</code></pre>
</div>
</div>
<p>Now that we have a query that tells us the most recent year for each IUCR code, we should look up what the <code>PrimaryType</code> and <code>FBICode</code> are for each <code>IUCR</code> in its most recent year. We are going to temporarily create a table with the results from the previous query using “Common Table Expressions” (CTE). A CTE is a temporary table that only lasts for the one query in which it is created. You can have multiple CTEs in one query. Also, here we have our first encounter with a <code>JOIN</code>. We will cover more about <code>JOIN</code> later in these notes. For now, study the query and see how it solves our problem. With a CTE (the part following the keyword <code>WITH</code>) we create a temporary table called <code>recentIUCR</code> that has two columns, <code>IUCR</code> and <code>maxyear</code>. Then the main query looks for rows in the <code>crime</code> table that match the rows in <code>recentIUCR</code>. When it finds a match, it merges in that crime’s <code>PrimaryType</code> and <code>FBICode.</code> Since many crimes with the same value of <code>IUCR</code> show up, we use <code>DISTINCT</code> to keep just the unique combinations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>iucrLookupTable <span class="ot">&lt;-</span> <span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="st">  WITH</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="st">     recentIUCR AS</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="st">        (SELECT IUCR, MAX(year) AS maxyear</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="st">         FROM crime</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="st">         GROUP BY IUCR)</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="st">  SELECT DISTINCT crime.IUCR, </span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="st">                  crime.PrimaryType, </span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="st">                  crime.FBICode</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="st">  FROM crime</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a><span class="st">  INNER JOIN recentIUCR</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a><span class="st">      ON crime.iucr = recentIUCR.iucr AND</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a><span class="st">         crime.year = recentIUCR.maxyear</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a><span class="st">  ORDER BY crime.IUCR</span></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a><span class="st">"</span>)</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a><span class="co"># check for a few IUCRs</span></span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>iucrLookupTable <span class="sc">|&gt;</span> </span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>   <span class="fu">filter</span>(IUCR <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">2091</span>,<span class="dv">2092</span>,<span class="dv">2093</span>,<span class="dv">1030</span>,<span class="dv">1035</span>,<span class="dv">5114</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  IUCR  PrimaryType FBICode
1 1030        ARSON      09
2 1035        ARSON      09
3 2091    NARCOTICS      18
4 2092    NARCOTICS      18
5 2093    NARCOTICS      18
6 5114 NON-CRIMINAL      26</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># make sure that each IUCR code shows up in only one row</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co">#   should be empty</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>iucrLookupTable <span class="sc">|&gt;</span> </span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>   <span class="fu">count</span>(IUCR) <span class="sc">|&gt;</span> </span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>   <span class="fu">filter</span>(n <span class="sc">&gt;</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] IUCR n   
&lt;0 rows&gt; (or 0-length row.names)</code></pre>
</div>
</div>
<p>With questions about IUCR to FBI codes resolved, let’s create the IUCR, primary type, and FBI code lookup table in our Chicago crime database. We can use <code>dbWriteTable()</code> to post our data frame <code>iucrLookupTable</code> to the database, creating a new table called <code>iucr</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># remove iucr table if it is there already</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="fu">dbExistsTable</span>(con,<span class="st">"iucr"</span>)) <span class="fu">dbRemoveTable</span>(con, <span class="st">"iucr"</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co"># import the data frame into SQLite</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="fu">dbWriteTable</span>(con, <span class="st">"iucr"</span>, iucrLookupTable,</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">row.names=</span><span class="cn">FALSE</span>)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="co"># check</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="fu">dbListFields</span>(con,<span class="st">"iucr"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "IUCR"        "PrimaryType" "FBICode"    </code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check whether the table looks correct</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, <span class="st">"SELECT * FROM iucr LIMIT 5"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  IUCR             PrimaryType FBICode
1 0110                HOMICIDE     01A
2 0130                HOMICIDE     01A
3 0141                HOMICIDE     01B
4 0142                HOMICIDE     01B
5 0261 CRIMINAL SEXUAL ASSAULT      02</code></pre>
</div>
</div>
<p>Everything looks correct!</p>
<p>Note that we ran a SQL query to pull this lookup table into <code>iucrLookupTable</code>, then we wrote that table back to the database with <code>dbWriteTable()</code>. There really was no need to pull the table into R, only to post it right back into the database. We can use a <code>CREATE TABLE</code> clause to create this lookup table directly in our database.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># remove iucr table if it is there already</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="fu">dbExistsTable</span>(con,<span class="st">"iucr"</span>)) <span class="fu">dbRemoveTable</span>(con, <span class="st">"iucr"</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># use dbExecute() since we are creating a table, not retrieving data</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="fu">dbExecute</span>(con, <span class="st">"</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="st">  CREATE TABLE iucr AS</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="st">  WITH</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="st">     recentIUCR AS</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a><span class="st">        (SELECT IUCR, MAX(year) AS maxyear</span></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a><span class="st">         FROM crime</span></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a><span class="st">         GROUP BY IUCR)</span></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a><span class="st">  SELECT DISTINCT crime.IUCR, crime.PrimaryType, crime.FBICode</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a><span class="st">  FROM crime</span></span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a><span class="st">  INNER JOIN recentIUCR</span></span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a><span class="st">      ON crime.iucr = recentIUCR.iucr AND</span></span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a><span class="st">         crime.year = recentIUCR.maxyear</span></span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a><span class="st">  ORDER BY crime.IUCR</span></span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>We now see that our database has two tables, the original <code>crime</code> table and the new <code>iucr</code> lookup table.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbListTables</span>(con)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "crime" "iucr" </code></pre>
</div>
</div>
<section id="exercises" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="exercises"><span class="header-section-number">1.1</span> Exercises</h2>
<p>With the new table <code>iucr</code> in the database, complete the following exercises.</p>
<ol type="1">
<li><p>Print out all of the rows in iucr</p></li>
<li><p>Print out all the IUCR codes for “KIDNAPPING”</p></li>
<li><p>How many IUCR codes are there for “ASSAULT”?</p></li>
<li><p>Try doing the prior exercise again using <code>COUNT(*)</code> if you did not use it the first time</p></li>
</ol>
</section>
</section>
<section id="sql-dates" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> SQL dates</h1>
<p>SQLite has no special date/time data type. The <code>Date</code> column is currently stored in the <code>crime</code> table as plain text. The <code>PRAGMA</code> statement is a way to modify or query the SQLite database itself. Here we can ask SQLite the data types it is using to store each of the columns. All the entries, including <code>Date</code>, are stored as text, integers, or doubles (numbers with decimal points).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, <span class="st">"PRAGMA table_info(crime)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   cid                name   type notnull dflt_value pk
1    0                  ID    INT       0         NA  0
2    1          CaseNumber   TEXT       0         NA  0
3    2                Date   TEXT       0         NA  0
4    3               Block   TEXT       0         NA  0
5    4                IUCR   TEXT       0         NA  0
6    5         PrimaryType   TEXT       0         NA  0
7    6         Description   TEXT       0         NA  0
8    7 LocationDescription   TEXT       0         NA  0
9    8              Arrest   TEXT       0         NA  0
10   9            Domestic   TEXT       0         NA  0
11  10                Beat    INT       0         NA  0
12  11            District   TEXT       0         NA  0
13  12                Ward   TEXT       0         NA  0
14  13       CommunityArea   TEXT       0         NA  0
15  14             FBICode   TEXT       0         NA  0
16  15         XCoordinate    INT       0         NA  0
17  16         YCoordinate    INT       0         NA  0
18  17                Year    INT       0         NA  0
19  18           UpdatedOn   TEXT       0         NA  0
20  19            Latitude DOUBLE       0         NA  0
21  20           Longitude DOUBLE       0         NA  0
22  21            Location   TEXT       0         NA  0</code></pre>
</div>
</div>
<p>The standard date format in computing is yyyy-mm-dd hh:mm:ss, where the hours are on the 24-hour clock (so no AM/PM). The reason for this format is that you can sort the data in this format to get events in order. For some reason, the producers of the Chicago crime dataset did not use this standard format. If you sort events in the current database, then all the January events will come first (regardless of the year in which they occurred) and any events occurring at 1pm will show up before those occurring at 2am. Putting the dates in a standard format also allows us to use some useful SQLite date functions for extracting the year, day of the week, time of day, and other features of the date and time.</p>
<p>The plan is to create a data frame in R with each crime’s <code>ID</code> and <code>Date</code>. Then we will use <code>lubridate</code> to clean up the dates and put them in the standard format. Then we will push a new table into the database containing each crime’s <code>ID</code> and its newly formatted date.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">dbGetQuery</span>(con, <span class="st">"SELECT ID, Date FROM crime"</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>data <span class="sc">|&gt;</span> <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        ID                   Date
1 13311263 07/29/2022 03:39:00 AM
2 13053066 01/03/2023 04:44:00 PM
3 12131221 08/10/2020 09:45:00 AM
4 11227634 08/26/2017 10:00:00 AM
5 13203321 09/06/2023 05:00:00 PM
6 13204489 09/06/2023 11:00:00 AM</code></pre>
</div>
</div>
<p>Since the dates are in mm/dd/yyyy hh:mm:ss format, we will use <code>mdy_hms()</code> from the <code>lubridate</code> package to clean these up. Fortunately, this function can also handle the AM/PM.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">mutate</span>(<span class="at">datefix =</span> <span class="fu">mdy_hms</span>(Date),</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">datefix =</span> <span class="fu">as.character</span>(datefix)) <span class="sc">|&gt;</span> <span class="co"># convert to plain text</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>   <span class="co"># delete the original date from the data frame</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>   <span class="fu">select</span>(<span class="sc">-</span>Date)</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a><span class="co"># check that the reformatting worked</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>data <span class="sc">|&gt;</span> <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        ID             datefix
1 13311263 2022-07-29 03:39:00
2 13053066 2023-01-03 16:44:00
3 12131221 2020-08-10 09:45:00
4 11227634 2017-08-26 10:00:00
5 13203321 2023-09-06 17:00:00
6 13204489 2023-09-06 11:00:00</code></pre>
</div>
</div>
<p>With the dates in standard format, let’s push the fixed dates table to the database.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># remove DateFix table if it already exists</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="fu">dbExistsTable</span>(con,<span class="st">"DateFix"</span>)) <span class="fu">dbRemoveTable</span>(con, <span class="st">"DateFix"</span>)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="co"># save a table with ID and the properly formatted date</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="fu">dbWriteTable</span>(con, <span class="st">"DateFix"</span>, data, <span class="at">row.names=</span><span class="cn">FALSE</span>)</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="fu">dbListTables</span>(con)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "DateFix" "crime"   "iucr"   </code></pre>
</div>
</div>
<p>Our database now has three tables with the addition of the new <code>DateFix</code> table.</p>
<p>Before we used <code>SUBSTR()</code> to extract the year from the date. That was not very elegant and required figuring out which characters held the four characters representing the year. Even though SQLite does not have a date/time type, it does have some functions that help us work with dates. We will use SQLite’s <code>STRFTIME()</code> function. It stands for “string format time”. It is a decades-old function that you will find in almost all languages. Even R has its own version of <code>strftime()</code>. Early programming language compilers limited functions to at most eight characters, so programmers got rather creative in shrinking complicated function descriptions down to eight characters.</p>
<p>The <code>STRFTIME()</code> function has two primary arguments (and some optional <a href="https://sqlite.org/lang_datefunc.html#modifiers">modifiers</a>). The first is a format parameter in which you tell <code>STRFTIME()</code> what you want it to extract from the date. The second argument is the column containing the dates. There are a lot of options for the format parameter. For example, you can extract just the year (%Y), just the month (%m), just the minute (%M), the day of the week (%w) with Sunday represented as 0 and Saturday as 6, or the week of the year (%W). You can also combine to get, for example, the year and month (%Y-%m). You can find a complete listing <a href="https://www.sqlite.org/lang_datefunc.html">here</a>.</p>
<p>Let’s write a query to test out <code>STRFTIME()</code>. Here we will select some dates from <code>DateFix</code> and determine on which day of the week the crime occurred.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="st">  SELECT ID,</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="st">         datefix,</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="st">         STRFTIME('%w',datefix) AS weekday</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="st">  FROM DateFix"</span>)</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>a <span class="sc">|&gt;</span> <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        ID             datefix weekday
1 13311263 2022-07-29 03:39:00       5
2 13053066 2023-01-03 16:44:00       2
3 12131221 2020-08-10 09:45:00       1
4 11227634 2017-08-26 10:00:00       6
5 13203321 2023-09-06 17:00:00       3
6 13204489 2023-09-06 11:00:00       3</code></pre>
</div>
</div>
<p>For the first date, 2022-07-29, <code>STRFTIME()</code> tells us that this was day 5 of the week, which is Friday (remember that 0 is Sunday).</p>
<p><code>STRFTIME()</code> always returns values that are text. That is, if you ask for the year using <code>STRFTIME('%Y',datefix)</code> and you get values like 2017 and 2018, your results will be character strings rather than numeric. You will have to convert them using <code>as.numeric()</code> in R or, preferably, using a <code>CAST()</code> expression in SQL. <code>CAST()</code> is particularly useful if you want to select records that, say, occur after 2010 or after noon.</p>
<p>Let’s count cases that occurred between Monday and Friday after noon.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="st">  SELECT COUNT(*) as crimecount,</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="st">         CAST(STRFTIME('%w',datefix) AS INTEGER) AS weekday</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="st">  FROM DateFix</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="st">  WHERE (weekday&gt;=1) AND (weekday&lt;=5) AND</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a><span class="st">        (CAST(STRFTIME('%H',datefix) AS INTEGER) &gt;= 12)</span></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="st">  GROUP BY weekday"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  crimecount weekday
1     746915       1
2     768661       2
3     774035       3
4     760030       4
5     810449       5</code></pre>
</div>
</div>
<p>In the <code>SELECT</code> clause, we told SQLite to store the weekday as an integer. In the <code>WHERE</code> clause we extracted the hour (24-hour clock) so that we could make a numerical comparison with the number 12.</p>
</section>
<section id="creating-the-final-table" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Creating the final table</h1>
<p>Now we can put it all together, drop columns we do not want, remove redundant information, and clean up the dates.</p>
<p>Removing columns from tables in SQLite used to not be simple. Only after March 2021 could you run <code>ALTER TABLE crime DROP COLUMN Date</code> to remove a single column. We are going to use an old-school approach since we are going to make many changes to our database. We are going to rename the current <code>crime</code> table, then copy only the columns we want into a new <code>crime</code> table, while at the same time replacing the old format dates with dates in a more preferable format.</p>
<p>First, rename the <code>crime</code> table to <code>crime_old</code>, which we will delete as soon as we are done.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbExecute</span>(con, <span class="st">"ALTER TABLE crime RENAME TO crime_old"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>There should be a new table.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbListTables</span>(con)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "DateFix"   "crime_old" "iucr"     </code></pre>
</div>
</div>
<p>This will create our new <code>crime</code> table. It can take a few minutes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbExecute</span>(con, <span class="st">"</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="st">   CREATE TABLE crime AS</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="st">   SELECT crime_old.ID,</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="st">          crime_old.CaseNumber,</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a><span class="st">          DateFix.datefix AS date,</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a><span class="st">          crime_old.Block,</span></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a><span class="st">          crime_old.IUCR,</span></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a><span class="st">          crime_old.Description,</span></span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a><span class="st">          crime_old.LocationDescription,</span></span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a><span class="st">          crime_old.Arrest,</span></span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a><span class="st">          crime_old.Domestic,</span></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a><span class="st">          crime_old.Beat,</span></span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a><span class="st">          crime_old.District,</span></span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a><span class="st">          crime_old.Ward,</span></span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a><span class="st">          crime_old.CommunityArea,</span></span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a><span class="st">          crime_old.Latitude,</span></span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a><span class="st">          crime_old.Longitude</span></span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a><span class="st">   FROM crime_old</span></span>
<span id="cb47-19"><a href="#cb47-19" aria-hidden="true" tabindex="-1"></a><span class="st">      INNER JOIN DateFix</span></span>
<span id="cb47-20"><a href="#cb47-20" aria-hidden="true" tabindex="-1"></a><span class="st">        ON crime_old.ID=DateFix.ID"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>This query requires a bit of discussion. First, note that the <code>FROM</code> clause joins two tables, <code>crime_old</code> and <code>DateFix</code>. The <code>ON</code> clause tells SQLite how to link these two tables together. It says that if there is a row in <code>crime_old</code> with a particular <code>ID</code>, then it can find its associated row in the <code>DateFix</code> table by finding the matching value in the <code>DateFix</code>’s <code>ID</code> column. For every column in the <code>SELECT</code> clause, we have included the table from where SQLite should find the column. Technically, we only need to prefix the column with the table name when there might be confusion. For example, both <code>crime_old</code> and <code>DateFix</code> have a column called <code>ID</code>. However, we like to be explicit in complicated queries to remind ourselves from where all the data comes.</p>
<p>You can also see in this <code>SELECT</code> query why periods in column names cause problems. SQL uses the period to separate the table name from the column name. If we were to include <code>Case.Number</code> in a <code>SELECT</code> statement, then SQL would think we had a table called <code>Case</code> with a column called <code>Number</code>. Are you not glad we fixed this way back when we first created our database? When we were cleaning up the Chicago crime CSV file we ran this code on the first line in the CSV file.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">readLines</span>(infile, <span class="at">n=</span><span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">gsub</span>(<span class="st">","</span>, <span class="st">";"</span>, <span class="at">x=</span>_) <span class="sc">|&gt;</span> <span class="co"># separate with ;</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>   <span class="fu">gsub</span>(<span class="st">" "</span>, <span class="st">""</span>, <span class="at">x=</span>_)  <span class="sc">|&gt;</span> <span class="co"># SQL doesn't like field names with .,-,space</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>   <span class="fu">writeLines</span>(<span class="at">con=</span>outfile)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>R typically renames column names with spaces by replacing the spaces with periods. Right at the beginning we deleted any spaces in column names so that we get <code>CaseNumber</code> instead of <code>Case Number</code> or <code>Case.Number</code>.</p>
<p>Technically, <code>Beat</code>, <code>District</code>, <code>Ward</code>, and <code>CommunityArea</code> are all redundant information once we have <code>Latitude</code> and <code>Longitude</code>. However, “spatial joins,” linking coordinates to spatial areas, is computationally expensive so that it is more efficient to simply leave this redundant information here. Lastly, note that the first line is a <code>CREATE TABLE</code> statement that will store the results of this query in a new table called <code>crime</code>.</p>
<p>Let’s look at the newly cleaned up table.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="st">  SELECT *</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="st">  FROM crime</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a><span class="st">  LIMIT 10"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         ID CaseNumber                date                   Block IUCR
1  13311263   JG503434 2022-07-29 03:39:00         023XX S TROY ST 1582
2  13053066   JG103252 2023-01-03 16:44:00 039XX W WASHINGTON BLVD 2017
3  12131221   JD327000 2020-08-10 09:45:00       015XX N DAMEN AVE 0326
4  11227634   JB147599 2017-08-26 10:00:00     001XX W RANDOLPH ST 0281
5  13203321   JG415333 2023-09-06 17:00:00        002XX N Wells st 1320
6  13204489   JG416325 2023-09-06 11:00:00          0000X E 8TH ST 0810
7  11695116   JC272771 2019-05-21 08:20:00  018XX S CALIFORNIA AVE 0620
8  12419690   JE295655 2021-07-07 10:30:00   132XX S GREENWOOD AVE 1544
9  12729745   JF279458 2022-06-14 14:47:00     035XX N CENTRAL AVE 0340
10 12835559   JF406130 2022-09-21 22:00:00         004XX E 69TH ST 0910
                      Description                    LocationDescription Arrest
1               CHILD PORNOGRAPHY                              RESIDENCE   true
2   MANUFACTURE / DELIVER - CRACK                               SIDEWALK   true
3  AGGRAVATED VEHICULAR HIJACKING                                 STREET   true
4                  NON-AGGRAVATED                            HOTEL/MOTEL  false
5                      TO VEHICLE PARKING LOT / GARAGE (NON RESIDENTIAL)  false
6                       OVER $500 PARKING LOT / GARAGE (NON RESIDENTIAL)  false
7                  UNLAWFUL ENTRY                              RESIDENCE  false
8  SEXUAL EXPLOITATION OF A CHILD                              RESIDENCE  false
9  ATTEMPT STRONG ARM - NO WEAPON                                   BANK   true
10                     AUTOMOBILE                        OTHER (SPECIFY)   true
   Domestic Beat District Ward CommunityArea Latitude Longitude
1     false 1033      010   25            30       NA        NA
2     false 1122      011   28            26       NA        NA
3     false 1424      014    1            24 41.90842 -87.67741
4     false  122      001   42            32       NA        NA
5     false  122      001   42            32 41.88602 -87.63394
6     false  123      001    4            32 41.87183 -87.62615
7     false 1023      010   25            29 41.85655 -87.69560
8     false  533      005   10            54 41.65512 -87.59488
9     false 1633      016   30            15 41.94523 -87.76673
10    false  322      003    6            69 41.76935 -87.61501</code></pre>
</div>
</div>
<p>Note that the dates are formatted properly and both <code>PrimaryType</code> and <code>FBICode</code> have been eliminated from the table. If everything looks as expected, then we can delete the <code>crime_old</code> and the <code>DateFix</code> tables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbExecute</span>(con, <span class="st">"DROP TABLE crime_old"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbExecute</span>(con, <span class="st">"DROP TABLE DateFix"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbListTables</span>(con)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "crime" "iucr" </code></pre>
</div>
</div>
<p>After all this work, the size of the <code>chicagocrime.db</code> database file can become quite large. Our database file is now 3.4 Gb, much larger than the size of the file we downloaded from the City of Chicago open data site. Even though we have deleted the <code>crime_old</code> and <code>DateFix</code> tables, SQLite simply marks them as deleted, but does not necessarily give up the space that it had allocated for their storage. It holds onto that space in case the user needs it. The <code>VACUUM</code> statement will clean up unused space, but it can take a minute.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbExecute</span>(con, <span class="st">"VACUUM"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>After <code>VACUUM</code>, our <code>chicagocrime.db</code> file is now 1.2 Gb… much better.</p>
</section>
<section id="joining-data-across-tables" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Joining data across tables</h1>
<p>Now that data are split across tables, we need to link tables together to get information. Let’s extract the first 10 crime incidents with their case numbers and FBI codes. Since <code>FBICode</code> is no longer in the <code>crime</code> table, we need to add the table <code>iucr</code> to the <code>FROM</code> clause and link the two tables with a <code>JOIN</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>timeIUCRjoin <span class="ot">&lt;-</span> </span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">system.time</span>(</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>   data <span class="ot">&lt;-</span> <span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a><span class="st">       SELECT crime.CaseNumber,</span></span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a><span class="st">              iucr.FBICode</span></span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a><span class="st">       FROM   crime</span></span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a><span class="st">         INNER JOIN iucr</span></span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a><span class="st">           ON crime.iucr=iucr.iucr"</span>)</span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a>data <span class="sc">|&gt;</span> <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  CaseNumber FBICode
1   JG503434      17
2   JG103252      18
3   JD327000      03
4   JB147599      02
5   JG415333      14
6   JG416325      06</code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>timeIUCRjoin</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   user  system elapsed 
  10.43    1.78   12.48 </code></pre>
</div>
</div>
<p>For each record in <code>crime</code>, SQLite looks up the crime’s IUCR code in the <code>iucr</code> table and links in the FBI code. SQLite is fast. This query took 12.48 seconds, but this linking does take time, especially for really large datasets and large lookup tables. For the above query, SQLite scans through the <code>iucr</code> table until it finds the right IUCR code. This is not very efficient. If you were to look up the word “query” in the dictionary, you would not start on page 1 and scan through every word until you arrived at “query”. Instead, you would start about two-thirds of the way through the dictionary, see if the words are before or after “query,” and revise your search until you find the word. Rather than search hundreds of pages, you might only need to look at nine pages.</p>
<p>In the same way, we can create an index for the <code>iucr</code> table to help speed up the search. An index does not always make queries faster and can require storing a large index in some cases. Let’s try this example.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbExecute</span>(con, <span class="st">"</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="st">   CREATE INDEX iucr_idx on iucr(iucr)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>Let’s rerun the query now and see if it made a difference.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>timeIUCRjoinIndex <span class="ot">&lt;-</span> </span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">system.time</span>(</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>   data <span class="ot">&lt;-</span> <span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a><span class="st">       SELECT crime.CaseNumber,</span></span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a><span class="st">              iucr.FBICode</span></span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a><span class="st">       FROM   crime</span></span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a><span class="st">         INNER JOIN iucr</span></span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a><span class="st">           ON crime.iucr=iucr.iucr"</span>)</span>
<span id="cb66-10"><a href="#cb66-10" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb66-11"><a href="#cb66-11" aria-hidden="true" tabindex="-1"></a>timeIUCRjoinIndex</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   user  system elapsed 
   7.50    1.45    8.97 </code></pre>
</div>
</div>
<p>That query now takes 8.97 seconds. Creating an index is not always worth it. If you have queries that are taking too long, it is worth experimenting with creating an index to see if it helps.</p>
<p>You may come across SQL queries that join two tables with a <code>WHERE</code> clause like this.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="st">    SELECT crime.CaseNumber,</span></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a><span class="st">           iucr.FBICode</span></span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a><span class="st">    FROM crime, iucr</span></span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a><span class="st">    WHERE crime.iucr=iucr.iucr"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Technically this is a legal SQL join query. However, most SQL programmers prefer using <code>JOIN</code> rather than using the <code>WHERE</code> clause. The primary reason is readability. The thinking is that the <code>WHERE</code> clause should really be about filtering which cases to include, while joining tables is quite a different operation.</p>
<p>There are also several different kinds of joins. What should the query return if a crime has an IUCR code that does not appear in the <code>iucr</code> table? <code>JOIN</code>s more carefully define the desired behavior. An <code>INNER JOIN</code> returns only the rows where the join keys (the columns we use to link tables like <code>crime.iucr</code>) exist in both tables. All other rows are dropped. SQL interprets joins using the WHERE clause implicitly as an <code>INNER JOIN</code>.</p>
<p>Generally, in social science, we do not want to drop a row simply because its IUCR code does not appear in the lookup table. We would probably rather code its <code>PrimaryType</code> and <code>FBICode</code> as missing rather than drop the row. A <code>LEFT JOIN</code> forces every record in <code>crime</code> (the “left” table) to appear in the final result set even if it cannot find an IUCR code in <code>iucr</code>. It will simply report <code>NA</code> for its <code>FBICode</code>. More precisely, <code>LEFT JOIN</code> is synonymous with a <code>LEFT OUTER JOIN</code> (the <code>OUTER</code> keyword is optional).</p>
<p>For a helpful, visual description of the different kinds of joins, visit <a href="http://blog.codinghorror.com/a-visual-explanation-of-sql-joins/">this site</a>.</p>
<p>Let’s determine how many assaults occurred in each ward. Since the crime type is stored in <code>iucr.PrimaryType</code>, we need to join the tables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="st">    SELECT COUNT(*) AS crimecount,</span></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a><span class="st">           crime.Ward</span></span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a><span class="st">    -- Use LEFT JOIN to link the two tables </span></span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a><span class="st">    FROM crime</span></span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a><span class="st">       LEFT JOIN iucr</span></span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a><span class="st">          ON crime.iucr=iucr.iucr</span></span>
<span id="cb69-8"><a href="#cb69-8" aria-hidden="true" tabindex="-1"></a><span class="st">    -- Use WHERE to filter cases we want</span></span>
<span id="cb69-9"><a href="#cb69-9" aria-hidden="true" tabindex="-1"></a><span class="st">    WHERE iucr.PrimaryType='ASSAULT'</span></span>
<span id="cb69-10"><a href="#cb69-10" aria-hidden="true" tabindex="-1"></a><span class="st">    GROUP BY crime.Ward"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   crimecount Ward
1       39807     
2        7395    1
3       12065   10
4        7413   11
5        6520   12
6        5472   13
7        6540   14
8       14872   15
9       17957   16
10      21168   17
11       9332   18
12       4580   19
13      14607    2
14      20353   20
15      17680   21
16       6657   22
17       5659   23
18      20247   24
19       8053   25
20       9471   26
21      16997   27
22      23558   28
23      13488   29
24      17378    3
25       6628   30
26       6725   31
27       4245   32
28       4462   33
29      17117   34
30       6461   35
31       5242   36
32      14383   37
33       4641   38
34       4138   39
35      11962    4
36       5003   40
37       3974   41
38      12144   42
39       2859   43
40       4000   44
41       4712   45
42       6840   46
43       3556   47
44       5230   48
45       7106   49
46      13812    5
47       4561   50
48      20364    6
49      17963    7
50      18017    8
51      17820    9</code></pre>
</div>
</div>
<p>Let’s tabulate how many Part 1 crimes occur in each year. We will use <code>PrimaryType</code> to give useful labels, <code>STRFTIME()</code> to extract the year in which each crime occurred, <code>FBICode</code> to pick out the Part 1 crimes, and a <code>LEFT JOIN</code> to link the tables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="st">   SELECT iucr.PrimaryType           AS type,</span></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a><span class="st">          STRFTIME('%Y', crime.date) AS year,</span></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a><span class="st">          COUNT(*)                   AS crimecount</span></span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a><span class="st">   FROM crime</span></span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a><span class="st">     INNER JOIN iucr</span></span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a><span class="st">       ON crime.iucr=iucr.iucr</span></span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a><span class="st">   WHERE iucr.FBICode IN ('01A','02','03','04A','04B','05','06','07','09')</span></span>
<span id="cb71-9"><a href="#cb71-9" aria-hidden="true" tabindex="-1"></a><span class="st">   GROUP BY type, year"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          type year crimecount
1                        ARSON 2001       1011
2                        ARSON 2002       1032
3                        ARSON 2003        955
4                        ARSON 2004        778
5                        ARSON 2005        691
6                        ARSON 2006        726
7                        ARSON 2007        712
8                        ARSON 2008        644
9                        ARSON 2009        616
10                       ARSON 2010        522
11                       ARSON 2011        504
12                       ARSON 2012        469
13                       ARSON 2013        364
14                       ARSON 2014        397
15                       ARSON 2015        453
16                       ARSON 2016        516
17                       ARSON 2017        444
18                       ARSON 2018        373
19                       ARSON 2019        376
20                       ARSON 2020        588
21                       ARSON 2021        530
22                       ARSON 2022        422
23                       ARSON 2023        513
24                       ARSON 2024        482
25                       ARSON 2025        250
26                     ASSAULT 2001       7871
27                     ASSAULT 2002       7721
28                     ASSAULT 2003       7372
29                     ASSAULT 2004       7331
30                     ASSAULT 2005       6754
31                     ASSAULT 2006       6597
32                     ASSAULT 2007       6335
33                     ASSAULT 2008       6250
34                     ASSAULT 2009       6000
35                     ASSAULT 2010       5278
36                     ASSAULT 2011       5157
37                     ASSAULT 2012       4873
38                     ASSAULT 2013       4268
39                     ASSAULT 2014       4337
40                     ASSAULT 2015       4480
41                     ASSAULT 2016       5713
42                     ASSAULT 2017       5793
43                     ASSAULT 2018       6002
44                     ASSAULT 2019       5842
45                     ASSAULT 2020       6265
46                     ASSAULT 2021       7242
47                     ASSAULT 2022       7281
48                     ASSAULT 2023       7712
49                     ASSAULT 2024       7905
50                     ASSAULT 2025       4345
51                     BATTERY 2001      16388
52                     BATTERY 2002      15196
53                     BATTERY 2003      12477
54                     BATTERY 2004      11529
55                     BATTERY 2005      11327
56                     BATTERY 2006      11001
57                     BATTERY 2007      11153
58                     BATTERY 2008      10805
59                     BATTERY 2009      10142
60                     BATTERY 2010       9432
61                     BATTERY 2011       8402
62                     BATTERY 2012       8005
63                     BATTERY 2013       6634
64                     BATTERY 2014       6577
65                     BATTERY 2015       7018
66                     BATTERY 2016       8085
67                     BATTERY 2017       7845
68                     BATTERY 2018       7734
69                     BATTERY 2019       7858
70                     BATTERY 2020       8319
71                     BATTERY 2021       8346
72                     BATTERY 2022       7495
73                     BATTERY 2023       8080
74                     BATTERY 2024       8182
75                     BATTERY 2025       4597
76                    BURGLARY 2001      26014
77                    BURGLARY 2002      25623
78                    BURGLARY 2003      25157
79                    BURGLARY 2004      24564
80                    BURGLARY 2005      25503
81                    BURGLARY 2006      24324
82                    BURGLARY 2007      24858
83                    BURGLARY 2008      26218
84                    BURGLARY 2009      26767
85                    BURGLARY 2010      26422
86                    BURGLARY 2011      26620
87                    BURGLARY 2012      22844
88                    BURGLARY 2013      17894
89                    BURGLARY 2014      14569
90                    BURGLARY 2015      13184
91                    BURGLARY 2016      14289
92                    BURGLARY 2017      13001
93                    BURGLARY 2018      11747
94                    BURGLARY 2019       9639
95                    BURGLARY 2020       8758
96                    BURGLARY 2021       6661
97                    BURGLARY 2022       7594
98                    BURGLARY 2023       7486
99                    BURGLARY 2024       8425
100                   BURGLARY 2025       5679
101    CRIMINAL SEXUAL ASSAULT 2001       1814
102    CRIMINAL SEXUAL ASSAULT 2002       1839
103    CRIMINAL SEXUAL ASSAULT 2003       1617
104    CRIMINAL SEXUAL ASSAULT 2004       1583
105    CRIMINAL SEXUAL ASSAULT 2005       1562
106    CRIMINAL SEXUAL ASSAULT 2006       1488
107    CRIMINAL SEXUAL ASSAULT 2007       1565
108    CRIMINAL SEXUAL ASSAULT 2008       1566
109    CRIMINAL SEXUAL ASSAULT 2009       1450
110    CRIMINAL SEXUAL ASSAULT 2010       1397
111    CRIMINAL SEXUAL ASSAULT 2011       1516
112    CRIMINAL SEXUAL ASSAULT 2012       1468
113    CRIMINAL SEXUAL ASSAULT 2013       1355
114    CRIMINAL SEXUAL ASSAULT 2014       1398
115    CRIMINAL SEXUAL ASSAULT 2015       1461
116    CRIMINAL SEXUAL ASSAULT 2016       1627
117    CRIMINAL SEXUAL ASSAULT 2017       1697
118    CRIMINAL SEXUAL ASSAULT 2018       1742
119    CRIMINAL SEXUAL ASSAULT 2019       1673
120    CRIMINAL SEXUAL ASSAULT 2020       1255
121    CRIMINAL SEXUAL ASSAULT 2021       1530
122    CRIMINAL SEXUAL ASSAULT 2022       1606
123    CRIMINAL SEXUAL ASSAULT 2023       1668
124    CRIMINAL SEXUAL ASSAULT 2024       1598
125    CRIMINAL SEXUAL ASSAULT 2025       1041
126                   HOMICIDE 2001        667
127                   HOMICIDE 2002        657
128                   HOMICIDE 2003        601
129                   HOMICIDE 2004        454
130                   HOMICIDE 2005        451
131                   HOMICIDE 2006        472
132                   HOMICIDE 2007        448
133                   HOMICIDE 2008        513
134                   HOMICIDE 2009        461
135                   HOMICIDE 2010        438
136                   HOMICIDE 2011        437
137                   HOMICIDE 2012        514
138                   HOMICIDE 2013        430
139                   HOMICIDE 2014        427
140                   HOMICIDE 2015        496
141                   HOMICIDE 2016        786
142                   HOMICIDE 2017        672
143                   HOMICIDE 2018        588
144                   HOMICIDE 2019        499
145                   HOMICIDE 2020        787
146                   HOMICIDE 2021        806
147                   HOMICIDE 2022        730
148                   HOMICIDE 2023        632
149                   HOMICIDE 2024        589
150                   HOMICIDE 2025        264
151        MOTOR VEHICLE THEFT 2001      27555
152        MOTOR VEHICLE THEFT 2002      25121
153        MOTOR VEHICLE THEFT 2003      22749
154        MOTOR VEHICLE THEFT 2004      22805
155        MOTOR VEHICLE THEFT 2005      22497
156        MOTOR VEHICLE THEFT 2006      21818
157        MOTOR VEHICLE THEFT 2007      18573
158        MOTOR VEHICLE THEFT 2008      18881
159        MOTOR VEHICLE THEFT 2009      15482
160        MOTOR VEHICLE THEFT 2010      19029
161        MOTOR VEHICLE THEFT 2011      19388
162        MOTOR VEHICLE THEFT 2012      16490
163        MOTOR VEHICLE THEFT 2013      12582
164        MOTOR VEHICLE THEFT 2014       9911
165        MOTOR VEHICLE THEFT 2015      10068
166        MOTOR VEHICLE THEFT 2016      11285
167        MOTOR VEHICLE THEFT 2017      11380
168        MOTOR VEHICLE THEFT 2018       9985
169        MOTOR VEHICLE THEFT 2019       8978
170        MOTOR VEHICLE THEFT 2020       9962
171        MOTOR VEHICLE THEFT 2021      10605
172        MOTOR VEHICLE THEFT 2022      21472
173        MOTOR VEHICLE THEFT 2023      29253
174        MOTOR VEHICLE THEFT 2024      21709
175        MOTOR VEHICLE THEFT 2025      10731
176 OFFENSE INVOLVING CHILDREN 2001        380
177 OFFENSE INVOLVING CHILDREN 2002        383
178 OFFENSE INVOLVING CHILDREN 2003        386
179 OFFENSE INVOLVING CHILDREN 2004        366
180 OFFENSE INVOLVING CHILDREN 2005        354
181 OFFENSE INVOLVING CHILDREN 2006        327
182 OFFENSE INVOLVING CHILDREN 2007        318
183 OFFENSE INVOLVING CHILDREN 2008        239
184 OFFENSE INVOLVING CHILDREN 2009        248
185 OFFENSE INVOLVING CHILDREN 2010        244
186 OFFENSE INVOLVING CHILDREN 2011        221
187 OFFENSE INVOLVING CHILDREN 2012        233
188 OFFENSE INVOLVING CHILDREN 2013        218
189 OFFENSE INVOLVING CHILDREN 2014        239
190 OFFENSE INVOLVING CHILDREN 2015        253
191 OFFENSE INVOLVING CHILDREN 2016        244
192 OFFENSE INVOLVING CHILDREN 2017        297
193 OFFENSE INVOLVING CHILDREN 2018        312
194 OFFENSE INVOLVING CHILDREN 2019        258
195 OFFENSE INVOLVING CHILDREN 2020        251
196 OFFENSE INVOLVING CHILDREN 2021        226
197 OFFENSE INVOLVING CHILDREN 2022        235
198 OFFENSE INVOLVING CHILDREN 2023        204
199 OFFENSE INVOLVING CHILDREN 2024        181
200 OFFENSE INVOLVING CHILDREN 2025         97
201                  RITUALISM 2001          8
202                  RITUALISM 2002          1
203                  RITUALISM 2003          1
204                  RITUALISM 2004          1
205                  RITUALISM 2005          2
206                  RITUALISM 2006          6
207                  RITUALISM 2007          1
208                  RITUALISM 2020          1
209                    ROBBERY 2001      18441
210                    ROBBERY 2002      18523
211                    ROBBERY 2003      17332
212                    ROBBERY 2004      15978
213                    ROBBERY 2005      16047
214                    ROBBERY 2006      15969
215                    ROBBERY 2007      15450
216                    ROBBERY 2008      16703
217                    ROBBERY 2009      15981
218                    ROBBERY 2010      14275
219                    ROBBERY 2011      13983
220                    ROBBERY 2012      13484
221                    ROBBERY 2013      11819
222                    ROBBERY 2014       9800
223                    ROBBERY 2015       9638
224                    ROBBERY 2016      11960
225                    ROBBERY 2017      11881
226                    ROBBERY 2018       9681
227                    ROBBERY 2019       7995
228                    ROBBERY 2020       7855
229                    ROBBERY 2021       7920
230                    ROBBERY 2022       8964
231                    ROBBERY 2023      11052
232                    ROBBERY 2024       9116
233                    ROBBERY 2025       3970
234                      THEFT 2001      99290
235                      THEFT 2002      98334
236                      THEFT 2003      98876
237                      THEFT 2004      95464
238                      THEFT 2005      85684
239                      THEFT 2006      86241
240                      THEFT 2007      85156
241                      THEFT 2008      88437
242                      THEFT 2009      80977
243                      THEFT 2010      76758
244                      THEFT 2011      75153
245                      THEFT 2012      75464
246                      THEFT 2013      71536
247                      THEFT 2014      61569
248                      THEFT 2015      57353
249                      THEFT 2016      61625
250                      THEFT 2017      64386
251                      THEFT 2018      65290
252                      THEFT 2019      62498
253                      THEFT 2020      41350
254                      THEFT 2021      40822
255                      THEFT 2022      54899
256                      THEFT 2023      57490
257                      THEFT 2024      60495
258                      THEFT 2025      35635</code></pre>
</div>
</div>
<section id="exercises-1" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="exercises-1"><span class="header-section-number">4.1</span> Exercises</h2>
<ol start="5" type="1">
<li><p>Count the number of arrests for “MOTOR VEHICLE THEFT”</p></li>
<li><p>Which District has the most thefts?. You can first try doing this with a mix of SQL and R. Once you do that, try finding another solution that only uses SQL (and two CTEs in a <code>WITH</code> clause separated by a comma).</p></li>
</ol>
</section>
</section>
<section id="subqueries" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Subqueries</h1>
<p>Sometimes we would like to use the results of one query as part of another query. You can put <code>SELECT</code> statements inside <code>FROM</code> statements to accomplish this. We will use this method to see if addresses are always geocoded to the same coordinates. Here are the unique combinations of addresses and coordinates. We will just show the first 20.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a><span class="st">   SELECT DISTINCT Block, Longitude, Latitude</span></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a><span class="st">   FROM crime</span></span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a><span class="st">   LIMIT 20"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     Block Longitude Latitude
1          023XX S TROY ST        NA       NA
2  039XX W WASHINGTON BLVD        NA       NA
3        015XX N DAMEN AVE -87.67741 41.90842
4      001XX W RANDOLPH ST        NA       NA
5         002XX N Wells st -87.63394 41.88602
6           0000X E 8TH ST -87.62615 41.87183
7   018XX S CALIFORNIA AVE -87.69560 41.85655
8    132XX S GREENWOOD AVE -87.59488 41.65512
9      035XX N CENTRAL AVE -87.76673 41.94523
10         004XX E 69TH ST -87.61501 41.76935
11       070XX S CLYDE AVE -87.57389 41.76742
12     073XX S EMERALD AVE -87.64308 41.76094
13      055XX S ALBANY AVE -87.70109 41.79261
14         040XX W 59TH ST -87.72327 41.78593
15         002XX W 47TH ST -87.63191 41.80913
16      044XX S KEDZIE AVE -87.70416 41.81281
17         004XX E 88TH ST -87.61318 41.73470
18     020XX N KIMBALL AVE -87.71191 41.91849
19   101XX S LAFAYETTE AVE -87.62480 41.71004
20       105XX S PERRY AVE -87.62578 41.70301</code></pre>
</div>
</div>
<p>The crime table has at least one row with each of these combinations of <code>Block</code>, <code>Longitude</code>, and <code>Latitude</code>.</p>
<p>We would like to know if <code>Block</code> shows up multiple times in these results or just once. We use the results of this query in the <code>FROM</code> clause and count up the frequency of each <code>Block</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="st">   SELECT COUNT(*) AS Blockcount, </span></span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a><span class="st">          Block</span></span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a><span class="st">   FROM</span></span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a><span class="st">     (SELECT DISTINCT block,</span></span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a><span class="st">                      Longitude,</span></span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a><span class="st">                      Latitude</span></span>
<span id="cb75-8"><a href="#cb75-8" aria-hidden="true" tabindex="-1"></a><span class="st">      FROM crime)</span></span>
<span id="cb75-9"><a href="#cb75-9" aria-hidden="true" tabindex="-1"></a><span class="st">   GROUP BY block</span></span>
<span id="cb75-10"><a href="#cb75-10" aria-hidden="true" tabindex="-1"></a><span class="st">   ORDER BY blockcount DESC</span></span>
<span id="cb75-11"><a href="#cb75-11" aria-hidden="true" tabindex="-1"></a><span class="st">   LIMIT 20"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Blockcount                block
1         117     034XX N CLARK ST
2         108     048XX N BROADWAY
3         106    016XX W HOWARD ST
4         105   002XX N PULASKI RD
5         104  013XX W RANDOLPH ST
6         103     044XX N BROADWAY
7         100     028XX N CLARK ST
8         100     024XX N CLARK ST
9          97    010XX W ARGYLE ST
10         96     045XX N BROADWAY
11         95  045XX N SHERIDAN RD
12         94  0000X W DIVISION ST
13         93   031XX W MADISON ST
14         93     031XX S GREEN ST
15         93 015XX N KINGSBURY ST
16         93  001XX W DIVISION ST
17         92    027XX W CERMAK RD
18         90   054XX W MADISON ST
19         87   049XX W MADISON ST
20         87  008XX W RANDOLPH ST</code></pre>
</div>
</div>
<p>Clearly, the coordinates are not unique to each address. The addresses are “rounded” to provide some privacy, but the coordinates appear to be scattered. Why? The Chicago data portal notes “This location is shifted from the actual location for partial redaction but falls on the same block.”</p>
<p>Rather than place subqueries in the <code>FROM</code> clause, the more modern preference is to use Common Table Expressions like we did earlier. Rewritten as a CTE:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="st"> WITH</span></span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a><span class="st">    XYBlockUnique AS</span></span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a><span class="st">      (SELECT DISTINCT block,</span></span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a><span class="st">              Longitude,</span></span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a><span class="st">              Latitude</span></span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a><span class="st">       FROM crime)</span></span>
<span id="cb77-8"><a href="#cb77-8" aria-hidden="true" tabindex="-1"></a><span class="st"> SELECT COUNT(*) AS blockcount,</span></span>
<span id="cb77-9"><a href="#cb77-9" aria-hidden="true" tabindex="-1"></a><span class="st">        block</span></span>
<span id="cb77-10"><a href="#cb77-10" aria-hidden="true" tabindex="-1"></a><span class="st"> FROM XYBlockUnique</span></span>
<span id="cb77-11"><a href="#cb77-11" aria-hidden="true" tabindex="-1"></a><span class="st"> GROUP BY block</span></span>
<span id="cb77-12"><a href="#cb77-12" aria-hidden="true" tabindex="-1"></a><span class="st"> ORDER BY blockcount DESC</span></span>
<span id="cb77-13"><a href="#cb77-13" aria-hidden="true" tabindex="-1"></a><span class="st"> LIMIT 20"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   blockcount                block
1         117     034XX N CLARK ST
2         108     048XX N BROADWAY
3         106    016XX W HOWARD ST
4         105   002XX N PULASKI RD
5         104  013XX W RANDOLPH ST
6         103     044XX N BROADWAY
7         100     028XX N CLARK ST
8         100     024XX N CLARK ST
9          97    010XX W ARGYLE ST
10         96     045XX N BROADWAY
11         95  045XX N SHERIDAN RD
12         94  0000X W DIVISION ST
13         93   031XX W MADISON ST
14         93     031XX S GREEN ST
15         93 015XX N KINGSBURY ST
16         93  001XX W DIVISION ST
17         92    027XX W CERMAK RD
18         90   054XX W MADISON ST
19         87   049XX W MADISON ST
20         87  008XX W RANDOLPH ST</code></pre>
</div>
</div>
<p>If you are going to use the CTE or subquery in multiple queries, then it is better to <code>CREATE TEMPORARY TABLE</code>, which we will encounter later.</p>
<p>After completing the final exercise, remember to run <code>dbDisconnect(con)</code> to disconnect from the database.</p>
<section id="exercise" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="exercise"><span class="header-section-number">5.1</span> Exercise</h2>
<p>As a final exercise that does not involve a subquery:</p>
<ol start="7" type="1">
<li>Count the number of assaults, since 2016, that occurred on Fridays and Saturdays, after 6pm, reporting the date, day of week, hour of the day, and year</li>
</ol>
</section>
</section>
<section id="solutions" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Solutions</h1>
<ol type="1">
<li>Print out all of the rows in iucr</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a><span class="st">  SELECT * from iucr</span></span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a><span class="st">  LIMIT 20"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   IUCR             PrimaryType FBICode
1  0110                HOMICIDE     01A
2  0130                HOMICIDE     01A
3  0141                HOMICIDE     01B
4  0142                HOMICIDE     01B
5  0261 CRIMINAL SEXUAL ASSAULT      02
6  0262 CRIMINAL SEXUAL ASSAULT      02
7  0263 CRIMINAL SEXUAL ASSAULT      02
8  0264 CRIMINAL SEXUAL ASSAULT      02
9  0265 CRIMINAL SEXUAL ASSAULT      02
10 0266 CRIMINAL SEXUAL ASSAULT      02
11 0271 CRIMINAL SEXUAL ASSAULT      02
12 0272 CRIMINAL SEXUAL ASSAULT      02
13 0273 CRIMINAL SEXUAL ASSAULT      02
14 0274 CRIMINAL SEXUAL ASSAULT      02
15 0275 CRIMINAL SEXUAL ASSAULT      02
16 0281 CRIMINAL SEXUAL ASSAULT      02
17 0291 CRIMINAL SEXUAL ASSAULT      02
18 0312                 ROBBERY      03
19 0313                 ROBBERY      03
20 031A                 ROBBERY      03</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Print out all the IUCR codes for “KIDNAPPING”</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="st">   SELECT iucr</span></span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a><span class="st">   FROM iucr</span></span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a><span class="st">   WHERE PrimaryType='KIDNAPPING'"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  IUCR
1 1792
2 4210
3 4220
4 4230
5 4240
6 4255</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>How many IUCR codes are there for “ASSAULT”?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a><span class="st">   SELECT *</span></span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a><span class="st">   FROM iucr</span></span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a><span class="st">   WHERE PrimaryType='ASSAULT'"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   IUCR PrimaryType FBICode
1  051A     ASSAULT     04A
2  051B     ASSAULT     04A
3  0520     ASSAULT     04A
4  0530     ASSAULT     04A
5  0545     ASSAULT     08A
6  0550     ASSAULT     04A
7  0551     ASSAULT     04A
8  0552     ASSAULT     04A
9  0553     ASSAULT     04A
10 0554     ASSAULT     08A
11 0555     ASSAULT     04A
12 0556     ASSAULT     04A
13 0557     ASSAULT     04A
14 0558     ASSAULT     04A
15 0560     ASSAULT     08A</code></pre>
</div>
</div>
<ol start="4" type="1">
<li>Try doing the prior exercise again using <code>COUNT(*)</code> if you did not use it the first time</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a><span class="st">   SELECT COUNT(*)</span></span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a><span class="st">   FROM iucr</span></span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a><span class="st">   WHERE PrimaryType='ASSAULT'"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  COUNT(*)
1       15</code></pre>
</div>
</div>
<ol start="5" type="1">
<li>Count the number of arrests for “MOTOR VEHICLE THEFT”</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a><span class="st">   SELECT COUNT(*) as MVTArrestCount</span></span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a><span class="st">   FROM crime</span></span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a><span class="st">      INNER JOIN iucr ON</span></span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a><span class="st">         crime.iucr=iucr.iucr</span></span>
<span id="cb87-6"><a href="#cb87-6" aria-hidden="true" tabindex="-1"></a><span class="st">   WHERE crime.Arrest='true' AND</span></span>
<span id="cb87-7"><a href="#cb87-7" aria-hidden="true" tabindex="-1"></a><span class="st">         iucr.PrimaryType='MOTOR VEHICLE THEFT'"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  MVTArrestCount
1          32533</code></pre>
</div>
</div>
<ol start="6" type="1">
<li>Which District has the most thefts?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a><span class="st">   SELECT COUNT(*) AS crimecount,</span></span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a><span class="st">          District</span></span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a><span class="st">   FROM crime</span></span>
<span id="cb89-5"><a href="#cb89-5" aria-hidden="true" tabindex="-1"></a><span class="st">      INNER JOIN iucr ON</span></span>
<span id="cb89-6"><a href="#cb89-6" aria-hidden="true" tabindex="-1"></a><span class="st">         crime.iucr=iucr.iucr</span></span>
<span id="cb89-7"><a href="#cb89-7" aria-hidden="true" tabindex="-1"></a><span class="st">   WHERE iucr.PrimaryType='THEFT'</span></span>
<span id="cb89-8"><a href="#cb89-8" aria-hidden="true" tabindex="-1"></a><span class="st">   GROUP BY District"</span>)</span>
<span id="cb89-9"><a href="#cb89-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-10"><a href="#cb89-10" aria-hidden="true" tabindex="-1"></a>a <span class="sc">|&gt;</span></span>
<span id="cb89-11"><a href="#cb89-11" aria-hidden="true" tabindex="-1"></a>   <span class="fu">filter</span>(crimecount<span class="sc">==</span><span class="fu">max</span>(crimecount))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  crimecount District
1     159430      018</code></pre>
</div>
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="co"># or</span></span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>a <span class="sc">|&gt;</span></span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a>   <span class="fu">slice_max</span>(crimecount, <span class="at">with_ties=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  crimecount District
1     159430      018</code></pre>
</div>
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="co"># or with a CTE</span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a><span class="st">WITH </span></span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a><span class="st">   -- first CTE counts thefts by district</span></span>
<span id="cb93-5"><a href="#cb93-5" aria-hidden="true" tabindex="-1"></a><span class="st">   DistrictCountCTE AS </span></span>
<span id="cb93-6"><a href="#cb93-6" aria-hidden="true" tabindex="-1"></a><span class="st">      (SELECT COUNT(*) AS crimecount,</span></span>
<span id="cb93-7"><a href="#cb93-7" aria-hidden="true" tabindex="-1"></a><span class="st">              District</span></span>
<span id="cb93-8"><a href="#cb93-8" aria-hidden="true" tabindex="-1"></a><span class="st">       FROM crime</span></span>
<span id="cb93-9"><a href="#cb93-9" aria-hidden="true" tabindex="-1"></a><span class="st">          INNER JOIN iucr ON</span></span>
<span id="cb93-10"><a href="#cb93-10" aria-hidden="true" tabindex="-1"></a><span class="st">             crime.iucr=iucr.iucr</span></span>
<span id="cb93-11"><a href="#cb93-11" aria-hidden="true" tabindex="-1"></a><span class="st">       WHERE iucr.PrimaryType='THEFT'</span></span>
<span id="cb93-12"><a href="#cb93-12" aria-hidden="true" tabindex="-1"></a><span class="st">       GROUP BY District),</span></span>
<span id="cb93-13"><a href="#cb93-13" aria-hidden="true" tabindex="-1"></a><span class="st">   -- second CTE finds the max theft count</span></span>
<span id="cb93-14"><a href="#cb93-14" aria-hidden="true" tabindex="-1"></a><span class="st">   MaxCountCTE AS</span></span>
<span id="cb93-15"><a href="#cb93-15" aria-hidden="true" tabindex="-1"></a><span class="st">      (SELECT MAX(crimecount) AS MaxCrimeCount</span></span>
<span id="cb93-16"><a href="#cb93-16" aria-hidden="true" tabindex="-1"></a><span class="st">       FROM DistrictCountCTE)</span></span>
<span id="cb93-17"><a href="#cb93-17" aria-hidden="true" tabindex="-1"></a><span class="st">-- main query selects the district(s) matching the max       </span></span>
<span id="cb93-18"><a href="#cb93-18" aria-hidden="true" tabindex="-1"></a><span class="st">SELECT District, crimecount</span></span>
<span id="cb93-19"><a href="#cb93-19" aria-hidden="true" tabindex="-1"></a><span class="st">FROM DistrictCountCTE</span></span>
<span id="cb93-20"><a href="#cb93-20" aria-hidden="true" tabindex="-1"></a><span class="st">   INNER JOIN MaxCountCTE</span></span>
<span id="cb93-21"><a href="#cb93-21" aria-hidden="true" tabindex="-1"></a><span class="st">      ON DistrictCountCTE.crimecount = MaxCountCTE.MaxCrimeCount</span></span>
<span id="cb93-22"><a href="#cb93-22" aria-hidden="true" tabindex="-1"></a><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  District crimecount
1      018     159430</code></pre>
</div>
</div>
<ol start="7" type="1">
<li>Count the number of assaults, since 2016, that occurred on Fridays and Saturdays, after 6pm, reporting the date, day of week, hour of the day, and year</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="co">#  count 1) assaults</span></span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a><span class="co">#        2) since 2016 on</span></span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a><span class="co">#        3) Fridays and Saturdays</span></span>
<span id="cb95-4"><a href="#cb95-4" aria-hidden="true" tabindex="-1"></a><span class="co">#        4) after 6pm</span></span>
<span id="cb95-5"><a href="#cb95-5" aria-hidden="true" tabindex="-1"></a><span class="co"># report 5) count,</span></span>
<span id="cb95-6"><a href="#cb95-6" aria-hidden="true" tabindex="-1"></a><span class="co">#        6) date,</span></span>
<span id="cb95-7"><a href="#cb95-7" aria-hidden="true" tabindex="-1"></a><span class="co">#        7) day of week, and</span></span>
<span id="cb95-8"><a href="#cb95-8" aria-hidden="true" tabindex="-1"></a><span class="co">#        8) hour of the day</span></span>
<span id="cb95-9"><a href="#cb95-9" aria-hidden="true" tabindex="-1"></a><span class="co">#        9) year</span></span>
<span id="cb95-10"><a href="#cb95-10" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, <span class="st">"</span></span>
<span id="cb95-11"><a href="#cb95-11" aria-hidden="true" tabindex="-1"></a><span class="st">   SELECT COUNT(*),</span></span>
<span id="cb95-12"><a href="#cb95-12" aria-hidden="true" tabindex="-1"></a><span class="st">          DATE(crime.date) AS crimdate,</span></span>
<span id="cb95-13"><a href="#cb95-13" aria-hidden="true" tabindex="-1"></a><span class="st">          CAST(STRFTIME('%w',crime.date) AS INTEGER) AS weekday,</span></span>
<span id="cb95-14"><a href="#cb95-14" aria-hidden="true" tabindex="-1"></a><span class="st">          CAST(STRFTIME('%H',crime.date) AS INTEGER) AS hour,</span></span>
<span id="cb95-15"><a href="#cb95-15" aria-hidden="true" tabindex="-1"></a><span class="st">          CAST(STRFTIME('%Y',crime.date) AS INTEGER) AS year</span></span>
<span id="cb95-16"><a href="#cb95-16" aria-hidden="true" tabindex="-1"></a><span class="st">   FROM   crime</span></span>
<span id="cb95-17"><a href="#cb95-17" aria-hidden="true" tabindex="-1"></a><span class="st">             INNER JOIN iucr ON</span></span>
<span id="cb95-18"><a href="#cb95-18" aria-hidden="true" tabindex="-1"></a><span class="st">                crime.iucr=iucr.iucr</span></span>
<span id="cb95-19"><a href="#cb95-19" aria-hidden="true" tabindex="-1"></a><span class="st">   WHERE  iucr.PrimaryType='ASSAULT' AND</span></span>
<span id="cb95-20"><a href="#cb95-20" aria-hidden="true" tabindex="-1"></a><span class="st">          year&gt;=2016 AND</span></span>
<span id="cb95-21"><a href="#cb95-21" aria-hidden="true" tabindex="-1"></a><span class="st">          weekday&gt;=5 AND</span></span>
<span id="cb95-22"><a href="#cb95-22" aria-hidden="true" tabindex="-1"></a><span class="st">          hour&gt;=18</span></span>
<span id="cb95-23"><a href="#cb95-23" aria-hidden="true" tabindex="-1"></a><span class="st">   GROUP BY crimdate, weekday, hour, year</span></span>
<span id="cb95-24"><a href="#cb95-24" aria-hidden="true" tabindex="-1"></a><span class="st">   LIMIT 20"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   COUNT(*)   crimdate weekday hour year
1         2 2016-01-01       5   18 2016
2         3 2016-01-01       5   19 2016
3         1 2016-01-01       5   20 2016
4         3 2016-01-01       5   21 2016
5         1 2016-01-01       5   22 2016
6         3 2016-01-01       5   23 2016
7         2 2016-01-02       6   18 2016
8         2 2016-01-02       6   19 2016
9         2 2016-01-02       6   20 2016
10        1 2016-01-02       6   21 2016
11        2 2016-01-02       6   22 2016
12        1 2016-01-02       6   23 2016
13        6 2016-01-08       5   18 2016
14        2 2016-01-08       5   19 2016
15        1 2016-01-08       5   21 2016
16        4 2016-01-08       5   23 2016
17        2 2016-01-09       6   18 2016
18        2 2016-01-09       6   19 2016
19        4 2016-01-09       6   20 2016
20        2 2016-01-09       6   21 2016</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbDisconnect</span>(con)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = true;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>