{
  "hash": "e25f33744d1d1f8a418d1ff9f1634f97",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Introduction to NIBRS\"\nauthor:\n- affiliation: University of Pennsylvania\n  email: gridge@upenn.edu\n  name: Greg Ridgeway\ndate: \"August 15, 2025\"\nformat:\n  html:\n    theme: \n      dark: darkly\n      light: default\n    toc: true\n    html-math-method: mathjax\n  pdf:\n    toc: true\n    exclude: true\n    prefer-html: true\nnumber-sections: true\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n\n<!-- In terminal -->\n<!-- quarto render 03_Working_with_NIBRS_data.qmd -->\n\n<!-- git commit 03_* -m \"commit message\" -->\n<!-- git status -->\n<!-- git push -->\n\n\n<!-- A function for automating the numbering and wording of the exercise questions -->\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n# National Incident-Based Reporting System\n\nThe FBI established the Uniform Crime Reporting (UCR) Program in 1930 to generate reliable crime statistics for law enforcement administration, operation, and management. It has been the primary source of crime data in the United States for decades.\n\nThe UCR's Summary Reporting System (SRS) is the best-known component of the UCR. About 18,000 law enforcement agencies, including municipal police departments, sheriff's departments, campus police, transit police, park police, and many other agencies, reported monthly counts of Part 1 crimes (murder and non-negligent manslaughter, forcible rape, robbery, aggravated assault, burglary, larceny theft, motor vehicle theft, and arson), often called \"index crimes.\" The SRS also tracked monthly counts of Part II crimes, such as simple assault, fraud, vandalism, drug offenses, and driving under the influence. Even though reporting to the SRS was voluntary, almost all law enforcement agencies reported their data, offering fairly comprehensive coverage of crimes reported to the police in the United States.\n\nWhile the UCR SRS has provided valuable crime data for many years, it has several notable limitations. The SRS focused on a limited number of crimes, potentially overlooking important details and emerging trends. With SRS data researchers cannot separate out trends in shootings, identity theft, and cybercrimes. Shootings, for example, are lumped together in an aggravated assault category that includes a range of serious assaults like striking someone with a beer bottle. The SRS also operated under the \"Hierarchy Rule,\" reporting only the most severe offense in a multi-offense incident. Lastly, the SRS only collected aggregate counts, meaning that detailed information about the context of the crimes, such as the characteristics of the victims and offenders, the extent of property loss or damage, the time, place, and context of the crime, and the relationships between these crime features, is lost.\n\nThe FBI introduced the National Incident-Based Reporting System (NIBRS) in the 1980s. NIBRS aimed to address the shortcomings of the SRS by capturing incident-level data and a comprehensive description of what happened in each incident. Unlike the SRS, NIBRS collects data on each individual crime incident, capturing detailed information about the offenses, victims, offenders, property, and arrestees. NIBRS records data on 52 \"Group A\" offenses and 10 \"Group B\" offenses, covering a broader spectrum of criminal activity. It did away with the Hierarchy Rule and collects data on all offenses within a single incident, providing a fuller picture of criminal activity. Because NIBRS is incident-based, we have full access to the multivariate relationships between features of crime incidents.\n\nOn January 1, 2021, the FBI officially retired the SRS marking a significant transition towards the exclusive use of the National Incident-Based Reporting System for crime data collection and reporting. Although the transition has been planned for almost a decade, many law enforcement agencies are yet to transition their information systems to report to NIBRS. As of this writing, four of the nation's largest states, California, New York, Pennsylvania, and Florida, essentially do not participate in NIBRS. You can find a [map describing NIBRS coverage](https://bjs.ojp.gov/national-incident-based-reporting-system-nibrs) at the Bureau of Justice Statistics. The largest law enforcement agencies in those states regularly post crime data to their local open data portals, but you will not find those data in NIBRS yet. The transition to NIBRS also makes the study of long-term national crime trends challenging. Any study that spans the SRS-NIBRS transition will have to grapple with inconsistencies and gaps in data as agencies adapt to the new system.\n\nThe FBI accepts data from law enforcement agencies through March of the following year. That is, the FBI accepted NIBRS data for 2023 through March 2024. Some crimes committed in December 2023, for example, may be solved or result in an arrest in April 2024. Such a case would not get marked as \"cleared\" in the NIBRS data since the clearance came after the NIBRS 2023 submission end date. Crimes in January 2023 may seem to be solved at a higher rate than crimes in December 2023 because of the March 2024 censoring. This is a feature of the data that simply requires care. Lastly, like the SRS, NIBRS only has data on those crimes reported to the police and reporting rates can vary greatly by type of crime.\n\nIn this document, you will walk through running the nibrs.R script, which processes NIBRS data from 2023. The steps will cover reading the dataset, segmenting data by type (e.g., offenders, victims), and performing some exploration of the NIBRS data.\n\n# Acquiring the data\n\nThe complete NIBRS data are available from the FBI's Crime Data Explorer [downloads page](https://cde.ucr.cjis.gov/LATEST/webapp/#/pages/downloads) under the Master File Downloads section heading. from the dropdown menu select \"National Incident-Based Reporting System (NIBRS)\". The compressed data file, `nibrs-2023.zip`, is over 500 Mb so downloading will take some time. It has over 73 million rows of data. Unzip `nibrs-2023.zip`. It is very big... about 6 Gb. I then run `gzip 2023_NIBRS_NATIONAL_MASTER_FILE.TXT` from the Terminal pane in RStudio (not the Console pane, the Terminal pane is typically one tab to the right of the Console pane).\n\nLet's start by loading a few libraries that we will need and peeking at a few lines of the data.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(readr)\nlibrary(stringr)\nlibrary(lubridate)\n\nscan(\"2023_NIBRS_NATIONAL_MASTER_FILE.txt.gz\",\n     nlines=5, what=\"\", sep=\"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"BH50AK0010100000000000000                ANCHORAGE                     AK1C941Y         3030020A         00028502600  39000000000000000000      000000000000000000      000000000000000000      000000000000000000      000000000  002023NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN020            \"\n[2] \"BH50AK0010200000000000000        20210101FAIRBANKS                     AK4 941Y         3030020AA        00003196100 258000000000000000000      000000000000000000      000000000000000000      000000000000000000      00000000012122023NYNNYNNYNNYNNYNNYNNYNNYNNYNNYNNYNNYN090            \"\n[3] \"0150AK001020023000003    20230101 11010010100    N                                      N\"                                                                                                                                                                                                   \n[4] \"0250AK001020023000003    2023010123DCN  04               88\"                                                                                                                                                                                                                                 \n[5] \"0350AK001020023000003    20230101775000000150                                                         \"                                                                                                                                                                                      \n```\n\n\n:::\n:::\n\n\n\nAs you can see the data are not pretty. This data is in \"fixed-width format\". Rather than separate each column of data with a delimiter (like a comma or tab), all of the data fields are placed side by side. This is a legacy format that has some benefits. First, there is no need to store delimiters. This is less important these days with cheap data storage, but storing delimiters in a dataset this size requires about 1 Gb... just to store a bunch of commas. Instead, the data come with a separate file that describes which columns of text correspond to different columns of data. The following table shows the first five rows of the NIBRS offense segment in the included `NIBRS Records Description updated.xlsx` file.\n\n| Positions | Field Length and Type | Field Name                              | \n|-----------|-----------------------|-----------------------------------------|\n| 1-2       | A2                    | SEGMENT LEVEL                           |\n| 3-4       | N2                    | NUMERIC STATE CODE                      |\n| 5-13      | A9                    | ORIGINATING AGENCY IDENTIFIER (ORI)     |\n| 14-25     | A12                   | INCIDENT NUMBER                         |\n| 26-33     | A8                    | INCIDENT DATE                           |\n| 34-36     | A3                    | UCR OFFENSE CODE\t\t\t               |\n| ...       | ...                   | ...                                     |\n\nThe table tells us that for offense segments, the first two characters represent the segment level, characters 3 and 4 capture the state numeric code, characters 5-13 capture the ORI (a unique identifier for a law enforcement agency), and so on. The second column describes the data type, (A)lphanumeric or (N)umeric, and the width (number of characters) of the data field. Let's start by discussing the segment level. The NIBRS data is more complex than an already complex fixed-width format data file. The NIBRS data involve several data tables, separate tables for offenses, victims, offenders, property, and arrests. The data file we just loaded interleaves all of these tables. Note that the fourth row of the data we scanned in starts with \"02\" that signals that the rest of that row describes an offense and its format will align with the formatting table shown here. Since characters 3-4 are \"50\" we know from the format table that this number represents the state with code \"50,\" which turns out to be Alaska. The next nine characters (AK0010200) is the ORI code for the law enforcement agency that reported the offense, which turns out to be the Fairbanks Police Department. If we look further to the right in that fourth row of data to characters 26-33 we get \"20230101,\" which is the data of the criminal incident, January 1, 2023. And the three characters after the date give the offense code \"23D,\" which is the code for theft from a building. \n\nThis interpretation only works for lines of data with the first two characters equal to \"02\". The others are\n\n| Segment code            | Segment type        |\n|-------------------------|---------------------|\n|BH                       | batch header        |\n|01                       | administrative      |\n|02                       | offenses            |\n|03                       | property            |\n|04                       | victims             |\n|05                       | offender            |\n|06                       | arrestee            |\n|07                       | Group B arrests     |\n|W1                       | Incomplete admin    |\n|W3                       | Incomplete property |\n|W6                       | Incomplete arrest   |\n\nWe will read each of these in and explore what they contain. The W1, W2, and W3 are \"window segments\" and represent a partial reporting. These are relatively rare records and mostly relate to arrests or recovered property related to offenses that do not appear in the 02 segment, most likely because the agency transitioned to NIBRS between the offense and the recovery/arrest.\n\n# Reading in the data\nHere's the strategy that we will use to read in the data. The data might be too big to read in all at once and still have computer memory available to clean and organize the data. Instead of reading all of it in, we are going to read in one million rows at a time. We will then examine the first two characters of each row and split rows of data by those first two characters. In this way, all the offense records will be together, and all the victim records will be together, and so one. Then we will write out all the records into segment specific files. Our computers will then have a separate file for each of the NIBRS segments.\n\nFirst, I set up `infile` to connect to the large NIBRS data file, opening it in (r)ead mode. Next, I set up eight files, one for each of the segments, creating them in (w)rite mode to be gzip'd (compressed) as they are created. Then I set up a while-loop to continue to read one million lines at a time as long as there are more rows of data to read in. Within the loop I use `split()` to separate the lines of data I have read in based on the first two characters of the line. I combine the few window segments with the similar complete records (e.g. window segment on property goes with the rest of the property data). Lastly, inside the loop I write out the new batch of data, appending them to existing data from previous iterations of the while-loop. Closing all the files makes sure that all the read and write buffers get flushed to the data files and the connections are closed.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# set the file we want to 'r'ead\ninfile  <- file(\"2023_NIBRS_NATIONAL_MASTER_FILE.txt.gz\",'r')\n# create the files we are going to 'w'rite\noutfile <- list(\"01\"=gzfile(\"2023-01.txt.gz\", 'w'),\n                \"02\"=gzfile(\"2023-02.txt.gz\", 'w'),\n                \"03\"=gzfile(\"2023-03.txt.gz\", 'w'),\n                \"04\"=gzfile(\"2023-04.txt.gz\", 'w'),\n                \"05\"=gzfile(\"2023-05.txt.gz\", 'w'),\n                \"06\"=gzfile(\"2023-06.txt.gz\", 'w'),\n                \"07\"=gzfile(\"2023-07.txt.gz\", 'w'),\n                \"BH\"=gzfile(\"2023-BH.txt.gz\", 'w'))\n\n# read in 1,000,000 lines at a time\ncLines <- 0\nwhile ((length(a <- readLines(infile, n=1000000)) >  0))\n{\n  # split up what we read based on first two characters BH, 01, 02, ...\n  b <- split(a, substring(a,1,2))\n\n  # combine window segments with the associated segments\n  b[[\"01\"]] <- c(b[[\"01\"]], b[[\"W1\"]]) # administrative\n  b[[\"03\"]] <- c(b[[\"03\"]], b[[\"W3\"]]) # property\n  b[[\"06\"]] <- c(b[[\"06\"]], b[[\"W6\"]]) # arrestees\n  b[c(\"W1\",\"W3\",\"W6\")] <- NULL # drop the W1, W3, W6\n\n  # write each segment to its own file\n  for(iSegment in names(b))\n  {\n    writeLines(b[[iSegment]], con=outfile[[iSegment]])\n  }\n}\nclose(infile)\nfor(iSegment in 1:8)\n{\n  close(outfile[[iSegment]])\n}\n```\n:::\n\n\n\n\nNow with the segments separated into their own files, we can read them each in individually.\n\nThe Excel file `NIBRS Records Description updated.xlsx` contains all the information about which columns in which segments contain which data field. It is probably a good idea to open the file in Excel and explore what is in there and how the file is structured. We will start by reading in the second sheet called \"INCIDENT RECORD\" using `read_excel()` from the `readxl` library. Note that `range` is set to just capture the part of the sheet with the information that we need. So, the first row in `fmtXL` will be the row with the header: Data Field Number, Position, Type/Length, Description.\n \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfmtXL <- read_excel(\"NIBRS Records Description updated.xlsx\",\n                    sheet = \"INCIDENT RECORD\",\n                    range = \"A5:D819\") |>\n   rename(DataField=`Data Field Number`,\n          TypeLength=`Type/ Length`)\n```\n:::\n\n\n\n\n## Administrative segment\n\nWe will start by reading in segment 01, the administrative segment, where the records description lies between rows 3 and 100 in `fmtXL`. I'm going to use `grep()` to find out where the description of the next segment (LEVEL 02, the offense segment) starts so I know where the end of the administrative segment is. I am also going to drop those rows where `Position` is missing and where `Position==\"59-88\"`, which is redundant with other record descriptions which provide more details about the contents between characters 59 and 88 in administrative records.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# select only the rows for admin segment\ni <- grep('LEVEL \"02\"', fmtXL$DataField)\nfmt <- fmtXL |>\n  slice(3:(i-3)) |>\n  filter(!is.na(Position) &\n         !(Position %in% c(\"59-88\"))) # up to 10 UCR codes\nfmt\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 25 x 4\n   DataField Position TypeLength Description                                    \n   <chr>     <chr>    <chr>      <chr>                                          \n 1 <NA>      1-2      A2         \"SEGMENT LEVEL - Designates this as the Admini~\n 2 <NA>      3-4      N2         \"NUMERIC STATE CODE - This is a two-digit valu~\n 3 1         5-13     A9         \"ORIGINATING AGENCY IDENTIFIER (ORI) - This id~\n 4 2         14-25    A12        \"INCIDENT NUMBER - This is a unique case numbe~\n 5 3         26-33    A8         \"INCIDENT DATE - This is the date that the inc~\n 6 <NA>      34       A1         \"REPORT DATE INDICATOR - If value is \\\"R\\\" = R~\n 7 <NA>      35-36    A2         \"INCIDENT DATE HOUR - This is the military tim~\n 8 <NA>      37-38    N2         \"TOTAL OFFENSE SEGMENTS - This is the number o~\n 9 <NA>      39-41    N3         \"TOTAL VICTIM SEGMENTS - This is the number of~\n10 <NA>      42-43    N2         \"TOTAL OFFENDER SEGMENTS - This is the number ~\n# i 15 more rows\n```\n\n\n:::\n:::\n\n\n\n\n`fmt` now contains everything we need to know about how to interpret the administrative data. We are going to use `read_fwf()` from the `readr` package to read in the fixed-width formatted administrative segment (R also has a `read.fwf()` function, but it is extremely slow with large files). `read_fwf()` needs to know how wide each column is and whether it is of type character (c) or of type numeric (n). The `TypeLength` column in `fmt` has this information. If the first character is an A (alphanumeric) then I will set `fmtType` to \"c\", otherwise I will set it to \"n\". Then the rest of the `TypeLength` field I will store in `fmtWidth`. Lastly, I will need to create some column names for the dataset and I see that the part of the `Description` column before the hyphen has a suitable column name. I'll use `strsplit()` to separate the `Description` at the \" - \" and keep only the first part for the column names. `make.names()` converts the names to syntactically valid R variable names, replacing invalid characters like spaces and # with a period instead.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfmtType <- fmt$TypeLength |> \n   substring(1,1) |>            # get first character\n   case_match(\"A\"~\"c\",\"N\"~\"n\")  # convert A->c, N->n\nfmtWidth <- fmt$TypeLength |> \n   substring(2) |>   # get everything after the first character\n   as.numeric()      # turn text to a number\nfmtNames <- fmt$Description |>\n   strsplit(split = \" - \", fixed = TRUE) |>\n   sapply(head, n=1) |>\n   make.names() |>\n   gsub(\"\\\\.+(\\\\.|$)\", \"\\\\1\", x=_) # turn .. into one . or delete trailing .\n```\n:::\n\n\n\n\nTime to read in the administrative segment.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# read in the data from fixed width format\n#    R also has a read.fwf() function but it is very slow\nnibrsAdmin01 <-\n   read_fwf(\"2023-01.txt.gz\",\n            col_positions = fwf_widths(fmtWidth),\n            col_type=paste(fmtType, collapse=\"\")) |>\n   rename_with(~fmtNames) |>\n   rename(ORI     = ORIGINATING.AGENCY.IDENTIFIER.ORI,\n          SEGMENT = SEGMENT.LEVEL,\n          STATE   = NUMERIC.STATE.CODE)\n```\n:::\n\n\n\n\nLet's take a look at the first three rows.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnibrsAdmin01 |> print(n=3, width=Inf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12,351,743 x 25\n  SEGMENT STATE ORI       INCIDENT.NUMBER INCIDENT.DATE REPORT.DATE.INDICATOR\n  <chr>   <dbl> <chr>     <chr>           <chr>         <chr>                \n1 01         50 AK0010200 23000003        20230101      <NA>                 \n2 01         50 AK0010200 23000005        20230101      <NA>                 \n3 01         50 AK0010200 23000011        20230102      <NA>                 \n  INCIDENT.DATE.HOUR TOTAL.OFFENSE.SEGMENTS TOTAL.VICTIM.SEGMENTS\n  <chr>                               <dbl>                 <dbl>\n1 11                                      1                     1\n2 15                                      1                     1\n3 16                                      1                     1\n  TOTAL.OFFENDER.SEGMENTS TOTAL.ARRESTEE.SEGMENTS CITY.SUBMISSION\n                    <dbl>                   <dbl> <chr>          \n1                       1                       0 <NA>           \n2                       1                       0 <NA>           \n3                       2                       0 <NA>           \n  CLEARED.EXCEPTIONALLY EXCEPTIONAL.CLEARANCE.DATE OFFENSE.CODE.1 OFFENSE.CODE.2\n  <chr>                 <chr>                      <chr>          <chr>         \n1 N                     <NA>                       <NA>           <NA>          \n2 N                     <NA>                       <NA>           <NA>          \n3 N                     <NA>                       <NA>           <NA>          \n  OFFENSE.CODE.3 OFFENSE.CODE.4 OFFENSE.CODE.5 OFFENSE.CODE.6 OFFENSE.CODE.7\n  <chr>          <chr>          <chr>          <chr>          <chr>         \n1 <NA>           <NA>           <NA>           <NA>           <NA>          \n2 <NA>           <NA>           <NA>           <NA>           <NA>          \n3 <NA>           <NA>           <NA>           <NA>           <NA>          \n  OFFENSE.CODE.8 OFFENSE.CODE.9 OFFENSE.CODE.10 Cargo.Theft.Indicator\n  <chr>          <chr>          <chr>           <chr>                \n1 <NA>           <NA>           <NA>            N                    \n2 <NA>           <NA>           <NA>            N                    \n3 <NA>           <NA>           <NA>            N                    \n# i 12,351,740 more rows\n```\n\n\n:::\n:::\n\n\n\nThe first row describes one incident, occurring in Alaska (STATE=50), reported to the Fairbanks Police Department (ORI=AK0010200), that occurred on January 1, 2023 at around 11am. The incident number, 23000003, is only unique within an agency. There may be other incidents that other law enforcement agencies reported that have the same incident number. Whenever linking this record to learn more about the offense, victims, property, and arrests, be sure to join on *both* the ORI *and* the incident number. The first row also tells us that this incident involved one particular offense, involving one victim and one offender, with no arrests (at least through the cutoff date of March 15, 2024).\n\n## Offense segment\nLet's move on to loading the offense data. NIBRS reports all \"Group A offenses\" in the offense table. Group A offenses are mostly crimes against a person or property. NIBRS includes crime types based on \n\n- seriousness of offense\n- frequency of its occurrence\n- prevalence nationwide\n- probability the offense comes to police attention\n- law enforcement is the best channel for collecting data\n- burden placed on law enforcement to collect data\n- validity and usefulness of the collected data\n- legitimate general interest in offense\n\nA [complete list of offenses](https://bjs.ojp.gov/sites/g/files/xyckuh236/files/media/document/offensea_offenseb.pdf) that fall into Group A can be found at the Bureau of Justice Statistics website. Generally, Group A includes arson, assault, burglary, counterfeiting, vandalism, drugs, extortion, fraud, gambling, homicide, human trafficking, kidnapping, theft, motor vehicle theft, obscene material, prostitution, robbery, sex offenses, and weapons offenses. You will not find reports of Group B offenses in the offense segment. Group B offenses include writing bad checks, curfew violations, loitering, disorderly conduct, drunk driving, family offenses, peeping tom, trespassing, and other non-violent offenses. These crimes only get included in NIBRS arrest segment if there is an arrest. Reports from the public about Group B offenses do not make it into the offense segment.\n\nAs with the administrative segment, we will extract from the Excel records description the offense segment's format.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# select only the rows for offense segment,\n#   everything between LEVEL 02 and LEVEL 03\ni <- grep('LEVEL \"02\"', fmtXL$DataField)\nj <- grep('LEVEL \"03\"', fmtXL$DataField)\nfmt <- fmtXL |>\n  slice((i+1):(j-3)) |>\n  filter(!is.na(Position) &\n         !(Position %in% c(\"38-40\",\"46-48\",\"49-57\")))\nfmt\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 21 x 4\n   DataField Position TypeLength Description                                    \n   <chr>     <chr>    <chr>      <chr>                                          \n 1 <NA>      1-2      A2         \"SEGMENT LEVEL - Designates this as the Offens~\n 2 <NA>      3-4      N2         \"NUMERIC STATE CODE - This is a two-digit valu~\n 3 1         5-13     A9         \"ORIGINATING AGENCY IDENTIFIER (ORI) - This id~\n 4 2         14-25    A12        \"INCIDENT NUMBER - This is a unique case numbe~\n 5 3         26-33    A8         \"INCIDENT DATE - This is the same date value f~\n 6 6         34-36    A3         \"UCR OFFENSE CODE\"                             \n 7 7         37       A1         \"OFFENSE ATTEMPTED/COMPLETED - This indicates ~\n 8 8         38       A1         \"SUSPECTED OF USING #1\"                        \n 9 8         39       A1         \"SUSPECTED OF USING #2\"                        \n10 8         40       A1         \"SUSPECTED OF USING #3\"                        \n# i 11 more rows\n```\n\n\n:::\n:::\n\n\n\nThis `fmt` is similar in structure to the one we saw for the administrative segment, just with a different set of features, ones more specific to the offense, like the UCR code of the offense and whether it was attempted or completed. Let's use `read_fwf()` to read in the offense data.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfmtType <- fmt$TypeLength |> \n   substring(1,1) |>\n   case_match(\"A\"~\"c\",\"N\"~\"n\")\nfmtWidth <- fmt$TypeLength |> \n   substring(2) |>\n   as.numeric()\nfmtNames <- fmt$Description |>\n   strsplit(split = \" - \", fixed = TRUE) |>\n   sapply(head, n=1) |>\n   make.names() |>\n   gsub(\"\\\\.+(\\\\.|$)\", \"\\\\1\", x=_)\n\nnibrsCrm02 <- read_fwf(\"2023-02.txt.gz\",\n                       col_positions = fwf_widths(fmtWidth),\n                       col_type=paste(fmtType,collapse=\"\")) |>\n   rename_with(~fmtNames) |>\n   rename(ORI     = ORIGINATING.AGENCY.IDENTIFIER.ORI,\n          SEGMENT = SEGMENT.LEVEL,\n          STATE   = NUMERIC.STATE.CODE)\n```\n:::\n\n\n\n\n\n\nLet's pull up the offense record for the Fairbanks, Alaska incident 2300003 that was in the first row of the administrative segment.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnibrsCrm02 |> filter(INCIDENT.NUMBER==\"23000003\") |> print(n=3, width=80)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 91 x 21\n  SEGMENT STATE ORI       INCIDENT.NUMBER INCIDENT.DATE UCR.OFFENSE.CODE\n  <chr>   <dbl> <chr>     <chr>           <chr>         <chr>           \n1 02         50 AK0010200 23000003        20230101      23D             \n2 02         50 AK0010900 23000003        20230101      290             \n3 02          2 AZ0071300 23000003        20230101      520             \n# i 88 more rows\n# i 15 more variables: OFFENSE.ATTEMPTED.COMPLETED <chr>,\n#   SUSPECTED.OF.USING.1 <chr>, SUSPECTED.OF.USING.2 <chr>,\n#   SUSPECTED.OF.USING.3 <chr>, LOCATION.TYPE <chr>,\n#   NUMBER.OF.PREMISES.ENTERED <chr>, METHOD.OF.ENTRY <chr>,\n#   CRIMINAL.ACTIVITY.1.GANG.INFORMATION.1 <chr>,\n#   CRIMINAL.ACTIVITY.2.GANG.INFORMATION.2 <chr>, ...\n```\n\n\n:::\n:::\n\n\n\nNote here that I only filtered on the incident number. What we got back were all incidents labeled as incident number 23000003, including those from other police departments. Remember that incident numbers are only unique within a law enforcement agency. So, we need to also specifically request the incident from Fairbanks.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnibrsCrm02 |> \n   filter(ORI==\"AK0010200\" & INCIDENT.NUMBER==\"23000003\") |> \n   print(width=Inf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 21\n  SEGMENT STATE ORI       INCIDENT.NUMBER INCIDENT.DATE UCR.OFFENSE.CODE\n  <chr>   <dbl> <chr>     <chr>           <chr>         <chr>           \n1 02         50 AK0010200 23000003        20230101      23D             \n  OFFENSE.ATTEMPTED.COMPLETED SUSPECTED.OF.USING.1 SUSPECTED.OF.USING.2\n  <chr>                       <chr>                <chr>               \n1 C                           N                    <NA>                \n  SUSPECTED.OF.USING.3 LOCATION.TYPE NUMBER.OF.PREMISES.ENTERED METHOD.OF.ENTRY\n  <chr>                <chr>         <chr>                      <chr>          \n1 <NA>                 04            <NA>                       <NA>           \n  CRIMINAL.ACTIVITY.1.GANG.INFORMATION.1 CRIMINAL.ACTIVITY.2.GANG.INFORMATION.2\n  <chr>                                  <chr>                                 \n1 <NA>                                   <NA>                                  \n  CRIMINAL.ACTIVITY.3 WEAPON.FORCE.1 AUTOMATIC.INDICATOR.1 WEAPON.FORCE.2\n  <chr>               <chr>          <chr>                 <chr>         \n1 <NA>                <NA>           <NA>                  <NA>          \n  WEAPON.FORCE.3 BIAS.MOTIVATION\n  <chr>          <chr>          \n1 <NA>           88             \n```\n\n\n:::\n:::\n\n\n\nThis offense record describes a UCR code 23D, which is theft from a building. `OFFENSE.ATTEMPTED.COMPLETED` is `C` meaning it was a completed crime (not attempted). During the offense the offender was suspected of using narcotics (`SUSPECTED.OF.USING.1` marked as `N`). Location type is `04`, which is a Church/Synagogue/Temple.\n\nYou have noticed by now that NIBRS has a lot of codes, for states, offenses, location types, and there are many more. It might be handy to have a lookup table so we can join the codes to better English descriptions. All the information is in that Excel records description. Let's write some code to create a UCR lookup table.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ni <- which(fmtXL$Description==\"720 - Animal Cruelty Offenses - Animal Cruelty\")\nj <- which(fmtXL$Description==\"90Z - All Other Offenses - All Other Offenses\")\n\nOffenseLookup <- \n   strsplit(fmtXL$Description[i:j], \" - \") |>\n   do.call(rbind, args=_) |> # stack all the rows on top of each other\n   data.frame() |>\n   rename(UCRCode=X1, CrimeCat=X2, Crime=X3) |>\n   filter(UCRCode!=\"Group B Offenses\")\nhead(OffenseLookup)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  UCRCode                CrimeCat              Crime\n1     720 Animal Cruelty Offenses     Animal Cruelty\n2     200                   Arson              Arson\n3     13A        Assault Offenses Aggravated Assault\n4     13B        Assault Offenses     Simple Assault\n5     13C        Assault Offenses       Intimidation\n6     510                 Bribery            Bribery\n```\n\n\n:::\n:::\n\n\n\nNow for each UCR offense code we can look up its general crime category (`CrimeCat`) and its specific crime type (`Crime`). You can adapt this code to create other lookup tables for other codes, like a state code lookup table.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ni <- which(fmtXL$Description==\"50  = AK -Alaska\")\nj <- which(fmtXL$Description==\"49  =  WY -  Wyoming\")\n\nStateLookup <- \n   fmtXL$Description[i:j] |> \n   data.frame() |>\n   rename(temp=fmtXL.Description.i.j.) |>\n   mutate(StateCode=as.numeric(substring(temp,1,2)),\n          State=gsub(\".*([A-Z][A-Z]).*\",\"\\\\1\", temp)) |>\n   select(-temp) |>\n   arrange(StateCode)\nhead(StateLookup)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  StateCode State\n1         1    AL\n2         2    AZ\n3         3    AR\n4         4    CA\n5         5    CO\n6         6    CT\n```\n\n\n:::\n:::\n\n\n\n\n### Exercises\n1. How many Group A offenses were reported to the Philadelphia Police Department (ORI PAPEP0000)?\n\n2. What is the most commonly reported crime in Philadelphia? Use the OffenseLookup to replace the UCR codes with crime descriptions.\n\n\n## Property segment\n\nMoving on to the NIBRS property segment, we repeat the same steps as we did before, adapting to get the records description for property reports.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# select only the rows for property segment\ni <- grep('LEVEL \"03\"', fmtXL$DataField)\nj <- grep('LEVEL \"04\"', fmtXL$DataField)\n\nfmt <- fmtXL |>\n  slice((i+2):(j-3)) |>\n  filter(!is.na(Position) &\n         !(Position %in% c(\"14-22\",\"20-22\",\"58-102\",\"58-72\",\"103-132\")))\n\nfmtType <- fmt$TypeLength |> \n   substring(1,1) |>\n   case_match(\"A\"~\"c\",\"N\"~\"n\")\nfmtWidth <- fmt$TypeLength |> \n   substring(2) |>\n   as.numeric()\nfmtNames <- fmt$Description |>\n   strsplit(split = \" - \", fixed = TRUE) |>\n   sapply(head, n=1) |>\n   make.names() |>\n   gsub(\"\\\\.+(\\\\.|$)\", \"\\\\1\", x=_)\n```\n:::\n\n\n\n\nThere are two columns called `ESTIMATED.QUANTITY`. The second one represents thousandths of the first column. So, I'll rename the second one to have a unique name.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfmtNames\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"SEGMENT.LEVEL\"                      \"NUMERIC.STATE.CODE\"                \n [3] \"ORIGINATING.AGENCY.IDENTIFIER.ORI\"  \"INCIDENT.NUMBER\"                   \n [5] \"INCIDENT.DATE\"                      \"TYPE.PROPERTY.LOSS.ETC\"            \n [7] \"PROPERTY.DESCRIPTION\"               \"VALUE.OF.PROPERTY\"                 \n [9] \"DATE.RECOVERED\"                     \"NUMBER.OF.STOLEN.MOTOR.VEHICLES\"   \n[11] \"NUMBER.OF.RECOVERED.MOTOR.VEHICLES\" \"SUSPECTED.DRUG.TYPE\"               \n[13] \"ESTIMATED.QUANTITY\"                 \"ESTIMATED.QUANTITY\"                \n[15] \"TYPE.MEASUREMENT\"                   \"DRUG.INVOLVEMENT.2\"                \n[17] \"DRUG.INVOLVEMENT.3\"                 \"WINDOW.UCR.OFFENSE.CODE.1\"         \n[19] \"WINDOW.UCR.OFFENSE.CODE.2\"          \"WINDOW.UCR.OFFENSE.CODE.3\"         \n[21] \"WINDOW.UCR.OFFENSE.CODE.4\"          \"WINDOW.UCR.OFFENSE.CODE.5\"         \n[23] \"WINDOW.UCR.OFFENSE.CODE.6\"          \"WINDOW.UCR.OFFENSE.CODE.7\"         \n[25] \"WINDOW.UCR.OFFENSE.CODE.8\"          \"WINDOW.UCR.OFFENSE.CODE.9\"         \n[27] \"WINDOW.UCR.OFFENSE.CODE.10\"        \n```\n\n\n:::\n\n```{.r .cell-code}\nfmtNames[which(fmtNames==\"ESTIMATED.QUANTITY\")[2]] <- \n   \"ESTIMATED.QUANTITY.1000THS\"\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nnibrsProp03 <- read_fwf(\"2023-03.txt.gz\",\n                        col_positions = fwf_widths(fmtWidth),\n                        col_type=paste(fmtType,collapse=\"\")) |>\n   rename_with(~fmtNames) |>\n   mutate(VALUE.OF.PROPERTY=as.numeric(VALUE.OF.PROPERTY)) |>\n   rename(ORI     = ORIGINATING.AGENCY.IDENTIFIER.ORI,\n          SEGMENT = SEGMENT.LEVEL,\n          STATE   = NUMERIC.STATE.CODE)\n```\n:::\n\n\n\n\nLet's pull up the property record for the Fairbanks, Alaska incident 2300003 that we previously examined.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnibrsProp03 |>  \n   filter(ORI==\"AK0010200\" & INCIDENT.NUMBER==\"23000003\") |> \n   print(width=360)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 27\n  SEGMENT STATE ORI       INCIDENT.NUMBER INCIDENT.DATE TYPE.PROPERTY.LOSS.ETC\n  <chr>   <chr> <chr>     <chr>           <chr>         <chr>                 \n1 03      50    AK0010200 23000003        20230101      7                     \n  PROPERTY.DESCRIPTION VALUE.OF.PROPERTY DATE.RECOVERED NUMBER.OF.STOLEN.MOTOR~1\n  <chr>                            <dbl> <chr>          <chr>                   \n1 75                                 150 <NA>           <NA>                    \n  NUMBER.OF.RECOVERED.MOTOR.VEHICLES SUSPECTED.DRUG.TYPE ESTIMATED.QUANTITY\n  <chr>                              <chr>               <chr>             \n1 <NA>                               <NA>                <NA>              \n  ESTIMATED.QUANTITY.10~2 TYPE.MEASUREMENT DRUG.INVOLVEMENT.2 DRUG.INVOLVEMENT.3\n  <chr>                   <chr>            <chr>              <chr>             \n1 <NA>                    <NA>             <NA>               <NA>              \n  WINDOW.UCR.OFFENSE.CODE.1 WINDOW.UCR.OFFENSE.CODE.2 WINDOW.UCR.OFFENSE.CODE.3\n  <chr>                     <chr>                     <chr>                    \n1 <NA>                      <NA>                      <NA>                     \n# i abbreviated names: 1: NUMBER.OF.STOLEN.MOTOR.VEHICLES, 2: ESTIMATED.QUANTITY.1000THS\n# i 7 more variables: WINDOW.UCR.OFFENSE.CODE.4 <chr>, WINDOW.UCR.OFFENSE.CODE.5 <chr>, WINDOW.UCR.OFFENSE.CODE.6 <chr>, WINDOW.UCR.OFFENSE.CODE.7 <chr>, WINDOW.UCR.OFFENSE.CODE.8 <chr>, WINDOW.UCR.OFFENSE.CODE.9 <chr>, WINDOW.UCR.OFFENSE.CODE.10 <chr>\n```\n\n\n:::\n:::\n\n\n\nThis incident involved something stolen (`TYPE.PROPERTY.LOSS.ETC` equal to 7). The thing that was stolen was \"Portable Electronic Communications\" (`PROPERTY.DESCRIPTION` code is 75), which most likely means a mobile phone. The estimated value of the phone was $150.\n\nImportantly, the value of property stored in `VALUE.OF.PROPERTY` is not always the actual value. NIBRS codes certain special values in `VALUE.OF.PROPERTY`.\n\n- 1 = the value of the property is unknown\n- NA = the property was seized (`TYPE.PROPERTY.LOSS.ETC` is 6) and the seized property was drugs/narcotics (`PROPERTY.DESCRIPTION` is 10)\n- the value of drugs will be present if they were damaged, destroyed, or stolen when the offense is not a narcotics violation, such as arson, burglary, or robbery.\n\n\n## Victim segment\n\nWe repeat the same process for the victim segment.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ni <- grep('LEVEL \"04\"', fmtXL$DataField)\nj <- grep('LEVEL \"05\"', fmtXL$DataField)\n\nfmt <- fmtXL |>\n  slice((i+1):(j-3)) |>\n  filter(!is.na(Position) &\n         !(Position %in% c(\"37-66\",\"74-77\",\"79-83\",\"84-123\")))\n\nfmtType <- fmt$TypeLength |> \n   substring(1,1) |>\n   case_match(\"A\"~\"c\",\"N\"~\"n\")\nfmtWidth <- fmt$TypeLength |> \n   substring(2) |>\n   as.numeric()\nfmtNames <- fmt$Description |>\n   strsplit(split = \" - \", fixed = TRUE) |>\n   sapply(head, n=1) |>\n   make.names() |>\n   gsub(\"\\\\.+(\\\\.|$)\", \"\\\\1\", x=_)\n\nnibrsVic04 <- read_fwf(\"2023-04.txt.gz\",\n                        col_positions = fwf_widths(fmtWidth),\n                        col_type=paste(fmtType,collapse=\"\")) |>\n   rename_with(~fmtNames) |>\n   rename(ORI     = ORIGINATING.AGENCY.IDENTIFIER.ORI,\n          SEGMENT = SEGMENT.LEVEL,\n          STATE   = NUMERIC.STATE.CODE)\n```\n:::\n\n\n\n\n\nLet's pull up the property record for the Fairbanks, Alaska incident 2300003 that we previously examined.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnibrsVic04 |>\n   filter(ORI==\"AK0010200\" & INCIDENT.NUMBER==\"23000003\") |> \n   print(width=360)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 44\n  SEGMENT STATE ORI       INCIDENT.NUMBER INCIDENT.DATE VICTIM.SEQUENCE.NUMBER\n  <chr>   <chr> <chr>     <chr>           <chr>                          <dbl>\n1 04      50    AK0010200 23000003        20230101                           1\n  UCR.OFFENSE.CODE.1 UCR.OFFENSE.CODE.2 UCR.OFFENSE.CODE.3 UCR.OFFENSE.CODE.4\n  <chr>              <chr>              <chr>              <chr>             \n1 23D                <NA>               <NA>               <NA>              \n  UCR.OFFENSE.CODE.5 UCR.OFFENSE.CODE.6 UCR.OFFENSE.CODE.7 UCR.OFFENSE.CODE.8\n  <chr>              <chr>              <chr>              <chr>             \n1 <NA>               <NA>               <NA>               <NA>              \n  UCR.OFFENSE.CODE.9 UCR.OFFENSE.CODE.10 TYPE.OF.VICTIM AGE.OF.VICTIM\n  <chr>              <chr>               <chr>          <chr>        \n1 <NA>               <NA>                I              61           \n  SEX.OF.VICTIM RACE.OF.VICTIM ETHNICITY.OF.VICTIM RESIDENT.STATUS.OF.VICTIM\n  <chr>         <chr>          <chr>               <chr>                    \n1 M             W              N                   R                        \n# i 22 more variables: CIRCUMSTANCE.1 <chr>, CIRCUMSTANCE.2 <chr>, ADDITIONAL.JUSTIFIABLE.HOMICIDE.CIRCUMSTANCES <chr>, INJURY.1 <chr>, INJURY.2 <chr>, INJURY.3 <chr>, INJURY.4 <chr>, INJURY.5 <chr>, OFFENDER.NUMBER.TO.BE.RELATED <chr>, RELATIONSHIP.OF.VICTIM.TO.OFFENDER <chr>, RELATIONSHIP.2 <chr>, RELATIONSHIP.3 <chr>, RELATIONSHIP.4 <chr>,\n#   RELATIONSHIP.5 <chr>, RELATIONSHIP.6 <chr>, RELATIONSHIP.7 <chr>, RELATIONSHIP.8 <chr>, RELATIONSHIP.9 <chr>, RELATIONSHIP.10 <chr>, Type.of.Activity.Officer.Circumstance <chr>, Assignment.Type.Officer <chr>, ORI.Other.Jurisdiction.Officer <chr>\n```\n\n\n:::\n:::\n\n\n\nHere we see that `TYPE.OF.VICTIM` is I, meaning that the victim was an individual (instead of a business, government, society, or some other institutional victim). The individual is a 61 year old non-Hispanic white male. No other information is available for this victim, but police can record the relationship between the victim and offender, whether the victim sustained any injuries, what drew the officer to the victim (such as a traffic stop or responding to a call for service), and whether the victim killed the offender in self-defense.\n\n## Offender segment\n\nA few more segments to go. Now we will read in the data on the offenders.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ni <- grep('LEVEL \"05\"', fmtXL$DataField)\nj <- grep('LEVEL \"06\"', fmtXL$DataField)\n\nfmt <- fmtXL |>\n  slice((i+1):(j-3)) |>\n  filter(!is.na(Position))\n\nfmtType <- fmt$TypeLength |> \n   substring(1,1) |>\n   case_match(\"A\"~\"c\",\"N\"~\"n\")\nfmtWidth <- fmt$TypeLength |> \n   substring(2) |>\n   as.numeric()\nfmtNames <- fmt$Description |>\n   strsplit(split = \" - \", fixed = TRUE) |>\n   sapply(head, n=1) |>\n   make.names() |>\n   gsub(\"\\\\.+(\\\\.|$)\", \"\\\\1\", x=_)\n\nnibrsOff05 <- read_fwf(\"2023-05.txt.gz\",\n                       col_positions = fwf_widths(fmtWidth),\n                       col_type=paste(fmtType,collapse=\"\")) |>\n   rename_with(~fmtNames) |>\n   rename(ORI     = ORIGINATING.AGENCY.IDENTIFIER.ORI,\n          SEGMENT = SEGMENT.LEVEL,\n          STATE   = NUMERIC.STATE.CODE)\n```\n:::\n\n\n\n\nIn some years the offender data has some text in the `OFFENDER.SEQUENCE.NUMBER` for some reason, like setting the `OFFENDER.SEQUENCE.NUMBER` to \"##\". We told `read_fwf()` to expect a numeric value for this column, marked by the \"n\" in the `fmtType` column here.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(fmtNames, fmtType)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                            fmtNames fmtType\n1                      SEGMENT.LEVEL       c\n2                 NUMERIC.STATE.CODE       c\n3  ORIGINATING.AGENCY.IDENTIFIER.ORI       c\n4                    INCIDENT.NUMBER       c\n5                      INCIDENT.DATE       c\n6           OFFENDER.SEQUENCE.NUMBER       n\n7                    AGE.OF.OFFENDER       c\n8                    SEX.OF.OFFENDER       c\n9                   RACE.OF.OFFENDER       c\n10             Ethnicity.OF.OFFENDER       c\n```\n\n\n:::\n:::\n\n\n\n\nIf this should happen, you can explore the problem a little to find the problem in the original data using `problems(nibrsOff05)`. My preferred solution is just to read all columns in as text and worry about fixing the non-numeric values later. Here I set all of the value of `col_type` to character.\n\n<!-- No such errors occur with 2023 data -->\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnibrsOff05 <- read_fwf(\"2023-05.txt.gz\",\n                       col_positions = fwf_widths(fmtWidth),\n                       col_type=\"cccccccccc\") |>\n   rename_with(~fmtNames) |>\n   rename(ORI=ORIGINATING.AGENCY.IDENTIFIER.ORI,\n          SEGMENT=SEGMENT.LEVEL,\n          STATE=NUMERIC.STATE.CODE)\n```\n:::\n\n\n\n\nWe have no description of the offender in this case.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnibrsOff05 |>\n   filter(ORI==\"AK0010200\" & INCIDENT.NUMBER==\"23000003\") |> \n   print(width=360)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 10\n  SEGMENT STATE ORI       INCIDENT.NUMBER INCIDENT.DATE OFFENDER.SEQUENCE.NUMBER\n  <chr>   <chr> <chr>     <chr>           <chr>                            <dbl>\n1 05      50    AK0010200 23000003        20230101                             0\n  AGE.OF.OFFENDER SEX.OF.OFFENDER RACE.OF.OFFENDER Ethnicity.OF.OFFENDER\n  <chr>           <chr>           <chr>            <chr>                \n1 <NA>            <NA>            <NA>             <NA>                 \n```\n\n\n:::\n:::\n\n\n\n\n\n## Arrestee segment\n\nIf the reporting agency arrests an offender for the reported offense after submitting the initial report, the agency later submits an updated arrestee segment as an update to the initial report. The [NIBRS User's Manual](https://le.fbi.gov/file-repository/nibrs-user-manual.pdf) notes that as cases develop, police can update, delete, or add to previously submitted records. However, the submission date cuts off on March 15 of subsequent year.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# select only the rows for victim segment\ni <- grep('LEVEL \"06\"', fmtXL$DataField)\nj <- grep('LEVEL \"07\"', fmtXL$DataField)\n\nfmt <- fmtXL |>\n  slice((i+2):(j-3)) |>\n  filter(!is.na(Position) &\n         !(Position %in% c(\"61-66\",\"75-104\")))\n\nfmtType <- fmt$TypeLength |> \n   substring(1,1) |>\n   case_match(\"A\"~\"c\",\"N\"~\"n\")\nfmtWidth <- fmt$TypeLength |> \n   substring(2) |>\n   as.numeric()\nfmtNames <- fmt$Description |>\n   strsplit(split = \" - \", fixed = TRUE) |>\n   sapply(head, n=1) |>\n   make.names() |>\n   gsub(\"\\\\.+(\\\\.|$)\", \"\\\\1\", x=_)\n\nnibrsArr06 <- read_fwf(\"2023-06.txt.gz\",\n                       col_positions = fwf_widths(fmtWidth),\n                       col_type=paste(fmtType,collapse=\"\")) |>\n   rename_with(~fmtNames) |>\n   rename(ORI     = ORIGINATING.AGENCY.IDENTIFIER.ORI,\n          SEGMENT = SEGMENT.LEVEL,\n          STATE   = NUMERIC.STATE.CODE)\n```\n:::\n\n\n\n\nNo arrests were made in this case. You probably already suspected this since there was no description of an offender in this case either.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnibrsArr06 |>\n   filter(ORI==\"AK0010200\" & INCIDENT.NUMBER==\"23000003\") |>\n   count()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 1\n      n\n  <int>\n1     0\n```\n\n\n:::\n:::\n\n\n\n\nGroup B arrestees are kept in a separate data file. Group B offenses are almost all crimes against society, such as bad checks, non-violent family offenses, curfew/loitering/vagrancy, liquor law violations, disorderly conduct, peeping Tom, DUI, trespassing, drunkenness. These offenses are only reported if the police made an arrest. That is, someone calls the police reporting some disorderly conduct, the police do not record that in NIBRS unless they end up making an arrest as a result of the call.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ni <- grep('LEVEL \"07\"', fmtXL$DataField)\n\nfmt <- fmtXL |>\n  slice(-(1:i)) |>\n  filter(!is.na(Position) &\n         !(Position %in% \"44-49\"))\n\nfmtType <- fmt$TypeLength |> \n   substring(1,1) |>\n   case_match(\"A\"~\"c\",\"N\"~\"n\")\nfmtWidth <- fmt$TypeLength |> \n   substring(2) |>\n   as.numeric()\nfmtNames <- fmt$Description |>\n   strsplit(split = \" - \", fixed = TRUE) |>\n   sapply(head, n=1) |>\n   make.names() |>\n   gsub(\"\\\\.+(\\\\.|$)\", \"\\\\1\", x=_)\n\nnibrsArB07 <- read_fwf(\"2023-07.txt.gz\",\n                       col_positions = fwf_widths(fmtWidth),\n                       col_type=paste(fmtType,collapse=\"\")) |>\n   rename_with(~fmtNames) |>\n   rename(ORI     = ORIGINATING.AGENCY.IDENTIFIER.ORI,\n          SEGMENT = SEGMENT.LEVEL,\n          STATE   = NUMERIC.STATE.CODE)\n```\n:::\n\n\n\n\nThe Fairbanks case we traced through the other NIBRS tables was not a Group B offense, so it will have no records in this table. Instead, let's examine the first two Fairbanks Group B offenses reported. I have gone ahead and joined the Group B arrestee table with the `OffenseLookup` so the offenses are easier to interpret.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnibrsArB07 |>\n   filter(ORI==\"AK0010200\") |>\n   head(2) |>\n   left_join(OffenseLookup, by=join_by(UCR.GROUP.B.ARREST.OFFENSE.CODE==UCRCode)) |>\n   print(width=360)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 x 20\n  SEGMENT STATE ORI       ARREST.TRANSACTION.INCIDENT.NUMBER ARREST.DATE\n  <chr>   <chr> <chr>     <chr>                              <chr>      \n1 07      50    AK0010200 50901                              20230206   \n2 07      50    AK0010200 50908                              20230102   \n  ARRESTEE.SEQUENCE.NUMBER CITY.SUBMISSION TYPE.OF.ARREST\n                     <dbl> <chr>           <chr>         \n1                        1 <NA>            T             \n2                        1 <NA>            O             \n  UCR.GROUP.B.ARREST.OFFENSE.CODE WEAPON.1 AUTOMATIC.INDICATOR.1 WEAPON.2\n  <chr>                           <chr>    <chr>                 <chr>   \n1 90F                             01       <NA>                  <NA>    \n2 90C                             01       <NA>                  <NA>    \n  AGE.OF.ARRESTEE SEX.OF.ARRESTEE RACE.OF.ARRESTEE ETHNICITY.OF.ARRESTEE\n  <chr>           <chr>           <chr>            <chr>                \n1 45              M               W                N                    \n2 35              F               I                N                    \n  RESIDENT.STATUS.OF.ARRESTEE DISPOSITION.OF.ARRESTEE.UNDER.18 CrimeCat    Crime\n  <chr>                       <chr>                            <chr>       <chr>\n1 R                           <NA>                             Family Off~ Fami~\n2 N                           <NA>                             Disorderly~ Diso~\n```\n\n\n:::\n:::\n\n\n\nPolice arrested the first individual listed here based on a warrant for a prior incident (`TYPE.OF.ARREST` is \"T\") for non-violent family offenses (e.g. neglect, not paying alimony). `WEAPON.1` equal to \"01\" indicates that the individual was unarmed. Age, race, sex information is also provided in this arrestee table.\n\n## Batch Header segment\n\nThe final segment we will read in is the batch header file. This file contains basic information about the agencies reporting to NIBRS. It contains one record for each law enforcement agency.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfmt <- read_excel(\"NIBRS Records Description updated.xlsx\",\n                  skip=4) |>\n       data.frame() |>\n       filter(!is.na(Position) &\n              !(Position %in% c(\"106-225\", # data on county can repeat 5x\n                                \"234-269\", # indicators for 12 months\n                                \"234\",\"235\",\"236\", # detailed January reporting\n                                \"270-284\"))) # county codes up to 5x\n\nfmtType <- fmt$Type..Length |> \n   substring(1,1) |>\n   case_match(\"A\"~\"c\",\"N\"~\"n\")\nfmtWidth <- fmt$Type..Length |> \n   substring(2) |>\n   as.numeric()\nfmtNames <- fmt$Description |>\n   strsplit(split = \" - \", fixed = TRUE) |>\n   sapply(head, n=1) |>\n   make.names() |>\n   gsub(\"\\\\.+(\\\\.|$)\", \"\\\\1\", x=_)\n\nnibrsBH <- read_fwf(\"2023-BH.txt.gz\",\n                    col_positions = fwf_widths(fmtWidth),\n                    col_type=paste(fmtType,collapse=\"\")) |>\n   rename_with(~fmtNames) |>\n   rename(ORI     = ORIGINATING.AGENCY.IDENTIFIER.ORI,\n          SEGMENT = SEGMENT.LEVEL,\n          STATE   = NUMERIC.STATE.CODE)\n```\n:::\n\n\n\n\nSome particularly important columns are `DATE.ORI.WENT.NIBRS` containing the date when the agency first reported data to NIBRS, the `AGENCY.INDICATOR` describing what type of law enforcement agency it is (eg. city, county, state, college, tribal) or whether the agency relies on another to file its NIBRS reports (such as a transit police that reports through the municipal police). The batch header contains an estimate of the size of the population that the agency covers, but breaks down the reporting by county. Oklahoma City, for example, intersects with four different counties, so that the Oklahoma City Police Department reports their population separately for each.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnibrsBH |> \n   filter(ORI==\"OK0550600\") |> \n   select(ORI, CITY.NAME, STATE.ABBREVIATION,\n          starts_with(\"CURRENT.POPULATION\")) |>\n   print(width=360)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 8\n  ORI       CITY.NAME     STATE.ABBREVIATION CURRENT.POPULATION.1\n  <chr>     <chr>         <chr>                             <dbl>\n1 OK0550600 OKLAHOMA CITY OK                               532970\n  CURRENT.POPULATION.2 CURRENT.POPULATION.3 CURRENT.POPULATION.4\n                 <dbl>                <dbl>                <dbl>\n1                88049                79665                   80\n  CURRENT.POPULATION.5\n                 <dbl>\n1                    0\n```\n\n\n:::\n:::\n\n\n\nI find it helpful to have a total population covered.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnibrsBH <- nibrsBH |>\n   mutate(TOTAL.POP=rowSums(across(starts_with(\"CURRENT.POP\")), na.rm=TRUE))\n```\n:::\n\n\n\n\nThe batch header also contains information on whether the agency regularly reports their data. For example, here is the record for San Jose, California.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnibrsBH |> filter(ORI==\"CA0431300\") |> \n   select(ORI, CITY.NAME, STATE.ABBREVIATION, DATE.ORI.WENT.NIBRS,\n          NUMBER.OF.MONTHS.REPORTED, JANUARY:DECEMBER) |>\n   print(width=1000)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 17\n  ORI       CITY.NAME STATE.ABBREVIATION DATE.ORI.WENT.NIBRS\n  <chr>     <chr>     <chr>              <chr>              \n1 CA0431300 SAN JOSE  CA                 20230401           \n  NUMBER.OF.MONTHS.REPORTED JANUARY FEBRUARY MARCH APRIL MAY   JUNE  JULY \n  <chr>                     <chr>   <chr>    <chr> <chr> <chr> <chr> <chr>\n1 07                        NNN     NNN      NNN   NYN   NYN   NYN   NYN  \n  AUGUST SEPTEMBER OCTOBER NOVEMBER DECEMBER\n  <chr>  <chr>     <chr>   <chr>    <chr>   \n1 NYN    NYN       NYN     NNN      NNN     \n```\n\n\n:::\n:::\n\n\n\nThis record shows that they started reporting to NIBRS in April 2023 and reported for a total of 7 months. The `JANUARY` to `DECEMBER` columns describe more precisely what the agency submitted. The \"NNN\" indicates no reporting of any kind to NIBRS, occurring January, February, and March and then again in November and December. The \"NYN\" pattern means that the agency did not report (the first \"N\") a \"Zero Report\" (a formal notice of no crime reports), did report Group A or Group B offenses (the \"Y\"), and did not report any window records (the final N, meaning there was no partial reporting, like an arrest without an associated offense report).\n\nLet's explore which agencies are reporting to NIBRS so we have a better sense of what NIBRS includes and excludes.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# NYPD, LAPD, and Nashville PD\nnibrsBH |>  \n   filter(ORI %in% c(\"NY0303000\",\"CA0194200\",\"TN0190100\")) |>    \n   select(ORI, CITY.NAME, STATE.ABBREVIATION, DATE.ORI.WENT.NIBRS,\n          NUMBER.OF.MONTHS.REPORTED, JANUARY:DECEMBER) |>\n   print(width=Inf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 x 17\n  ORI       CITY.NAME   STATE.ABBREVIATION DATE.ORI.WENT.NIBRS\n  <chr>     <chr>       <chr>              <chr>              \n1 CA0194200 LOS ANGELES CA                 <NA>               \n2 NY0303000 NEW YORK    NY                 20230101           \n3 TN0190100 NASHVILLE   TN                 19991001           \n  NUMBER.OF.MONTHS.REPORTED JANUARY FEBRUARY MARCH APRIL MAY   JUNE  JULY \n  <chr>                     <chr>   <chr>    <chr> <chr> <chr> <chr> <chr>\n1 00                        NNN     NNN      NNN   NNN   NNN   NNN   NNN  \n2 12                        NYN     NYN      NYN   NYN   NYN   NYN   NYN  \n3 12                        NYN     NYN      NYN   NYN   NYN   NYN   NYN  \n  AUGUST SEPTEMBER OCTOBER NOVEMBER DECEMBER\n  <chr>  <chr>     <chr>   <chr>    <chr>   \n1 NNN    NNN       NNN     NNN      NNN     \n2 NYN    NYN       NYN     NYN      NYN     \n3 NYN    NYN       NYN     NYN      NYN     \n```\n\n\n:::\n:::\n\n\n\nLos Angeles PD has never reported to NIBRS, New York City started their NIBRS reporting in 2023, and Nashville has been reporting to NIBRS for 25 years, since 1999 and continues to report its crime data every month.\n\nWhich states seem to have good reporting?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnibrsBH |>\n  filter(is.na(COVERED.BY.ORI)) |> # remove those reporting through another\n  count(STATE.ABBREVIATION, AGENCY.NIBRS.FLAG) |>\n  pivot_wider(names_from = AGENCY.NIBRS.FLAG, \n              values_from = n, \n              values_fill = 0) |>\n  rename(inNIBRS=A, notInNIBRS=`NA`) |>\n  print(n=Inf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 54 x 3\n   STATE.ABBREVIATION inNIBRS notInNIBRS\n   <chr>                <int>      <int>\n 1 AK                      32          7\n 2 AL                     415         31\n 3 AR                     313          3\n 4 AZ                     100         26\n 5 CA                     634        225\n 6 CO                     245          4\n 7 CT                     108          0\n 8 DC                       2          1\n 9 DE                      63          0\n10 FL                     133        625\n11 GA                     499        164\n12 GM                       1          1\n13 HI                       4          0\n14 IA                     286          3\n15 ID                     112          0\n16 IL                     635        288\n17 IN                     260         97\n18 KS                     406          2\n19 KY                     436          1\n20 LA                     165         70\n21 MA                     398         22\n22 MD                     139         18\n23 ME                     131          0\n24 MI                     634          2\n25 MN                     409          2\n26 MO                     537         62\n27 MS                     168        108\n28 MT                     115          0\n29 NB                     283          4\n30 NC                     442         93\n31 ND                     111          0\n32 NH                     216          5\n33 NJ                     346        232\n34 NM                     104         26\n35 NV                      61         11\n36 NY                     185        405\n37 OH                     813         42\n38 OK                     462          0\n39 OR                     234          3\n40 PA                     171       1306\n41 PR                       0          1\n42 RI                      48          1\n43 SC                     513          1\n44 SD                     141          0\n45 TN                     411          1\n46 TX                    1393         84\n47 UT                     144          2\n48 VA                     420          0\n49 VI                       0          2\n50 VT                      87          0\n51 WA                     270          0\n52 WI                     394         64\n53 WV                     426          4\n54 WY                      53         17\n```\n\n\n:::\n:::\n\n\n\nThe states that have a large number of non-reporting agencies are California, Florida, Georgia, Illinois, New Jersey, New York, and Pennsylvania. These are rather large states. In the event that the non-reporting agencies are small, it is probably better to assess the percentage of the population covered by NIBRS rather than counting non-reporting agencies.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnibrsBH |>\n  filter(is.na(COVERED.BY.ORI)) |> # remove those reporting through another\n  group_by(STATE.ABBREVIATION, AGENCY.NIBRS.FLAG) |>\n  summarize(populationCovered=sum(TOTAL.POP)) |>\n  pivot_wider(names_from = AGENCY.NIBRS.FLAG, \n              values_from = populationCovered,\n              values_fill = 0) |>\n  rename(inNIBRS=A, notInNIBRS=`NA`) |>\n  mutate(percentCovered=round(100*inNIBRS/(inNIBRS+notInNIBRS))) |>\n  arrange(percentCovered) |>\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 x 4\n# Groups:   STATE.ABBREVIATION [10]\n   STATE.ABBREVIATION  inNIBRS notInNIBRS percentCovered\n   <chr>                 <dbl>      <dbl>          <dbl>\n 1 PR                        0    3205691              0\n 2 VI                        0      83265              0\n 3 FL                  9583627   13027099             42\n 4 PA                  5605372    7356311             43\n 5 AK                   445330     288076             61\n 6 AZ                  4664949    2766395             63\n 7 CA                 25034801   13930392             64\n 8 MS                  1905988    1033702             65\n 9 NJ                  6351608    2939233             68\n10 NY                 13614572    5956644             70\n```\n\n\n:::\n:::\n\n\n\nThe states with large populations that NIBRS does not cover are Florida, Pennsylvania, and California.\n\n## Saving our work\nSave the NIBRS 2023 data in its R format. If you ever want to reload the data, there will be no need to rerun all the previous steps. You can just use `load(\"nibrs2023.RData\")` to retrieve the data. It will be quite large and can take a few minutes to reload.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsave(nibrsAdmin01, nibrsCrm02, nibrsProp03, nibrsVic04, nibrsOff05,\n     nibrsArr06, nibrsArB07, nibrsBH,\n     fmtXL,\n     file=\"nibrs2023.RData\",\n     compress = TRUE)\n```\n:::\n\n\n\n\n# Examples using NIBRS\n\nFor several of these examples we are going to need to work with dates. So, let's start by converting all the dates to proper date formats.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnibrsCrm02 <- nibrsCrm02 |>\n   mutate(INCIDENT.DATE = ymd(INCIDENT.DATE))\nnibrsArr06 <- nibrsArr06 |>\n   mutate(INCIDENT.DATE = ymd(INCIDENT.DATE),\n          ARREST.DATE = ymd(ARREST.DATE))\n```\n:::\n\n\n\n\n## What percentage of burglaries result in an arrest? \n\nRemember that arrest data only go through March 15 of the subsequent year. Note that the arrest will show up only if the agency records the arrest by March 15, 2024. Let's start this example by finding the right UCR codes for burglary. Note that `str_detect()` is equivalent to `grepl()`. You may use either of them in such `filter()` statements.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nOffenseLookup |> filter(str_detect(Crime, \"[Bb]urglary\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  UCRCode                     CrimeCat                        Crime\n1     220 Burglary/Breaking & Entering Burglary/Breaking & Entering\n```\n\n\n:::\n:::\n\n\n\nWe will use UCR code 220 to select all the burglary offenses and check that `OFFENSE.ATTEMPTED.COMPLETED` equals \"C\" to eliminate the attempted burglaries.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnibrsCrm02 |>\n  filter(UCR.OFFENSE.CODE==\"220\" &            # burglary offense code \n         OFFENSE.ATTEMPTED.COMPLETED==\"C\") |> # completed\n  select(ORI, INCIDENT.NUMBER) |> # incidents are only unique within ORI\n  distinct() |> # remove any duplicate ORI/INCIDENT.NUMBER combos\n  # compress arrest data to ORI, INCIDENT.NUMBER, and first arrest\n  left_join(nibrsArr06 |>\n               group_by(ORI, INCIDENT.NUMBER) |>\n               summarize(dataFirstArrest = min(ARREST.DATE, na.rm=TRUE),\n                         .groups=\"drop\"),\n            by = join_by(ORI, INCIDENT.NUMBER)) |>\n  summarize(pctArrest = mean(!is.na(dataFirstArrest)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 1\n  pctArrest\n      <dbl>\n1     0.136\n```\n\n\n:::\n:::\n\n\n\n\n## What percentage of crimes are cleared with an arrest by month in which the offense occurred?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnibrsCrm02 |>\n  mutate(INCIDENT.MONTH=month(INCIDENT.DATE, label=TRUE)) |>\n  select(ORI, INCIDENT.NUMBER, INCIDENT.MONTH) |>\n  distinct() |>\n  left_join(nibrsArr06 |>\n               group_by(ORI, INCIDENT.NUMBER) |>\n               summarize(dataFirstArrest = min(ARREST.DATE, na.rm=TRUE),\n                         .groups=\"drop\"),\n            by = join_by(ORI, INCIDENT.NUMBER)) |>\n  group_by(INCIDENT.MONTH) |>\n  summarize(pctArrest = mean(!is.na(dataFirstArrest)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 x 2\n   INCIDENT.MONTH pctArrest\n   <ord>              <dbl>\n 1 Jan                0.246\n 2 Feb                0.248\n 3 Mar                0.249\n 4 Apr                0.248\n 5 May                0.244\n 6 Jun                0.241\n 7 Jul                0.241\n 8 Aug                0.242\n 9 Sep                0.244\n10 Oct                0.238\n11 Nov                0.243\n12 Dec                0.242\n```\n\n\n:::\n:::\n\n\n\n\n## What is the range of times to arrest for crimes resulting in arrest?\n\nThis next example shows the issue with the March 15 cutoff for reporting to NIBRS. Have a look at the average time and maximum time to arrest by month of the incident. The results seem to suggest that crimes resulting in arrest from January take a lot longer to produce the arrest than crimes in December. However, those January crimes have 15 months to produce an arrest (January 2023 to March 15, 2024) while the December arrests have only three months to produce an arrest before NIBRS reporting closes for the year. The observed pattern is entirely an artifact of the NIBRS data collection indicating that calculating clearance rates or time to clearance requires more care.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnibrsArr06 |>\n   group_by(ORI, INCIDENT.NUMBER) |>\n   summarize(dateFirstArrest = min(ARREST.DATE, na.rm=TRUE),\n             .groups=\"drop\") |>\n   left_join(nibrsCrm02 |> \n                select(ORI, INCIDENT.NUMBER, INCIDENT.DATE) |>\n                distinct(),\n             by = join_by(ORI, INCIDENT.NUMBER)) |>\n   mutate(timeToArrest = difftime(dateFirstArrest, INCIDENT.DATE, \n                                  units=\"days\") ,\n          INCIDENT.MONTH = month(INCIDENT.DATE, label=TRUE)) |>\n   group_by(INCIDENT.MONTH) |>\n   summarize(mean=mean(timeToArrest, na.rm=TRUE),\n             max=max(timeToArrest,  na.rm=TRUE)) |>\n   print(width=Inf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 x 3\n   INCIDENT.MONTH mean           max     \n   <ord>          <drtn>         <drtn>  \n 1 Jan            11.864666 days 451 days\n 2 Feb             9.946931 days 423 days\n 3 Mar             9.304757 days 398 days\n 4 Apr             8.638813 days 361 days\n 5 May             8.325869 days 332 days\n 6 Jun             7.769507 days 305 days\n 7 Jul             7.028547 days 275 days\n 8 Aug             6.381894 days 249 days\n 9 Sep             5.575103 days 213 days\n10 Oct             4.851006 days 185 days\n11 Nov             3.846566 days 155 days\n12 Dec             2.895208 days 125 days\n```\n\n\n:::\n:::\n\n\n\n\nFor a more fair comparison across months we can look at the percentage of crimes that result in an arrest within two months of the crime incident date. Technically, crimes on December 31st have until March 15th to have any arrests recorded (75 days), but I am going to set the threshold to within 60 days just in case it takes a few days for arrests in February for December crimes to get posted to NIBRS. Here we see that the percentage of crimes cleared with an arrest within 60 days is nearly constant across month of the year.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnibrsCrm02 |>\n   select(ORI, INCIDENT.NUMBER, INCIDENT.DATE) |>\n   distinct() |>\n   left_join(nibrsArr06 |> \n                group_by(ORI, INCIDENT.NUMBER, ARREST.DATE) |>\n                summarize(dateFirstArrest = min(ARREST.DATE, na.rm=TRUE),\n                          .groups = \"drop\"),\n             by = join_by(ORI, INCIDENT.NUMBER)) |>\n   mutate(timeToArrest = difftime(dateFirstArrest, INCIDENT.DATE, \n                                  units=\"days\"),\n          arrest2Months = as.numeric(!is.na(timeToArrest) & timeToArrest <= 60),\n          INCIDENT.MONTH = month(INCIDENT.DATE, label=TRUE)) |>\n   group_by(INCIDENT.MONTH) |>\n   summarize(mean=mean(arrest2Months, na.rm=TRUE)) |>\n   print(width=Inf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 x 2\n   INCIDENT.MONTH  mean\n   <ord>          <dbl>\n 1 Jan            0.234\n 2 Feb            0.238\n 3 Mar            0.239\n 4 Apr            0.239\n 5 May            0.235\n 6 Jun            0.232\n 7 Jul            0.233\n 8 Aug            0.235\n 9 Sep            0.238\n10 Oct            0.233\n11 Nov            0.240\n12 Dec            0.241\n```\n\n\n:::\n:::\n\n\n\n\n# Exercises\n\n3. How many offenses are shootings? That is, the offense was aggravated assault (13A), and the offense was completed (C), and the weapon involved was a firearm (11, 12, 13, 14, 15).\n\n4. What is the race distribution of shooting victims?\n\n5. How many cases are recorded as justifiable homicides? Note the special codes in the NIBRS documentation file. \n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{ll}\n\\toprule\nCode & Description\\\\\n\\midrule\n20 & Criminal killed by private citizen\\\\\n\\cmidrule{1-2}\\pagebreak[0]\n21 & Criminal killed by police officer\\\\\n\\cmidrule{1-2}\\pagebreak[0]\nA & Criminal attacked police officer and that officer killed criminal\\\\\n\\cmidrule{1-2}\\pagebreak[0]\nB & Criminal attacked fellow police officer and criminal killed by another police officer\\\\\n\\cmidrule{1-2}\\pagebreak[0]\nC & Criminal attacked a civilian\\\\\n\\cmidrule{1-2}\\pagebreak[0]\nD & Criminal attempted flight from a crime\\\\\n\\cmidrule{1-2}\\pagebreak[0]\nE & Criminal killed in commission of a crime\\\\\n\\cmidrule{1-2}\\pagebreak[0]\nF & Criminal resisted arrest\\\\\n\\cmidrule{1-2}\\pagebreak[0]\nG & Unable to determine/not enough information\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n\n\nOther data sources show that the total number of fatal police shooting victims is about 1,000 per year.\n\n6. Does NIBRS indicate that retail theft is rising? This exercise will involve a lot more work, including acquiring NIBRS data from multiple years. First, listen to the story \"[Is retail theft really rising?](https://www.marketplace.org/2023/09/11/is-retail-theft-really-rising/)\" featuring Kai Ryssdal and Livi Burdette recorded on September 11, 2023. In the discussion, one reporter seems to indicate that there are no national data on retail theft. Now that you have worked through this script and worked with NIBRS, you can see that retail theft is a UCR code reportable to NIBRS. Now some stores might not report retail theft to the police, but such non-reporting plagues all crime types. But you can evaluate whether reports of retail theft are increasing or decreasing over time. When examining trends over the last several years, make sure to consider that some agencies, like NYPD, just started reporting in 2023. Best to exclude them if you wish to compare trends from 2021 to the present. So, do the NIBRS data indicate that retail theft is rising?\n\n# Answers to the exercises\n\n1. How many Group A offenses were reported to the Philadelphia Police Department (ORI PAPEP0000)?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnibrsCrm02 |> filter(ORI==\"PAPEP0000\") |> count()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 1\n       n\n   <int>\n1 170168\n```\n\n\n:::\n:::\n\n\n\n\n2. What is the most commonly reported crime in Philadelphia? Use the OffenseLookup to replace the UCR codes with crime descriptions.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnibrsCrm02 |>\n   filter(ORI==\"PAPEP0000\") |>\n   count(UCR.OFFENSE.CODE) |>\n   slice_max(n) |>\n   left_join(OffenseLookup, \n             by=join_by(UCR.OFFENSE.CODE==UCRCode)) |>\n   select(n, Crime)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 2\n      n Crime                                   \n  <int> <chr>                                   \n1 31068 Destruction/Damage/Vandalism of Property\n```\n\n\n:::\n:::\n\n\n\n\n3. How many offenses are shootings?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnibrsCrm02 |>\n  filter(UCR.OFFENSE.CODE==\"13A\" &\n           OFFENSE.ATTEMPTED.COMPLETED==\"C\" &\n           (WEAPON.FORCE.1 %in% 11:15 |\n            WEAPON.FORCE.2 %in% 11:15 |\n            WEAPON.FORCE.3 %in% 11:15)) |>\n  count()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 1\n       n\n   <int>\n1 181371\n```\n\n\n:::\n:::\n\n\n\n\n4. What is the race distribution of shooting victims?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnibrsCrm02 |>\n  filter(UCR.OFFENSE.CODE==\"13A\" &\n         OFFENSE.ATTEMPTED.COMPLETED==\"C\" &\n         (WEAPON.FORCE.1 %in% 11:15 |\n          WEAPON.FORCE.2 %in% 11:15 |\n          WEAPON.FORCE.3 %in% 11:15)) |>\n  distinct() |>\n  left_join(nibrsVic04,\n            by=join_by(ORI, INCIDENT.NUMBER)) |>\n  group_by(RACE.OF.VICTIM, ETHNICITY.OF.VICTIM) |>\n  count()  |>\n  pivot_wider(names_from = ETHNICITY.OF.VICTIM,\n              values_from = n,\n              values_fill = 0) |>\n  print(n=Inf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 x 5\n# Groups:   RACE.OF.VICTIM [7]\n  RACE.OF.VICTIM     H      N     U  `NA`\n  <chr>          <int>  <int> <int> <int>\n1 A                165   2657   306   261\n2 B               1227 112878 11398 19727\n3 I                128   1726   271   434\n4 P                140    351    63    28\n5 U               2530   1456  5639  2046\n6 W              46833  57513  7952 13205\n7 <NA>               0      0     0 30829\n```\n\n\n:::\n:::\n\n\n\n\nHere's a little more complete version that makes sure the victim in the incident is one of the shooting victims and tabulates Hispanic as a race category. Some offenses might involve an offender hitting one person and shooting another. This code makes sure we just count the race of those actually shot.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnibrsCrm02 |>\n  filter(UCR.OFFENSE.CODE==\"13A\" &\n         OFFENSE.ATTEMPTED.COMPLETED==\"C\" &\n           (WEAPON.FORCE.1 %in% 11:15 |\n            WEAPON.FORCE.2 %in% 11:15 |\n            WEAPON.FORCE.3 %in% 11:15)) |>\n  select(ORI, INCIDENT.NUMBER) |>\n  distinct() |>\n  left_join(nibrsVic04 |> \n              filter(UCR.OFFENSE.CODE.1==\"13A\" | UCR.OFFENSE.CODE.2 ==\"13A\" | \n                     UCR.OFFENSE.CODE.3==\"13A\" | UCR.OFFENSE.CODE.4 ==\"13A\" | \n                     UCR.OFFENSE.CODE.5==\"13A\" | UCR.OFFENSE.CODE.6 ==\"13A\" | \n                     UCR.OFFENSE.CODE.7==\"13A\" | UCR.OFFENSE.CODE.8 ==\"13A\" | \n                     UCR.OFFENSE.CODE.9==\"13A\" | UCR.OFFENSE.CODE.10==\"13A\") |>\n              select(ORI,\n                     INCIDENT.NUMBER,\n                     RACE.OF.VICTIM,\n                     ETHNICITY.OF.VICTIM),\n            by=join_by(ORI, INCIDENT.NUMBER)) |>\n  mutate(race2=case_when(ETHNICITY.OF.VICTIM==\"H\" ~ \"H\",\n                         .default=RACE.OF.VICTIM)) |>\n  group_by(race2) |>\n  count()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 x 2\n# Groups:   race2 [7]\n  race2      n\n  <chr>  <int>\n1 A       2904\n2 B     134553\n3 H      47925\n4 I       2271\n5 P        412\n6 U       7833\n7 W      73097\n```\n\n\n:::\n:::\n\n\n\n\n5. How many cases are recorded as justifiable homicides?\n\nHere's the first idea. We can count \"criminal\" incidents involving UCR code 09C, justifiable homicide.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnibrsCrm02 |> \n  filter(UCR.OFFENSE.CODE==\"09C\") |>\n  count()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 1\n      n\n  <int>\n1   671\n```\n\n\n:::\n:::\n\n\n\n\nA second approach is to count victims, those killed by citizens (circumstance 20) and those killed by police (circumstance 21).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnibrsVic04 |> count(CIRCUMSTANCE.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 18 x 2\n   CIRCUMSTANCE.1        n\n   <chr>             <int>\n 1 01               294313\n 2 02                22595\n 3 03                 2136\n 4 04                 3066\n 5 05                 1905\n 6 06                99067\n 7 07                   16\n 8 08                 9620\n 9 09               143124\n10 10               184583\n11 20                  443\n12 21                  248\n13 30                   38\n14 31                   10\n15 32                    2\n16 33                  298\n17 34                 1670\n18 <NA>           13153518\n```\n\n\n:::\n\n```{.r .cell-code}\nnibrsVic04 |> count(CIRCUMSTANCE.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 x 2\n  CIRCUMSTANCE.2        n\n  <chr>             <int>\n1 02                  124\n2 03                  135\n3 04                  107\n4 05                  121\n5 06                 8209\n6 08                 1001\n7 09                 4629\n8 <NA>           13902326\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(nibrsVic04$CIRCUMSTANCE.1 %in% 20:21)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 691\n```\n\n\n:::\n\n```{.r .cell-code}\nnibrsVic04 |> count(ADDITIONAL.JUSTIFIABLE.HOMICIDE.CIRCUMSTANCES)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 x 2\n  ADDITIONAL.JUSTIFIABLE.HOMICIDE.CIRCUMSTANCES        n\n  <chr>                                            <int>\n1 A                                                  133\n2 B                                                   37\n3 C                                                  302\n4 D                                                    4\n5 E                                                  178\n6 F                                                   13\n7 G                                                   24\n8 <NA>                                          13915961\n```\n\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{ll}\n\\toprule\nCode & Description\\\\\n\\midrule\n20 & Criminal killed by private citizen\\\\\n\\cmidrule{1-2}\\pagebreak[0]\n21 & Criminal killed by police officer\\\\\n\\cmidrule{1-2}\\pagebreak[0]\nA & Criminal attacked police officer and that officer killed criminal\\\\\n\\cmidrule{1-2}\\pagebreak[0]\nB & Criminal attacked fellow police officer and criminal killed by another police officer\\\\\n\\cmidrule{1-2}\\pagebreak[0]\nC & Criminal attacked a civilian\\\\\n\\cmidrule{1-2}\\pagebreak[0]\nD & Criminal attempted flight from a crime\\\\\n\\cmidrule{1-2}\\pagebreak[0]\nE & Criminal killed in commission of a crime\\\\\n\\cmidrule{1-2}\\pagebreak[0]\nF & Criminal resisted arrest\\\\\n\\cmidrule{1-2}\\pagebreak[0]\nG & Unable to determine/not enough information\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n\n\nThe following code offers a more complete description of who committed the justifiable homicide and the reason for the homicide.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnibrsVic04 |>\n  filter(CIRCUMSTANCE.1 %in% c(\"20\",\"21\")) |>\n  count(CIRCUMSTANCE.1, ADDITIONAL.JUSTIFIABLE.HOMICIDE.CIRCUMSTANCES) |>\n  pivot_wider(names_from = ADDITIONAL.JUSTIFIABLE.HOMICIDE.CIRCUMSTANCES,\n              values_from = n,\n              values_fill = 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 x 8\n  CIRCUMSTANCE.1     B     C     D     E     G     A     F\n  <chr>          <int> <int> <int> <int> <int> <int> <int>\n1 20                 1   276     1   150    15     0     0\n2 21                36    26     3    28     9   133    13\n```\n\n\n:::\n:::\n\n\n\n\n6. Does NIBRS indicate that retail theft is rising? To examine trends we would need to load several years of NIBRS data. For now, let's just calculate the number of retail theft (23C) incidents reported to agencies that reported 12 months of NIBRS data.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnibrsCrm02 |>\n   select(ORI, INCIDENT.NUMBER, UCR.OFFENSE.CODE) |>\n   left_join(nibrsBH |> select(ORI,JANUARY:DECEMBER),\n             by=join_by(ORI)) |>\n   filter(UCR.OFFENSE.CODE==\"23C\" & # shoplifting\n             if_all(JANUARY:DECEMBER, # all months had some report\n                    function(x) x != \"NNN\")) |>\n   count()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 1\n       n\n   <int>\n1 945966\n```\n\n\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "\\usepackage{booktabs}\n\\usepackage{longtable}\n\\usepackage{array}\n\\usepackage{multirow}\n\\usepackage{wrapfig}\n\\usepackage{float}\n\\usepackage{colortbl}\n\\usepackage{pdflscape}\n\\usepackage{tabu}\n\\usepackage{threeparttable}\n\\usepackage{threeparttablex}\n\\usepackage[normalem]{ulem}\n\\usepackage{makecell}\n\\usepackage{xcolor}\n"
      ]
    },
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}